-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
checked_input as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order
    from {{ ref("reference__deal_stage_current__checked") }}
),
step_02_calculated_fields as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order,
        cast((row_number() over (partition by deal_external_identity order by stage_effective_from desc, stage_recorded_at desc)) as {{ dpf_type('int') }}) as stage_rank
    from checked_input
)

select
    stage_entity_type,
    deal_external_identity,
    stage_type_code,
    stage_value_code,
    stage_effective_from,
    stage_record_source,
    stage_load_datetime,
    stage_recorded_at,
    stage_key,
    classification_value_name,
    classification_sort_order,
    stage_rank
from step_02_calculated_fields
