-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        customer_external_id,
        segment,
        effective_from,
        record_source,
        load_datetime
    from {{ ref("reference__customer_segment_history__checked") }}
)

select
    customer_external_id,
    segment,
    effective_from,
    record_source,
    load_datetime
from checked_input
