-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        customer_external_id,
        segment,
        effective_from,
        record_source,
        load_datetime
    from {{ ref("reference__customer_segment__checked") }}
),
step_02_schema_transform as (
    select
        customer_external_id,
        cast(segment as {{ dpf_type('string') }}) as segment_name,
        cast(effective_from as {{ dpf_type('date') }}) as segment_effective_from,
        cast(record_source as {{ dpf_type('string') }}) as segment_record_source,
        cast(load_datetime as {{ dpf_type('timestamp') }}) as segment_load_datetime
    from checked_input
),
step_03_calculated_fields as (
    select
        customer_external_id,
        segment_name,
        segment_effective_from,
        segment_record_source,
        segment_load_datetime,
        cast((upper(segment_name)) as {{ dpf_type('string') }}) as segment_label
    from step_02_schema_transform
)

select
    customer_external_id,
    segment_name,
    segment_effective_from,
    segment_record_source,
    segment_load_datetime,
    segment_label
from step_03_calculated_fields
