-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        classification_type_code,
        classification_value_code,
        classification_value_name,
        sort_order,
        is_unknown
    from {{ ref("reference__investment_classification__checked") }}
),
step_02_schema_transform as (
    select
        cast(classification_type_code as {{ dpf_type('string') }}) as classification_type_code,
        cast(classification_value_code as {{ dpf_type('string') }}) as classification_value_code,
        cast(classification_value_name as {{ dpf_type('string') }}) as classification_value_name,
        cast(sort_order as {{ dpf_type('int') }}) as classification_sort_order,
        cast(is_unknown as {{ dpf_type('string') }}) as classification_unknown_text
    from checked_input
),
step_03_calculated_fields as (
    select
        classification_type_code,
        classification_value_code,
        classification_value_name,
        classification_sort_order,
        classification_unknown_text,
        cast((concat(classification_type_code, ':', classification_value_code)) as {{ dpf_type('string') }}) as classification_key,
        cast((classification_unknown_text = 'true') as {{ dpf_type('boolean') }}) as classification_is_unknown
    from step_02_schema_transform
),
step_04_data_enrichment as (
    select
        base.classification_type_code,
        base.classification_value_code,
        base.classification_value_name,
        base.classification_sort_order,
        base.classification_unknown_text,
        base.classification_key,
        base.classification_is_unknown,
        lookup_0.classification_type_name
    from step_03_calculated_fields as base
    left join {{ ref("reference__investment_classification_type") }} as lookup_0
        on base.classification_type_code = lookup_0.classification_type_code
)

select
    classification_type_code,
    classification_value_code,
    classification_value_name,
    classification_sort_order,
    classification_unknown_text,
    classification_key,
    classification_is_unknown,
    classification_type_name
from step_04_data_enrichment
