-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        entity_type,
        entity_external_id,
        classification_type_code,
        classification_value_code,
        effective_from,
        record_source,
        load_datetime,
        stage_recorded_at
    from {{ ref("reference__deal_stage_history__checked") }}
)

select
    entity_type,
    entity_external_id,
    classification_type_code,
    classification_value_code,
    effective_from,
    record_source,
    load_datetime,
    stage_recorded_at
from checked_input
