-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end
    from {{ ref("reference__investment_calendar__checked") }}
),
step_02_schema_transform as (
    select
        cast(calendar_date as {{ dpf_type('string') }}) as calendar_date_text,
        cast(year_number as {{ dpf_type('string') }}) as calendar_year_text,
        cast(quarter_number as {{ dpf_type('string') }}) as calendar_quarter_text,
        cast(month_number as {{ dpf_type('string') }}) as calendar_month_text,
        cast(month_start_date as {{ dpf_type('string') }}) as calendar_month_start_text,
        cast(quarter_start_date as {{ dpf_type('string') }}) as calendar_quarter_start_text,
        cast(is_month_end as {{ dpf_type('string') }}) as calendar_month_end_text,
        cast(is_quarter_end as {{ dpf_type('string') }}) as calendar_quarter_end_text
    from checked_input
),
step_03_calculated_fields as (
    select
        calendar_date_text,
        calendar_year_text,
        calendar_quarter_text,
        calendar_month_text,
        calendar_month_start_text,
        calendar_quarter_start_text,
        calendar_month_end_text,
        calendar_quarter_end_text,
        cast((calendar_date_text) as {{ dpf_type('date') }}) as calendar_date,
        cast((calendar_year_text) as {{ dpf_type('int') }}) as calendar_year,
        cast((calendar_quarter_text) as {{ dpf_type('int') }}) as calendar_quarter,
        cast((calendar_month_text) as {{ dpf_type('int') }}) as calendar_month,
        cast((calendar_month_start_text) as {{ dpf_type('date') }}) as calendar_month_start,
        cast((calendar_quarter_start_text) as {{ dpf_type('date') }}) as calendar_quarter_start,
        cast((calendar_month_end_text = 'true') as {{ dpf_type('boolean') }}) as calendar_is_month_end,
        cast((calendar_quarter_end_text = 'true') as {{ dpf_type('boolean') }}) as calendar_is_quarter_end,
        cast((concat(substr(calendar_date_text, 1, 4), '-Q', calendar_quarter_text)) as {{ dpf_type('string') }}) as calendar_quarter_label
    from step_02_schema_transform
)

select
    calendar_date_text,
    calendar_year_text,
    calendar_quarter_text,
    calendar_month_text,
    calendar_month_start_text,
    calendar_quarter_start_text,
    calendar_month_end_text,
    calendar_quarter_end_text,
    calendar_date,
    calendar_year,
    calendar_quarter,
    calendar_month,
    calendar_month_start,
    calendar_quarter_start,
    calendar_is_month_end,
    calendar_is_quarter_end,
    calendar_quarter_label
from step_03_calculated_fields
