-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order
    from {{ ref("reference__deal_stage") }}
),
step_00_batch_transfer as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order
    from source_00
)

select
    stage_entity_type,
    deal_external_identity,
    stage_type_code,
    stage_value_code,
    stage_effective_from,
    stage_record_source,
    stage_load_datetime,
    stage_recorded_at,
    stage_key,
    classification_value_name,
    classification_sort_order,
    coalesce(deal_external_identity is null, true) as violation_00,
    coalesce(stage_effective_from is null, true) as violation_01
from step_00_batch_transfer
