-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (stage_rank = 1) as predicate_00
    from {{ ref("reference__deal_stage_current__prefilter") }}
),
counted as (
    select
        'stage_in_force_only' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
