-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from {{ ref("entity_resolution_overlap_manifest") }}
)

select
    source_system,
    source_record_id,
    true_fund_external_id,
    overlap_note,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(source_record_id is not null and count(*) over (partition by source_record_id) > 1, true) as violation_01,
    coalesce(source_system is null, true) as violation_02,
    coalesce(true_fund_external_id is null, true) as violation_03
from source_00
