-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        classification_type_code,
        classification_value_code,
        classification_value_name,
        sort_order,
        is_unknown
    from {{ ref("reference__investment_classification_value") }}
),
step_00_batch_transfer as (
    select
        classification_type_code,
        classification_value_code,
        classification_value_name,
        sort_order,
        is_unknown
    from source_00
)

select
    classification_type_code,
    classification_value_code,
    classification_value_name,
    sort_order,
    is_unknown,
    coalesce(classification_type_code is null, true) as violation_00,
    coalesce(classification_value_code is null, true) as violation_01
from step_00_batch_transfer
