-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end,
        violation_00,
        violation_01
    from {{ ref("reference__investment_calendar_dates__checked") }}
),
violations as (
    select
        'calendar_date_not_null' as rule_name,
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end
    from quarantined
    where violation_00

    union all

    select
        'calendar_date_unique' as rule_name,
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end
    from quarantined
    where violation_01
)

select
    rule_name,
    calendar_date,
    year_number,
    quarter_number,
    month_number,
    day_of_month,
    month_start_date,
    quarter_start_date,
    is_month_end,
    is_quarter_end
from violations
