-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
checked_input as (
    select
        entity_type,
        entity_external_id,
        classification_type_code,
        classification_value_code,
        effective_from,
        record_source,
        load_datetime
    from {{ ref("reference__fund_department__checked") }}
),
step_02_schema_transform as (
    select
        cast(entity_type as {{ dpf_type('string') }}) as classification_entity_type,
        cast(entity_external_id as {{ dpf_type('string') }}) as fund_external_identity,
        cast(classification_type_code as {{ dpf_type('string') }}) as classification_type_code,
        cast(classification_value_code as {{ dpf_type('string') }}) as fund_department_code,
        cast(effective_from as {{ dpf_type('date') }}) as department_effective_from,
        cast(record_source as {{ dpf_type('string') }}) as classification_record_source,
        cast(load_datetime as {{ dpf_type('timestamp') }}) as classification_load_datetime
    from checked_input
),
step_03_calculated_fields as (
    select
        classification_entity_type,
        fund_external_identity,
        classification_type_code,
        fund_department_code,
        department_effective_from,
        classification_record_source,
        classification_load_datetime,
        cast((concat(classification_type_code, ':', fund_department_code)) as {{ dpf_type('string') }}) as classification_key,
        cast((concat(fund_external_identity, ':', classification_type_code)) as {{ dpf_type('string') }}) as fund_department_key
    from step_02_schema_transform
),
step_04_data_enrichment as (
    select
        base.classification_entity_type,
        base.fund_external_identity,
        base.classification_type_code,
        base.fund_department_code,
        base.department_effective_from,
        base.classification_record_source,
        base.classification_load_datetime,
        base.classification_key,
        base.fund_department_key,
        lookup_0.classification_value_name,
        lookup_0.classification_type_name
    from step_03_calculated_fields as base
    left join {{ ref("reference__investment_classification") }} as lookup_0
        on base.classification_key = lookup_0.classification_key
)

select
    classification_entity_type,
    fund_external_identity,
    classification_type_code,
    fund_department_code,
    department_effective_from,
    classification_record_source,
    classification_load_datetime,
    classification_key,
    fund_department_key,
    classification_value_name,
    classification_type_name
from step_04_data_enrichment
