-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        entity_type,
        entity_external_id,
        classification_type_code,
        classification_value_code,
        effective_from,
        record_source,
        load_datetime,
        stage_recorded_at
    from {{ ref("reference__deal_stage__checked") }}
),
step_02_schema_transform as (
    select
        cast(entity_type as {{ dpf_type('string') }}) as stage_entity_type,
        cast(entity_external_id as {{ dpf_type('string') }}) as deal_external_identity,
        cast(classification_type_code as {{ dpf_type('string') }}) as stage_type_code,
        cast(classification_value_code as {{ dpf_type('string') }}) as stage_value_code,
        cast(effective_from as {{ dpf_type('date') }}) as stage_effective_from,
        cast(record_source as {{ dpf_type('string') }}) as stage_record_source,
        cast(load_datetime as {{ dpf_type('timestamp') }}) as stage_load_datetime,
        cast(stage_recorded_at as {{ dpf_type('timestamp') }}) as stage_recorded_at
    from checked_input
),
step_03_calculated_fields as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        cast((concat(stage_type_code, ':', stage_value_code)) as {{ dpf_type('string') }}) as stage_key
    from step_02_schema_transform
),
step_04_data_enrichment as (
    select
        base.stage_entity_type,
        base.deal_external_identity,
        base.stage_type_code,
        base.stage_value_code,
        base.stage_effective_from,
        base.stage_record_source,
        base.stage_load_datetime,
        base.stage_recorded_at,
        base.stage_key,
        lookup_0.classification_value_name,
        lookup_0.classification_sort_order
    from step_03_calculated_fields as base
    left join {{ ref("reference__investment_classification") }} as lookup_0
        on base.stage_key = lookup_0.classification_key
)

select
    stage_entity_type,
    deal_external_identity,
    stage_type_code,
    stage_value_code,
    stage_effective_from,
    stage_record_source,
    stage_load_datetime,
    stage_recorded_at,
    stage_key,
    classification_value_name,
    classification_sort_order
from step_04_data_enrichment
