-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        customer_external_id,
        segment,
        effective_from,
        record_source,
        load_datetime
    from {{ ref("customer_segment_history_seed") }}
)

select
    customer_external_id,
    segment,
    effective_from,
    record_source,
    load_datetime,
    coalesce(customer_external_id is null, true) as violation_00,
    coalesce(segment is null, true) as violation_01,
    coalesce(effective_from is null, true) as violation_02
from source_00
