-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_system,
        source_record_id,
        true_customer_external_id,
        overlap_note
    from {{ ref("reference__customer_identity__checked") }}
),
step_02_schema_transform as (
    select
        cast(source_system as {{ dpf_type('string') }}) as identity_source_system,
        cast(source_record_id as {{ dpf_type('string') }}) as identity_source_record_id,
        cast(true_customer_external_id as {{ dpf_type('string') }}) as customer_external_id,
        cast(overlap_note as {{ dpf_type('string') }}) as customer_identity_note
    from checked_input
),
step_03_calculated_fields as (
    select
        identity_source_system,
        identity_source_record_id,
        customer_external_id,
        customer_identity_note,
        cast((concat(identity_source_system, ':', identity_source_record_id)) as {{ dpf_type('string') }}) as customer_identity_key
    from step_02_schema_transform
)

select
    identity_source_system,
    identity_source_record_id,
    customer_external_id,
    customer_identity_note,
    customer_identity_key
from step_03_calculated_fields
