-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note,
        violation_00,
        violation_01,
        violation_02,
        violation_03
    from {{ ref("reference__fund_overlap_manifest__checked") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from quarantined
    where violation_00

    union all

    select
        'source_record_id_unique' as rule_name,
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from quarantined
    where violation_01

    union all

    select
        'source_system_not_null' as rule_name,
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from quarantined
    where violation_02

    union all

    select
        'true_fund_external_id_not_null' as rule_name,
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from quarantined
    where violation_03
)

select
    rule_name,
    source_system,
    source_record_id,
    true_fund_external_id,
    overlap_note
from violations
