-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
prefilter_input as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order,
        stage_rank
    from {{ ref("reference__deal_stage_current__prefilter") }}
),
step_03_data_filtering as (
    select
        stage_entity_type,
        deal_external_identity,
        stage_type_code,
        stage_value_code,
        stage_effective_from,
        stage_record_source,
        stage_load_datetime,
        stage_recorded_at,
        stage_key,
        classification_value_name,
        classification_sort_order,
        stage_rank
    from prefilter_input
    where (stage_rank = 1)
)

select
    stage_entity_type,
    deal_external_identity,
    stage_type_code,
    stage_value_code,
    stage_effective_from,
    stage_record_source,
    stage_load_datetime,
    stage_recorded_at,
    stage_key,
    classification_value_name,
    classification_sort_order,
    stage_rank
from step_03_data_filtering
