-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (classification_entity_type = 'FUND' and classification_type_code = 'DEPT') as predicate_00
    from {{ ref("reference__fund_department__prefilter") }}
),
counted as (
    select
        'fund_department_history_only' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
