-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
prefilter_input as (
    select
        classification_entity_type,
        fund_external_identity,
        classification_type_code,
        fund_department_code,
        department_effective_from,
        classification_record_source,
        classification_load_datetime,
        classification_key,
        fund_department_key,
        classification_value_name,
        classification_type_name
    from {{ ref("reference__fund_department__prefilter") }}
),
step_05_data_filtering as (
    select
        classification_entity_type,
        fund_external_identity,
        classification_type_code,
        fund_department_code,
        department_effective_from,
        classification_record_source,
        classification_load_datetime,
        classification_key,
        fund_department_key,
        classification_value_name,
        classification_type_name
    from prefilter_input
    where (classification_entity_type = 'FUND' and classification_type_code = 'DEPT')
)

select
    classification_entity_type,
    fund_external_identity,
    classification_type_code,
    fund_department_code,
    department_effective_from,
    classification_record_source,
    classification_load_datetime,
    classification_key,
    fund_department_key,
    classification_value_name,
    classification_type_name
from step_05_data_filtering
