-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        classification_type_code,
        classification_type_name,
        description,
        violation_00,
        violation_01,
        violation_02
    from {{ ref("reference__investment_classification_type__checked") }}
),
violations as (
    select
        'classification_type_code_not_null' as rule_name,
        classification_type_code,
        classification_type_name,
        description
    from quarantined
    where violation_00

    union all

    select
        'classification_type_code_unique' as rule_name,
        classification_type_code,
        classification_type_name,
        description
    from quarantined
    where violation_01

    union all

    select
        'classification_type_name_not_null' as rule_name,
        classification_type_code,
        classification_type_name,
        description
    from quarantined
    where violation_02
)

select
    rule_name,
    classification_type_code,
    classification_type_name,
    description
from violations
