-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from {{ ref("reference__fund_overlap_manifest") }}
),
step_00_batch_transfer as (
    select
        source_system,
        source_record_id,
        true_fund_external_id,
        overlap_note
    from source_00
)

select
    source_system,
    source_record_id,
    true_fund_external_id,
    overlap_note,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(true_fund_external_id is null, true) as violation_01
from step_00_batch_transfer
