-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end
    from {{ ref("reference__investment_calendar_dates") }}
),
step_00_batch_transfer as (
    select
        calendar_date,
        year_number,
        quarter_number,
        month_number,
        day_of_month,
        month_start_date,
        quarter_start_date,
        is_month_end,
        is_quarter_end
    from source_00
)

select
    calendar_date,
    year_number,
    quarter_number,
    month_number,
    day_of_month,
    month_start_date,
    quarter_start_date,
    is_month_end,
    is_quarter_end,
    coalesce(calendar_date is null, true) as violation_00,
    coalesce(calendar_date is not null and count(*) over (partition by calendar_date) > 1, true) as violation_01
from step_00_batch_transfer
