-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_vantora_vehicle_cash_flows' -%}
{%- set src_pk = 'legal_vehicle_hk' -%}
{%- set src_hashdiff = 'legal_vehicle_cash_flow_hashdiff' -%}
{%- set src_payload = ['cash_flow_id',
 'vehicle_natural_id',
 'cash_flow_date',
 'cash_flow_type',
 'direction',
 'amount_usd',
 'currency'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
