-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_portiq_portfolio_companies' -%}
{%- set src_pk = 'portfolio_company_hk' -%}
{%- set src_hashdiff = 'portfolio_company_hashdiff' -%}
{%- set src_payload = ['source_company_id',
 'source_fund_id',
 'company_name',
 'lei',
 'shared_external_id',
 'sector',
 'sub_sector',
 'country',
 'status',
 'first_seen_at',
 'portfolio_company_resolution_tier',
 'portfolio_company_resolution_confidence'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
