-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_mercaro_customers' -%}
{%- set src_pk = 'customer_hk' -%}
{%- set src_hashdiff = 'customer_hashdiff' -%}
{%- set src_payload = ['source_record_id',
 'source_customer_id',
 'loyalty_id',
 'email',
 'full_name',
 'phone',
 'address_line',
 'city',
 'postal_code',
 'country',
 'marketing_consent',
 'preferred_channel',
 'buyer_segment',
 'customer_status',
 'as_of_date',
 'customer_resolution_tier',
 'customer_resolution_confidence'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
