-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_mercaro_orders' -%}
{%- set src_pk = 'order_hk' -%}
{%- set src_hashdiff = 'order_hashdiff' -%}
{%- set src_payload = ['source_record_id',
 'source_order_id',
 'source_customer_id',
 'order_date',
 'order_status',
 'currency',
 'order_total',
 'channel',
 'customer_resolution_tier',
 'customer_resolution_confidence'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
