-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_chrono_valuations' -%}
{%- set src_pk = 'fund_hk' -%}
{%- set src_hashdiff = 'fund_valuation_hashdiff' -%}
{%- set src_payload = ['valuation_id',
 'source_fund_id',
 'source_company_id',
 'valuation_date',
 'value_usd',
 'method',
 'valuation_level',
 'confidence_score',
 'golden_portfolio_company_key',
 'fund_resolution_tier',
 'fund_resolution_confidence',
 'portfolio_company_resolution_tier',
 'portfolio_company_resolution_confidence'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
