-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_origo_deals' -%}
{%- set src_pk = 'deal_hk' -%}
{%- set src_hashdiff = 'deal_hashdiff' -%}
{%- set src_payload = ['source_record_id',
 'source_deal_id',
 'external_deal_id',
 'deal_name',
 'target_entity_id',
 'strategy',
 'originating_team',
 'source_channel',
 'sourced_date',
 'structure',
 'converted_record_type',
 'converted_record_id',
 'deal_resolution_tier',
 'deal_resolution_confidence'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
