-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'stg_dv_vantora_succession_events' -%}
{%- set src_pk = 'gp_succession_lhk' -%}
{%- set src_hashdiff = 'gp_succession_hashdiff' -%}
{%- set src_payload = ['succession_event_id',
 'predecessor_source_gp_id',
 'successor_source_gp_id',
 'event_type',
 'effective_date'] -%}
{%- set src_eff = 'effective_from' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.sat(
    src_pk=src_pk,
    src_hashdiff=src_hashdiff,
    src_payload=src_payload,
    src_extra_columns=none,
    src_eff=src_eff,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
