"""Per-target dialect lint for Snowflake, BigQuery, and DuckDB SQL.

No dbt model or singular test -- whether emitted or hand-authored -- may carry SQL
that is incompatible with its selected adapter. Each registered adapter's
deny-list names constructs exclusive to another dialect, and every registered
adapter must declare at least one rule so a new target cannot silently skip linting.

The scanner covers generated and hand-authored SQL under ``models/`` and ``tests/``.
Generated violations are fixed in their template or declaration; hand-authored
violations are fixed in the SQL file itself.

Dialect-specific SQL is legitimate in ONE place only: the adapter-dispatch macros
under `macros/` (e.g. cross_db.sql). Those are the sanctioned translation layer and
are never scanned here.

Usage:
    python ergasterion/dialect_lint.py                 # lint all model SQL for snowflake
    python ergasterion/dialect_lint.py --target snowflake
    python ergasterion/dialect_lint.py --target bigquery
    python ergasterion/dialect_lint.py --target duckdb

Exit code 0 = clean, 1 = offenders found. Importable via `lint_models()` (all models)
and `lint_emitted()` (emitted only) so the emitter can run it as a post-emit gate
(SSOT: this module owns the deny-list).
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Support installed-command and direct-script execution.
if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion.estate import EstateContext

# Ambient estate context; scan functions default to it, a caller threads its own via `ctx=`.
_DEFAULT_CTX = EstateContext.default()

# ESTATE paths -- ride the context. Aliases kept for back-compat reads.
REPO_ROOT = _DEFAULT_CTX.root
MODELS_DIR = _DEFAULT_CTX.models_dir
# Singular tests are executable warehouse SQL and use the same deny-list as models.
TESTS_DIR = _DEFAULT_CTX.tests_dir

# Marker written by ergasterion/emit.py into every generated SQL model. Only files
# carrying it are linted -- this is the precise, self-maintaining definition of
# "emitted SQL".
GENERATED_MARKER = "Generated by ergasterion/emit.py"


@dataclass(frozen=True)
class DenyRule:
    token: str
    pattern: re.Pattern[str]
    message: str


def _rule(token: str, regex: str, message: str) -> DenyRule:
    return DenyRule(token=token, pattern=re.compile(regex, re.IGNORECASE), message=message)


# BigQuery-only constructs that break on Snowflake. Keyed by the target dialect the
# lint is guarding: when emitting for `snowflake`, none of these BigQuery idioms may
# appear in generated SQL. The neutralised forms (dpf_safe_cast / dbt.safe_cast /
# dpf_regexp_* / QUALIFY / union-all) render cleanly on all three supported adapters and match none
# of these patterns.
BIGQUERY_DENY: list[DenyRule] = [
    # `safe_cast` bare (BigQuery). Excludes dbt.safe_cast / dpf_safe_cast (preceded
    # by a word char or a dot), which are the sanctioned cross-db macro calls.
    _rule("safe_cast", r"(?<![\w.])safe_cast\s*\(", "BigQuery safe_cast(...) -- route via {{ dpf_safe_cast(...) }}"),
    _rule("int64", r"\bint64\b", "BigQuery type INT64 -- use dbt.type_int()"),
    _rule("float64", r"\bfloat64\b", "BigQuery type FLOAT64 -- use dbt.type_float()"),
    _rule("regexp_contains", r"\bregexp_contains\s*\(", "BigQuery regexp_contains(...) -- route via {{ dpf_regexp_contains(...) }}"),
    _rule("regexp_extract", r"\bregexp_extract\s*\(", "BigQuery regexp_extract(...) -- route via {{ dpf_regexp_extract(...) }}"),
    _rule("raw_string", r"(?<![\w])r'", "BigQuery raw-string literal r'...' -- use a plain quoted pattern"),
    _rule("unnest", r"\bunnest\s*\(", "BigQuery UNNEST(...) -- rewrite dialect-neutrally (union-all / QUALIFY)"),
    _rule("struct", r"\bstruct\s*\(", "BigQuery STRUCT(...) -- rewrite without struct/array construction"),
    _rule("select_except", r"\*\s*except\s*\(", "BigQuery SELECT * EXCEPT(...) -- list columns explicitly or use QUALIFY"),
    _rule("to_json_string", r"\bto_json_string\s*\(", "BigQuery to_json_string(...) -- route via a cross-db JSON macro"),
    _rule("to_hex", r"\bto_hex\s*\(", "BigQuery to_hex(...) -- route via {{ dpf_hash_hex(...) }}"),
    _rule("format_date", r"\bformat_date\s*\(", "BigQuery format_date(...) -- use a cross-db date-format macro"),
    _rule("generate_date_array", r"\bgenerate_date_array\s*\(", "BigQuery generate_date_array(...) -- use dbt_utils.date_spine"),
    _rule("string_agg", r"\bstring_agg\s*\(", "BigQuery string_agg(...) -- route via {{ dpf_string_agg(...) }}"),
    _rule("safe_divide", r"\bsafe_divide\s*\(", "BigQuery safe_divide(...) -- use (a) / nullif(b, 0)"),
    _rule("array_type", r"\barray\s*<", "BigQuery array<...> type -- route via {{ dpf_array(...) }} / {{ dpf_empty_array(...) }}"),
    _rule("bool_type", r"\bas\s+bool\b", "BigQuery BOOL type -- Snowflake uses BOOLEAN"),
    # BigQuery array literal [a, b] / [col]. Requires an identifier immediately after
    # the bracket so Jinja/dbt list literals (['col', 'col'] -> starts with a quote)
    # and index/empty forms ([0], []) are not matched. Route via {{ dpf_array(...) }}.
    _rule("array_literal", r"\[\s*[a-zA-Z_][\w.]*\s*[,\]]", "BigQuery array literal [...] -- route via {{ dpf_array(...) }} / {{ dpf_empty_array(...) }}"),
]

# Snowflake-only constructs that break on BigQuery. Adapter-dispatch macros are the
# sanctioned home for these forms and are outside the scan; models and tests must
# call the dialect-neutral macro instead. Patterns require SQL-shaped usage so prose
# such as a comment mentioning a "variant" does not become an offense.
SNOWFLAKE_DENY: list[DenyRule] = [
    _rule("variant", r"(?:(?:::|\bas\s+)\s*variant\b|\bvariant\s*\()", "Snowflake VARIANT type -- route via a cross-db JSON macro"),
    _rule("object_construct", r"\bobject_construct(?:_keep_null)?\s*\(", "Snowflake object_construct(...) -- route via {{ dpf_to_json_object(...) }}"),
    _rule("object_agg", r"\bobject_agg\s*\(", "Snowflake object_agg(...) -- route via {{ dpf_map_agg(...) }}"),
    _rule("array_construct", r"\barray_construct\s*\(", "Snowflake array_construct(...) -- route via {{ dpf_array(...) }} / {{ dpf_empty_array(...) }}"),
    _rule("listagg", r"\blistagg\s*\(", "Snowflake listagg(...) within group -- route via {{ dpf_string_agg(...) }}"),
    _rule("iff", r"\biff\s*\(", "Snowflake iff(...) -- use CASE"),
    _rule("to_varchar", r"\bto_varchar\s*\(", "Snowflake to_varchar(...) -- route via a cross-db cast macro"),
    _rule("try_to", r"\btry_to_[a-z][a-z0-9_]*\s*\(", "Snowflake TRY_TO_* conversion -- route via a cross-db cast macro"),
    _rule("div0", r"\bdiv0\s*\(", "Snowflake div0(...) -- use (a) / nullif(b, 0)"),
    _rule("zeroifnull", r"\bzeroifnull\s*\(", "Snowflake zeroifnull(...) -- use coalesce(..., 0)"),
    _rule("regexp_substr", r"\bregexp_substr\s*\(", "Snowflake regexp_substr(...) -- route via {{ dpf_regexp_extract(...) }}"),
    _rule("regexp_instr", r"\bregexp_instr\s*\(", "Snowflake regexp_instr(...) -- route via {{ dpf_regexp_contains(...) }}"),
    _rule("table_generator", r"\btable\s*\(\s*generator\s*\(", "Snowflake table(generator(...)) -- route via a cross-db series macro"),
    _rule("regexp_like", r"\bregexp_like\s*\(", "Snowflake regexp_like(...) is anchored -- route via {{ dpf_regexp_contains(...) }} for cross-adapter identity"),
]

# BigQuery and Snowflake forms that either fail on DuckDB or silently change the
# established dpf_* semantics there. This is deliberately the closed E2 override
# surface, rather than a generic catalogue of every DuckDB extension: models and
# tests use the dispatch macros for these behaviours, while neutral SQL remains
# unflagged. The timestamp_ltz rule is the one target-specific addition from E3.
DUCKDB_DENY: list[DenyRule] = [
    _rule("safe_cast", r"(?<![\w.])safe_cast\s*\(", "BigQuery safe_cast(...) -- route via {{ dpf_safe_cast(...) }}"),
    _rule("safe_parse_json", r"\bsafe\.parse_json\s*\(", "BigQuery safe.parse_json(...) -- route via {{ dpf_json_cast(...) }}"),
    _rule("json_type", r"\bjson_type\s*\(", "BigQuery json_type(...) -- route via {{ dpf_json_cast(...) }}"),
    _rule("json_value", r"\bjson_value\s*\(", "BigQuery json_value(...) -- route via {{ dpf_json_cast(...) }}"),
    _rule("to_hex", r"\bto_hex\s*\(", "BigQuery to_hex(...) -- route via {{ dpf_hash_hex(...) }}"),
    _rule("to_json_string", r"\bto_json_string\s*\(", "BigQuery to_json_string(...) -- route via {{ dpf_to_json_object(...) }} / {{ dpf_map_agg(...) }}"),
    _rule("struct", r"\bstruct\s*\(", "BigQuery struct(...) -- route via {{ dpf_to_json_object(...) }}"),
    _rule("object_construct", r"\bobject_construct(?:_keep_null)?\s*\(", "Snowflake object_construct(...) -- route via {{ dpf_to_json_object(...) }}"),
    _rule("object_agg", r"\bobject_agg\s*\(", "Snowflake object_agg(...) -- route via {{ dpf_map_agg(...) }}"),
    _rule("to_variant", r"\bto_variant\s*\(", "Snowflake to_variant(...) -- route via {{ dpf_json_cast(...) }} / {{ dpf_map_agg(...) }}"),
    # DuckDB accepts a fourth 'g' flag for global replacement. Its three-argument
    # spelling replaces only the first match, unlike the global BigQuery/Snowflake
    # form, so direct three-argument calls are unsafe even when they parse.
    # The actual call-shape recognition sits in _duckdb_regexp_replace_offenses()
    # below: a regexp cannot safely distinguish nested or multiline three-argument
    # calls from the sanctioned four-argument 'g' form.
    _rule("regexp_replace_global", r"(?!)", "Three-argument regexp_replace(...) is first-match-only on DuckDB -- route via {{ dpf_regexp_replace(...) }}"),
    _rule("regexp_contains", r"\bregexp_contains\s*\(", "BigQuery regexp_contains(...) -- route via {{ dpf_regexp_contains(...) }}"),
    _rule("regexp_extract", r"\bregexp_extract\s*\(", "BigQuery regexp_extract(...) -- route via {{ dpf_regexp_extract(...) }}"),
    _rule("regexp_substr", r"\bregexp_substr\s*\(", "Snowflake regexp_substr(...) -- route via {{ dpf_regexp_extract(...) }}"),
    _rule("regexp_instr", r"\bregexp_instr\s*\(", "Snowflake regexp_instr(...) -- route via {{ dpf_regexp_contains(...) }}"),
    _rule("array_type", r"\barray\s*<", "BigQuery array<...> type -- route via {{ dpf_empty_array(...) }}"),
    _rule("date_trunc_bigquery_order", r"\bdate_trunc\s*\(\s*[^'\"(),][^,()]*\s*,\s*(?:day|month|quarter|year)\b", "BigQuery date_trunc(date, part) argument order -- route via {{ dpf_date_trunc(...) }}"),
    _rule("generate_date_array", r"\bgenerate_date_array\s*\(", "BigQuery generate_date_array(...) -- route via {{ dpf_date_series(...) }}"),
    _rule("edit_distance", r"\bedit_distance\s*\(", "BigQuery edit_distance(...) -- route via {{ dpf_edit_distance(...) }}"),
    _rule("editdistance", r"\beditdistance\s*\(", "Snowflake editdistance(...) -- route via {{ dpf_edit_distance(...) }}"),
    _rule("date_diff_bigquery_order", r"\bdate_diff\s*\(\s*[^,()]+\s*,\s*[^,()]+\s*,\s*(?:day|month|quarter|year)\b", "BigQuery date_diff(date_a, date_b, part) -- route via {{ dpf_date_diff_days(...) }}"),
    _rule("datediff", r"\bdatediff\s*\(", "Snowflake datediff(...) has different argument order -- route via {{ dpf_date_diff_days(...) }}"),
    _rule("array_construct", r"\barray_construct\s*\(", "Snowflake array_construct(...) -- route via {{ dpf_array(...) }} / {{ dpf_empty_array(...) }}"),
    _rule("dateadd", r"\bdateadd\s*\(", "Snowflake dateadd(...) -- route via {{ dpf_date_series(...) }}"),
    _rule("table_generator", r"\btable\s*\(\s*generator\s*\(", "Snowflake table(generator(...)) -- route via {{ dpf_date_series(...) }}"),
    _rule("timestamp_ltz", r"\btimestamp_ltz\b", "Snowflake TIMESTAMP_LTZ -- DuckDB uses TIMESTAMP through the decision-log type macro"),
]

DENY_LISTS: dict[str, list[DenyRule]] = {
    "snowflake": BIGQUERY_DENY,
    "bigquery": SNOWFLAKE_DENY,
    "duckdb": DUCKDB_DENY,
}


@dataclass(frozen=True)
class Offense:
    path: Path
    line_no: int
    token: str
    message: str
    line: str


def _is_generated(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8")[:400]
    except OSError:
        return False
    return GENERATED_MARKER in head


def emitted_sql_files(ctx: EstateContext | None = None) -> list[Path]:
    return [p for p in sorted((ctx or _DEFAULT_CTX).models_dir.rglob("*.sql")) if _is_generated(p)]


def test_sql_files(ctx: EstateContext | None = None) -> list[Path]:
    """Return hand-authored singular tests under ``tests/*.sql``.

    Never carries the emitted marker (the emitter does not write tests/), so every
    file here is hand-authored by definition -- same class as a hand-authored model:
    dbt executes it straight against the warehouse and it must be dialect-neutral at
    its own SSOT (the test file itself).
    """
    tests_dir = (ctx or _DEFAULT_CTX).tests_dir
    return sorted(tests_dir.rglob("*.sql")) if tests_dir.is_dir() else []


def hand_authored_sql_files(ctx: EstateContext | None = None) -> list[Path]:
    """Model SQL WITHOUT the generated marker -- edited directly at its own SSOT.

    These carry the same adapter-specific risk as generated SQL.
    They are neutralised via the cross-db macros (macros/cross_db.sql), which are the
    one sanctioned home for dialect-specific SQL and are never scanned here. Does NOT
    include tests/ -- see test_sql_files(), scanned as its own hand-authored class.
    """
    return [p for p in sorted((ctx or _DEFAULT_CTX).models_dir.rglob("*.sql")) if not _is_generated(p)]


def model_sql_files(ctx: EstateContext | None = None) -> list[Path]:
    """Every model SQL file -- emitted and hand-authored alike (models/ only)."""
    return sorted((ctx or _DEFAULT_CTX).models_dir.rglob("*.sql"))


_SNOWFLAKE_DDL_PIN_BRANCH = re.compile(
    r"{%\s*elif\s+target\.type\s*==\s*'snowflake'\s*%}(.*?){%\s*else\s*%}",
    re.DOTALL | re.IGNORECASE,
)


def _snowflake_ddl_pin_timestamp_lines(path: Path, text: str) -> set[int]:
    """Return the exact expected-DDL token lines in E3's Snowflake Jinja branch."""
    if not path.as_posix().endswith("tests/assert_er_decisions_log_ddl_unchanged.sql"):
        return set()
    branch = _SNOWFLAKE_DDL_PIN_BRANCH.search(text)
    if branch is None:
        return set()
    branch_start_line = text[: branch.start(1)].count("\n") + 1
    return {
        branch_start_line + offset
        for offset, branch_line in enumerate(branch.group(1).splitlines())
        if branch_line.strip().lower() == "reviewed_at timestamp_ltz,"
    }


def _duckdb_ddl_pin_exemption(path: Path, rule: DenyRule, line_no: int, allowed_lines: set[int]) -> bool:
    """Allow exactly E3's Snowflake expectation in the cross-target DDL pin.

    The singular test deliberately contains a Snowflake expected-DDL branch next to
    its DuckDB expectation. It remains scanned for every other DuckDB rule, and this
    exception is intentionally narrower than a file skip: only its exact
    ``reviewed_at timestamp_ltz,`` expectation is permitted.
    """
    return rule.token == "timestamp_ltz" and line_no in allowed_lines


def _quoted_or_nested_call_end(text: str, opening_paren: int) -> int | None:
    """Find the matching close paren while respecting SQL quotes and nested calls."""
    depth = 1
    quote: str | None = None
    index = opening_paren + 1
    while index < len(text):
        char = text[index]
        if quote:
            if char == quote:
                if quote == "'" and index + 1 < len(text) and text[index + 1] == "'":
                    index += 2
                    continue
                quote = None
            elif char == "\\" and index + 1 < len(text):
                index += 2
                continue
        elif char in ("'", '"'):
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return None


def _top_level_call_arguments(body: str) -> list[str]:
    """Split one function body at commas outside quoted/nested expressions."""
    arguments: list[str] = []
    start = 0
    depth = 0
    quote: str | None = None
    index = 0
    while index < len(body):
        char = body[index]
        if quote:
            if char == quote:
                if quote == "'" and index + 1 < len(body) and body[index + 1] == "'":
                    index += 2
                    continue
                quote = None
            elif char == "\\" and index + 1 < len(body):
                index += 2
                continue
        elif char in ("'", '"'):
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            arguments.append(body[start:index].strip())
            start = index + 1
        index += 1
    arguments.append(body[start:].strip())
    return arguments


def _duckdb_regexp_replace_offenses(path: Path, text: str, rule: DenyRule) -> list[Offense]:
    """Catch direct regexp_replace calls unless they carry DuckDB's global flag.

    E2 established global replacement as the factory semantic. DuckDB's default
    three-argument call replaces only the first match, so this small delimiter-aware
    scanner intentionally supports nested expressions, capture-pattern strings, and
    multiline formatting that a line-level regular expression cannot classify.
    """
    offenses: list[Offense] = []
    for match in re.finditer(r"\bregexp_replace\s*\(", text, re.IGNORECASE):
        opening_paren = text.find("(", match.start(), match.end())
        closing_paren = _quoted_or_nested_call_end(text, opening_paren)
        if closing_paren is None:
            continue
        arguments = _top_level_call_arguments(text[opening_paren + 1 : closing_paren])
        if len(arguments) == 4 and arguments[-1].strip().lower() == "'g'":
            continue
        line_no = text.count("\n", 0, match.start()) + 1
        line = text.splitlines()[line_no - 1].strip()
        offenses.append(
            Offense(
                path=path,
                line_no=line_no,
                token=rule.token,
                message=rule.message,
                line=line,
            )
        )
    return offenses


def scan(files: list[Path], rules: list[DenyRule]) -> list[Offense]:
    offenses: list[Offense] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        allowed_ddl_pin_lines = _snowflake_ddl_pin_timestamp_lines(path, text)
        regexp_replace_rule = next((rule for rule in rules if rule.token == "regexp_replace_global"), None)
        if regexp_replace_rule is not None:
            offenses.extend(_duckdb_regexp_replace_offenses(path, text, regexp_replace_rule))
        for line_no, line in enumerate(text.splitlines(), start=1):
            for rule in rules:
                if rule.token == "regexp_replace_global":
                    continue
                if rule.pattern.search(line):
                    if _duckdb_ddl_pin_exemption(path, rule, line_no, allowed_ddl_pin_lines):
                        continue
                    offenses.append(
                        Offense(
                            path=path,
                            line_no=line_no,
                            token=rule.token,
                            message=rule.message,
                            line=line.strip(),
                        )
                    )
    return offenses


def _rules_for(target: str) -> list[DenyRule]:
    empty_adapters = sorted(adapter for adapter, rules in DENY_LISTS.items() if not rules)
    if empty_adapters:
        raise ValueError(
            "dialect_lint: empty deny-list for registered adapter(s): "
            f"{', '.join(empty_adapters)} -- every registered adapter must declare "
            "at least one portability rule"
        )
    rules = DENY_LISTS.get(target)
    if rules is None:
        raise ValueError(f"dialect_lint: unknown target {target!r} (known: {sorted(DENY_LISTS)})")
    return rules


def lint_emitted(target: str = "snowflake", *, ctx: EstateContext | None = None) -> list[Offense]:
    """Scan emitted SQL for BigQuery-only constructs for the given emit target.

    Returns the list of offenses (empty == clean). Importable by the emitter so the
    deny-list lives in exactly one place.
    """
    return scan(emitted_sql_files(ctx), _rules_for(target))


def lint_models(target: str = "snowflake", *, ctx: EstateContext | None = None) -> list[Offense]:
    """Scan ALL model SQL and test SQL -- emitted AND hand-authored -- for the target.

    This is the comprehensive gate. Dialect-specific SQL is legitimate only inside the
    cross-db macros (macros/cross_db.sql), which are never scanned; every model and
    every test, whether the emitter wrote it or a human did, must be dialect-neutral
    at its own source file.
    """
    return scan(model_sql_files(ctx) + test_sql_files(ctx), _rules_for(target))


def main() -> int:
    parser = argparse.ArgumentParser(description="Per-adapter dialect lint over emitted SQL.")
    parser.add_argument(
        "--target",
        default="snowflake",
        choices=sorted(DENY_LISTS),
        help="Emit target whose dialect deny-list to enforce (default: snowflake).",
    )
    parser.add_argument(
        "--estate-root",
        type=Path,
        default=None,
        help="Estate root to lint (resolved from the environment or working directory when omitted).",
    )
    args = parser.parse_args()

    ctx = EstateContext.resolve(estate_root=args.estate_root)
    emitted = emitted_sql_files(ctx)
    hand_authored = hand_authored_sql_files(ctx)
    tests = test_sql_files(ctx)
    offenses = lint_models(args.target, ctx=ctx)

    if offenses:
        print(f"dialect-lint FAIL [{args.target}]: {len(offenses)} offender(s) in model/test SQL")
        for off in offenses:
            rel = off.path.relative_to(ctx.root).as_posix()
            kind = "emitted" if _is_generated(off.path) else "hand-authored"
            print(f"  {rel}:{off.line_no}  [{off.token}]  ({kind})  {off.message}")
            print(f"      > {off.line}")
        return 1

    print(
        f"dialect-lint OK [{args.target}]: "
        f"{len(emitted)} emitted + {len(hand_authored)} hand-authored model + "
        f"{len(tests)} test SQL file(s) clean"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
