"""Deterministic property-graph projection-suite emitter.

Sibling generator to ergasterion/emit.py, ergasterion/emit_contracts.py, and
ergasterion/emit_odps.py. It emits one graph artefact suite per domains/<name>.yml under
graphs/<domain>/:

  - <domain>-nodes.csv
  - <domain>-edges.csv
  - <domain>-graph.cypher
  - <domain>-graph.pgq.sql
  - <domain>-graph.gql
  - <domain>-graph-description.json
  - <domain>-estate.pgq.sql   (CREATE PROPERTY GRAPH over the ACTUAL emitted tables)

The estate artefact binds the type-level graph onto the physical golden-record/hub node
tables and link edge tables generated for the domain. The rule is mechanical
(``graph_model.build_estate``): link-backed edges only. Its two offline cross-checks --
table existence (against dbt parse's target/manifest.json) and two-sided key correctness
(against the declared keys) -- live in graph_model and are exercised by test_emit_graph.py.

One reader: the domain sections are still read by emit.load_domains() and declarations
by emit.load_declarations(); the typed graph is built by graph_model.load_graph_inputs(),
    the shared graph loader. This module serialises the already-built representation only.
"""

from __future__ import annotations

import argparse
import csv
import difflib
import io
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Support installed-command and direct-script execution.
# Runs either installed (`ergasterion graph`) or script-mode. In script-mode the running
# module's own repo root is inserted at sys.path[0] ahead of site-packages so
# `import ergasterion.*` binds to THIS tree (see tests/python/test_package_mode.py).
if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion import emit
from ergasterion import graph_model
from ergasterion.estate import EstateContext

# Ambient estate context; functions default to it, a caller threads its own via `ctx=`.
_DEFAULT_CTX = EstateContext.default()

# Estate paths ride the context. Aliases remain for compatible library use.
REPO_ROOT = _DEFAULT_CTX.root
GRAPHS_DIR = _DEFAULT_CTX.graphs_dir

GENERATED_TEXT_HEADER = (
    "Generated by ergasterion/emit_graph.py from declarations/domains SSOT. "
    "Regenerated, never hand-edited. Do not edit by hand."
)

# Header-list-as-SSOT: CSV headers, SQL/PGQ table columns, and GQL property names are
# derived from these two lists.
NODE_HEADERS: list[str] = ["id", "name", "domain", "hash_key", "golden_key"]
EDGE_HEADERS: list[str] = [
    "edge_id",
    "src",
    "dst",
    "rel_type",
    "cardinality",
    "kind",
    "inverse",
    "source_key",
    "target_key",
    "source_column",
    "discriminator_value",
    "link",
    "properties",
]

NODE_TABLE_SUFFIX = "nodes"
EDGE_TABLE_SUFFIX = "edges"
NODE_LABEL = "Entity"
EDGE_LABEL = "Relationship"


@dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


class GraphEmitError(ValueError):
    """Raised when graph serialisation or coverage validation fails."""


def _identifier(value: str) -> str:
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", value).lower()
    if not ident or ident[0].isdigit():
        ident = f"g_{ident}"
    return ident


def node_table(domain: str) -> str:
    return f"{_identifier(domain)}_{NODE_TABLE_SUFFIX}"


def edge_table(domain: str) -> str:
    return f"{_identifier(domain)}_{EDGE_TABLE_SUFFIX}"


def graph_name(domain: str) -> str:
    return f"{_identifier(domain)}_graph"


def estate_graph_name(domain: str) -> str:
    return f"{_identifier(domain)}_estate"


ESTATE_HEADER_LINES = [
    "Property-graph binding over the emitted {domain} estate: a CREATE PROPERTY GRAPH DDL",
    "mapping the physical golden-record / hub node tables and link edge tables generated for",
    "this domain from the declarations/domains SSOT. Regenerated, never hand-edited.",
    "",
    "Scope: this binding realises LINK-BACKED relationships only -- those backed by a physical",
    "link table. Column-level relationships (a relationship carried by a payload column of a",
    "node table) are type-graph knowledge with no physical link table and are not part of this",
    "estate binding.",
    "",
    "Engine support: assumes an engine providing SQL/PGQ-style CREATE PROPERTY GRAPH DDL over",
    "the relational estate. This artefact is a declarative binding map; it is not executed here",
    "and asserts no ISO GQL conformance. Node identity is the Data Vault hash key together with",
    "its business natural key; link foreign keys reference the hash-key component.",
]


def _csv(headers: list[str], rows: list[list[str]]) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(headers)
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def _edge_id(index: int) -> str:
    return f"e{index:05d}"


def node_row(node: graph_model.GraphNode) -> list[str]:
    return [node.entity, node.entity, node.domain, node.hash_key, node.golden_key]


def sorted_edges(graph: graph_model.PropertyGraph) -> list[graph_model.GraphEdge]:
    return sorted(
        graph.edges,
        key=lambda e: (
            e.source,
            e.verb,
            e.target,
            e.kind,
            e.link or "",
            e.source_column or "",
            e.discriminator_value or "",
        ),
    )


def build_edge_rows(graph: graph_model.PropertyGraph) -> list[list[str]]:
    rows: list[list[str]] = []
    for index, edge in enumerate(sorted_edges(graph), start=1):
        verb = graph.verbs[edge.verb]
        rows.append([
            _edge_id(index),
            edge.source,
            edge.target,
            edge.verb,
            verb.cardinality,
            edge.kind,
            edge.inverse,
            edge.source_key or "",
            edge.target_key or "",
            edge.source_column or "",
            edge.discriminator_value or "",
            edge.link or "",
            ";".join(edge.properties),
        ])
    return rows


def serialise_nodes_csv(graph: graph_model.PropertyGraph) -> str:
    rows = [node_row(n) for n in sorted(graph.nodes, key=lambda n: n.entity)]
    return _csv(NODE_HEADERS, rows)


def serialise_edges_csv(graph: graph_model.PropertyGraph) -> str:
    return _csv(EDGE_HEADERS, build_edge_rows(graph))


def _cy_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _cy_props(pairs: list[tuple[str, str]]) -> str:
    return "{" + ", ".join(f"{key}: {_cy_str(value)}" for key, value in pairs) + "}"


def serialise_cypher(graph: graph_model.PropertyGraph) -> str:
    lines = [
        f"// {GENERATED_TEXT_HEADER}",
        "",
        "// Nodes",
    ]
    for node in sorted(graph.nodes, key=lambda n: n.entity):
        lines.append(f"CREATE (:{NODE_LABEL} {_cy_props(list(zip(NODE_HEADERS, node_row(node))))});")

    lines.extend(["", "// Relationships"])
    for row in build_edge_rows(graph):
        record = dict(zip(EDGE_HEADERS, row))
        props = _cy_props([(key, record[key]) for key in EDGE_HEADERS if key not in {"src", "dst", "rel_type"}])
        lines.append(
            f"MATCH (a:{NODE_LABEL} {{id: {_cy_str(record['src'])}}}), "
            f"(b:{NODE_LABEL} {{id: {_cy_str(record['dst'])}}}) "
            f"CREATE (a)-[:{record['rel_type']} {props}]->(b);"
        )
    return "\n".join(lines) + "\n"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def serialise_pgq_sql(graph: graph_model.PropertyGraph) -> str:
    domain = graph.domain
    nt = node_table(domain)
    et = edge_table(domain)
    node_cols = ",\n".join(
        f"  {column} VARCHAR" + (" PRIMARY KEY" if column == "id" else "")
        for column in NODE_HEADERS
    )
    edge_cols = ",\n".join(f"  {column} VARCHAR" for column in EDGE_HEADERS)
    node_props = ", ".join(NODE_HEADERS)
    edge_props = ", ".join(EDGE_HEADERS)
    nodes_csv = f"{domain}-nodes.csv"
    edges_csv = f"{domain}-edges.csv"
    return "\n".join([
        f"-- {GENERATED_TEXT_HEADER}",
        "",
        f"CREATE TABLE {nt} (",
        node_cols,
        ");",
        "",
        f"CREATE TABLE {et} (",
        edge_cols + ",",
        "  PRIMARY KEY (edge_id),",
        f"  FOREIGN KEY (src) REFERENCES {nt} (id),",
        f"  FOREIGN KEY (dst) REFERENCES {nt} (id)",
        ");",
        "",
        f"COPY {nt} ({node_props}) FROM {_sql_str(nodes_csv)} WITH (FORMAT csv, HEADER true);",
        f"COPY {et} ({edge_props}) FROM {_sql_str(edges_csv)} WITH (FORMAT csv, HEADER true);",
        "",
        f"CREATE PROPERTY GRAPH {graph_name(domain)}",
        "  NODE TABLES (",
        f"    {nt}",
        "      KEY (id)",
        f"      LABEL {NODE_LABEL} PROPERTIES ({node_props})",
        "  )",
        "  EDGE TABLES (",
        f"    {et}",
        "      KEY (edge_id)",
        f"      SOURCE KEY (src) REFERENCES {nt} (id)",
        f"      DESTINATION KEY (dst) REFERENCES {nt} (id)",
        f"      LABEL {EDGE_LABEL} PROPERTIES ({edge_props})",
        "  );",
    ]) + "\n"


def serialise_estate_pgq_sql(estate: graph_model.EstateGraph) -> str:
    """Serialise the estate binding to CREATE PROPERTY GRAPH DDL over the emitted tables.

    Link-backed edges only (column-level relationships have no physical table). Each node
    table's KEY clause names the node's declared keys; each edge endpoint's KEY is its own
    declared FK column and REFERENCES the endpoint node table by that node's declared keys.
    The two independent set-equality facts (edge KEY == the link's src_fk; REFERENCES == the
    node's declared keys) are the two sides the offline key-correctness cross-check verifies.
    """
    domain = estate.domain
    by_entity = {n.entity: n for n in estate.node_tables}

    lines = [f"-- {line}".rstrip() for line in
             [ln.format(domain=domain) for ln in ESTATE_HEADER_LINES]]
    lines.append("")
    lines.append(f"CREATE PROPERTY GRAPH {estate_graph_name(domain)}")

    node_blocks = []
    for node in estate.node_tables:
        node_blocks.append(
            f"    {node.table}\n"
            f"      KEY ({', '.join(node.key_columns)})\n"
            f"      LABEL {node.entity}"
        )
    lines.append("  NODE TABLES (")
    lines.append(",\n".join(node_blocks))
    if estate.edge_tables:
        lines.append("  )")
        edge_blocks = []
        for edge in estate.edge_tables:
            src = by_entity[edge.source_entity]
            dst = by_entity[edge.target_entity]
            edge_blocks.append(
                f"    {edge.table}\n"
                f"      KEY ({edge.key_column})\n"
                f"      SOURCE KEY ({edge.source_fk}) "
                f"REFERENCES {src.table} ({', '.join(src.key_columns)})\n"
                f"      DESTINATION KEY ({edge.target_fk}) "
                f"REFERENCES {dst.table} ({', '.join(dst.key_columns)})\n"
                f"      LABEL {edge.verb}"
            )
        lines.append("  EDGE TABLES (")
        lines.append(",\n".join(edge_blocks))
        lines.append("  );")
    else:
        lines.append("  );")
    return "\n".join(lines) + "\n"


def serialise_gql(graph: graph_model.PropertyGraph) -> str:
    node_props = ",\n".join(f"    {column} :: STRING" for column in NODE_HEADERS)
    edge_props = ",\n".join(f"    {column} :: STRING" for column in EDGE_HEADERS)
    verbs = sorted(graph.verbs)
    lines = [
        f"// {GENERATED_TEXT_HEADER}",
        "",
        f"CREATE GRAPH TYPE {graph_name(graph.domain)} AS {{",
        f"  (: {NODE_LABEL} {{",
        node_props,
        "  }),",
        f"  (: {NODE_LABEL})-[: {EDGE_LABEL} {{",
        edge_props,
        f"  }}]->(: {NODE_LABEL}),",
        "",
        "  // Declared relationship types",
    ]
    for index, verb in enumerate(verbs):
        sep = "," if index < len(verbs) - 1 else ""
        lines.append(f"  (: {NODE_LABEL})-[: {verb}]->(: {NODE_LABEL}){sep}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_description(graph: graph_model.PropertyGraph) -> dict[str, Any]:
    relation_types = []
    for verb_name in sorted(graph.verbs):
        verb = graph.verbs[verb_name]
        walks = []
        for edge in graph.edges:
            if edge.verb == verb_name:
                walks.append((edge.source, edge.target))
            if edge.inverse == verb_name:
                walks.append((edge.target, edge.source))
        walks.sort()
        example = walks[0]
        relation_types.append({
            "type": verb_name,
            "alias": verb.alias,
            "direction": verb.direction,
            "kind": verb.kind,
            "cardinality": verb.cardinality,
            "inverse": verb.inverse,
            "source_types": sorted({source for source, _target in walks}),
            "target_types": sorted({target for _source, target in walks}),
            "edge_count": len(walks),
            "example_traversal": {
                "source": example[0],
                "relation": verb_name,
                "target": example[1],
            },
        })
    return {
        "graph": graph_name(graph.domain),
        "node_label": NODE_LABEL,
        "relationship_label": EDGE_LABEL,
        "csv": {"node_headers": NODE_HEADERS, "edge_headers": EDGE_HEADERS},
        "node_types": [
            {
                "id": n.entity,
                "name": n.entity,
                "domain": n.domain,
                "hash_key": n.hash_key,
                "golden_key": n.golden_key,
            }
            for n in sorted(graph.nodes, key=lambda n: n.entity)
        ],
        "relation_types": relation_types,
        "satellites": [
            {"name": s.name, "anchor": s.anchor, "payload_columns": list(s.payload)}
            for s in sorted(graph.satellites, key=lambda s: (s.anchor, s.name))
        ],
    }


def assert_description_coverage(
    description: dict[str, Any],
    graph: graph_model.PropertyGraph,
) -> None:
    node_ids = {n["id"] for n in description.get("node_types", [])}
    expected_nodes = {n.entity for n in graph.nodes}
    if node_ids != expected_nodes:
        raise GraphEmitError(f"node description coverage failed: {sorted(expected_nodes - node_ids)}")

    relation_types = {r["type"]: r for r in description.get("relation_types", [])}
    if set(relation_types) != set(graph.verbs):
        raise GraphEmitError(
            f"relation description coverage failed: {sorted(set(graph.verbs) - set(relation_types))}"
        )
    for verb_name, rel in relation_types.items():
        walks = []
        for edge in graph.edges:
            if edge.verb == verb_name:
                walks.append((edge.source, edge.target))
            if edge.inverse == verb_name:
                walks.append((edge.target, edge.source))
        if not walks:
            raise GraphEmitError(f"relation description coverage failed: {verb_name} has no edge")
        if set(rel.get("source_types", [])) != {source for source, _target in walks}:
            raise GraphEmitError(f"relation source coverage failed: {verb_name}")
        if set(rel.get("target_types", [])) != {target for _source, target in walks}:
            raise GraphEmitError(f"relation target coverage failed: {verb_name}")
        traversal = rel.get("example_traversal") or {}
        if (
            traversal.get("relation") != verb_name
            or (traversal.get("source"), traversal.get("target")) not in set(walks)
        ):
            raise GraphEmitError(f"relation example coverage failed: {verb_name}")

    satellites = {
        (s["name"], s["anchor"], tuple(s.get("payload_columns", [])))
        for s in description.get("satellites", [])
    }
    expected_satellites = {(s.name, s.anchor, tuple(s.payload)) for s in graph.satellites}
    if satellites != expected_satellites:
        raise GraphEmitError(
            f"satellite description coverage failed: {sorted(expected_satellites - satellites)}"
        )


def serialise_description(graph: graph_model.PropertyGraph) -> str:
    description = build_description(graph)
    assert_description_coverage(description, graph)
    return json.dumps(description, indent=2, sort_keys=False) + "\n"


def assert_graph_coverage(graph: graph_model.PropertyGraph) -> None:
    node_ids = {n.entity for n in graph.nodes}
    for edge in graph.edges:
        if edge.source not in node_ids or edge.target not in node_ids:
            raise GraphEmitError(f"edge endpoint coverage failed for {edge.verb}")
    if {e.verb for e in graph.edges} | {e.inverse for e in graph.edges} != set(graph.verbs):
        raise GraphEmitError("edge/verb coverage failed")
    if len(graph.satellites) != len({s.name for s in graph.satellites}):
        raise GraphEmitError("satellite coverage failed: duplicate satellite")


def artefacts_for_graph(graph: graph_model.PropertyGraph) -> dict[str, str]:
    assert_graph_coverage(graph)
    domain = graph.domain
    return {
        f"{domain}-nodes.csv": serialise_nodes_csv(graph),
        f"{domain}-edges.csv": serialise_edges_csv(graph),
        f"{domain}-graph.cypher": serialise_cypher(graph),
        f"{domain}-graph.pgq.sql": serialise_pgq_sql(graph),
        f"{domain}-graph.gql": serialise_gql(graph),
        f"{domain}-graph-description.json": serialise_description(graph),
    }


def generate(ctx: EstateContext | None = None) -> dict[Path, str]:
    ctx = ctx or _DEFAULT_CTX
    graphs_dir = ctx.graphs_dir
    domain_cfg = emit.load_domains(ctx=ctx)
    emit.load_declarations(domain_cfg, ctx=ctx)
    inputs = graph_model.load_graph_inputs_with_config(ctx.domains_dir)
    files: dict[Path, str] = {}
    for domain in sorted(inputs):
        graph, config = inputs[domain]
        for name, content in artefacts_for_graph(graph).items():
            files[graphs_dir / domain / name] = content
        estate = graph_model.build_estate(domain, config, graph)
        files[graphs_dir / domain / f"{domain}-estate.pgq.sql"] = serialise_estate_pgq_sql(estate)
    return files


def write_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[Path]:
    changed: list[Path] = []
    live_dirs = {path.parent for path in files}
    for directory in sorted(live_dirs):
        if not directory.exists():
            continue
        for existing in sorted(directory.iterdir()):
            if existing.is_file() and existing not in files:
                changed.append(existing)
                existing.unlink()
    for path in sorted(files):
        content = files[path]
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return changed


def check_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[str]:
    root = (ctx or _DEFAULT_CTX).root
    problems: list[str] = []
    live_dirs = {path.parent for path in files}
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            problems.append(f"MISSING (never generated on disk): {rel}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != files[path]:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(),
                    files[path].splitlines(),
                    fromfile=f"{rel} (on disk)",
                    tofile=f"{rel} (regenerated)",
                    lineterm="",
                )
            )
            problems.append(f"DRIFT (hand-edited or stale): {rel}\n{diff}")
    for directory in sorted(live_dirs):
        if not directory.exists():
            continue
        for existing in sorted(directory.iterdir()):
            if existing.is_file() and existing not in files:
                problems.append(
                    f"ORPHAN (on disk, no longer generated): {existing.relative_to(root).as_posix()}"
                )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate + fail if generated graph artefacts drifted or were hand-edited.",
    )
    parser.add_argument(
        "--estate-root", type=Path, default=None,
        help="Estate root to emit graph artefacts against (resolved from the environment or working directory when omitted).",
    )
    args = parser.parse_args()

    ctx = EstateContext.resolve(estate_root=args.estate_root)
    try:
        files = generate(ctx)
    except (graph_model.GraphModelError, GraphEmitError, ValueError) as exc:
        print(f"property-graph projection gate FAIL: {exc}")
        return 1

    if args.check:
        problems = check_files(files, ctx=ctx)
        if problems:
            print(f"property-graph projection gate FAIL: {len(problems)} on-disk divergence(s):")
            for problem in problems:
                print(problem)
            return 1
        print(f"property-graph projection gate OK: {len(files)} artefact(s) byte-match the generated set")
        return 0

    changed = write_files(files, ctx=ctx)
    print(f"generated/updated {len([p for p in changed if p in files])} of {len(files)} graph artefact(s)")
    for path in sorted(changed):
        marker = "wrote" if path in files else "pruned"
        print(f"  {marker} {path.relative_to(ctx.root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
