"""Emit one deterministic Bitol ODPS v1 data-product descriptor per domain.

The Open Data Product Standard descriptor links each output port to a generated ODCS
contract. A source becomes an input port only when its declaration records an imported
ODCS contract id and version; unknown contracts are never invented. Management ports,
support details, and ownership come from declared repository configuration.

Outputs:
  - contracts/odps/<domain>.odps.yml   one ODPS (Bitol) v1.0.0 descriptor per domain,
                                        regenerated-never-hand-edited, sibling to
                                        contracts/<domain>/*.odcs.yml.

Descriptor ids are `dpf:odps:<domain>` -- no timestamps, UUIDs, or environment-derived
facts. The same manifest, declarations, and
domains config regenerates byte-identical output. Every emitted descriptor is validated
in-process against the vendored ODPS v1.0.0 JSON Schema
(schemas/odps-json-schema-v1.0.0.json) without network access.

Usage:
    python ergasterion/emit_odps.py            # write + validate every descriptor
    python ergasterion/emit_odps.py --check     # validate + fail if on-disk drifted / hand-edited
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft201909Validator

# Support installed-command and direct-script execution.
if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion import emit
from ergasterion import emit_contracts
from ergasterion.estate import EstateContext

# Ambient estate context; functions default to it, a caller threads its own via `ctx=`.
_DEFAULT_CTX = EstateContext.default()

# ESTATE paths -- ride the context. Aliases kept for back-compat reads.
REPO_ROOT = _DEFAULT_CTX.root
CONTRACTS_DIR = _DEFAULT_CTX.contracts_dir
ODPS_DIR = CONTRACTS_DIR / "odps"
DECLARATIONS_DIR = _DEFAULT_CTX.declarations_dir
LICENSE_PATH = _DEFAULT_CTX.license_path
# ENGINE DATA (the vendored ODPS JSON Schema) resolves package-relative -- shipped as
# package data inside ergasterion/, never estate-anchored (two-class principle).
SCHEMA_PATH = Path(__file__).resolve().parent / "schemas" / "odps-json-schema-v1.0.0.json"


def _odps_dir(ctx: EstateContext) -> Path:
    return ctx.contracts_dir / "odps"

API_VERSION = "v1.0.0"
KIND = "DataProduct"
GENERATED_HEADER = (
    "# Generated by ergasterion/emit_odps.py from the ODCS export set (emit_contracts.py) +\n"
    "# declarations/domains SSOT. ODPS (Bitol) v1.0.0 data-product descriptor -- Open Data\n"
    "# Product STANDARD (github.com/bitol-io), unrelated to opendataproducts.org's Open Data\n"
    "# Product Specification. Regenerated, never hand-edited. Do not edit by hand.\n"
)

# Stable public source and support endpoint for generated descriptors.
REPO_URL = "https://github.com/antikas/ergasterion"

# Streamlit-in-Snowflake review console (RUNBOOK.md section 9: `snow streamlit deploy`,
# object identifier ERGASTERION.PUBLIC.DPF_REVIEW_QUEUE) and dbt docs (standard `dbt docs
# generate && dbt docs serve` local default port). Both are factory-wide surfaces -- one
# review queue, one docs site, covering every domain -- so every domain's descriptor lists
# the same two management ports; static, not a live endpoint probe.
MANAGEMENT_PORTS: list[dict[str, Any]] = [
    {
        "name": "review-console",
        "content": "control",
        "type": "rest",
        "url": "https://app.snowflake.com/<org>/<account>/#/streamlit-apps/ERGASTERION.PUBLIC.DPF_REVIEW_QUEUE",
        "description": (
            "Streamlit-in-Snowflake entity-resolution review queue -- approve or reject "
            "uncertain candidate matches (tier-2 composite score 0.65-0.85). Deploy per "
            "RUNBOOK.md section 9; <org>/<account> are your own Snowflake identifiers."
        ),
    },
    {
        "name": "dbt-docs",
        "content": "discoverability",
        "type": "rest",
        "url": "http://localhost:8080",
        "description": (
            "dbt docs site (models, columns, lineage, tests) -- generate with "
            "`dbt docs generate` then serve with `dbt docs serve` (dbt's own local default "
            "port)."
        ),
    },
]

SUPPORT_CHANNELS: list[dict[str, Any]] = [
    {
        "channel": "GitHub Issues",
        "url": f"{REPO_URL}/issues",
        "description": "Repository issue tracker for questions, bugs, and source-onboarding requests.",
        "tool": "other",
        "scope": "issues",
    },
]

# The import seeder (ergasterion/import_odcs.py:build_context) writes exactly this two-line
# header onto a declaration file it seeds from an ODCS contract: a free-text "Seeded by"
# line, then id/version/domain in Python repr() form. This regex reads the second line
# back; see module docstring for why this is the sole "does this source have an
# imported/derived contract" signal today.
_SEEDED_HEADER_RE = re.compile(
    r"^#\s+id=(?P<id>'[^']*'|\"[^\"]*\")\s+version=(?P<version>'[^']*'|\"[^\"]*\")\s+domain=",
    re.MULTILINE,
)

# The holder is the text after the year, stopping before any trailing rights clause --
# both licence line shapes parse to the same holder ("Copyright (c) 2026 Jane Doe" and
# "Copyright (c) 2026 Jane Doe. All rights reserved." both yield "Jane Doe"), so the
# emitted team attribution is stable across a licence change.
_LICENSE_COPYRIGHT_RE = re.compile(
    r"Copyright \(c\) \d{4} (?P<holder>.+?)(?:\.\s*All rights reserved\.?)?\s*$",
    re.MULTILINE,
)


def _unrepr(token: str) -> str:
    """Strip one layer of Python repr() quoting -- the seeder's own well-known convention
    (see ergasterion/import_odcs.py:build_context); ast.literal_eval would also work but this
    keeps the dependency list unchanged for one fixed quoting shape."""
    if len(token) >= 2 and token[0] == token[-1] and token[0] in "'\"":
        return token[1:-1]
    return token


def load_schema_validator() -> Draft201909Validator:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return Draft201909Validator(schema)


def domain_entities(odcs: dict[str, Any]) -> set[str]:
    """The set of entities this domain's served products bind to -- the domain's own
    entity footprint, read straight off its odcs.products map (no re-derivation of
    domain-to-entity ownership; emit_contracts.py already owns that mapping)."""
    return {product["entity"] for product in odcs["products"].values() if product and product.get("entity")}


def feeding_declarations(entities: set[str], declarations: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Declared-source declarations that feed at least one of `entities`, ordered by
    source priority asc then name -- generalises
    emit_contracts.source_priority_for_entity's ordering across a whole domain's entity
    set instead of one entity."""
    feeders = [
        decl
        for decl in declarations
        if any(
            vault.get("enabled", True) and vault.get("entity") in entities
            for table in decl.get("tables", {}).values()
            for vault in table.get("vault_entities", [])
        )
    ]
    feeders.sort(key=lambda d: (d["source"].get("priority", 100), d["source"]["name"]))
    return feeders


def imported_contract_ref(
    decl: dict[str, Any], *, ctx: EstateContext | None = None
) -> dict[str, str] | None:
    """If `decl`'s declaration file carries the import seeder's header, return the
    {id, version} of the ODCS contract it was seeded from. None for a hand-authored
    declaration that names no source contract -- the honest, common case today."""
    path = (ctx or _DEFAULT_CTX).declarations_dir / decl["source"]["declaration_file"]
    text = path.read_text(encoding="utf-8")
    match = _SEEDED_HEADER_RE.search(text)
    if not match:
        return None
    return {"id": _unrepr(match.group("id")), "version": _unrepr(match.group("version"))}


def build_input_ports(
    entities: set[str], declarations: list[dict[str, Any]], *, ctx: EstateContext | None = None
) -> list[dict[str, Any]]:
    ports: list[dict[str, Any]] = []
    for decl in feeding_declarations(entities, declarations):
        ref = imported_contract_ref(decl, ctx=ctx)
        if ref is None:
            continue
        ports.append({"name": decl["source"]["name"], "version": ref["version"], "contractId": ref["id"]})
    return ports


def build_output_ports(
    domain_name: str,
    odcs: dict[str, Any],
    contract_docs: dict[Path, dict[str, Any]],
    *,
    ctx: EstateContext | None = None,
) -> list[dict[str, Any]]:
    """One output port per served product, contractId+version read straight off the
    freshly generated ODCS contract (never re-derived) -- so an output port can only ever
    point at a contract emit_contracts.py actually produced this run."""
    ctx = ctx or _DEFAULT_CTX
    ports: list[dict[str, Any]] = []
    for table in odcs["products"]:
        path = ctx.contracts_dir / domain_name / f"{table}.odcs.yml"
        doc = contract_docs.get(path)
        if doc is None:
            raise ValueError(
                f"output port {table!r} in domain {domain_name!r} has no emitted ODCS "
                f"contract at {path.relative_to(ctx.root).as_posix()} -- "
                f"emit_contracts.py's own completeness gate should make this unreachable; "
                f"if it fired, the two emitters have drifted out of sync."
            )
        ports.append({
            "name": table,
            "description": f"Served {table} table.",
            "type": "tables",
            "version": doc["version"],
            "contractId": doc["id"],
        })
    return ports


def team_from_license(ctx: EstateContext | None = None) -> dict[str, Any]:
    license_path = (ctx or _DEFAULT_CTX).license_path
    text = license_path.read_text(encoding="utf-8")
    match = _LICENSE_COPYRIGHT_RE.search(text)
    if not match:
        raise ValueError(f"{license_path}: no 'Copyright (c) <year> <holder>' line found -- team metadata source missing")
    holder = match.group("holder").strip()
    return {
        "name": "Ergasterion maintainers",
        "description": "Maintainer team, per this repository's LICENSE.",
        "members": [{"username": holder, "name": holder, "role": "maintainer"}],
    }


def build_descriptor(
    odcs: dict[str, Any],
    entities: set[str],
    declarations: list[dict[str, Any]],
    contract_docs: dict[Path, dict[str, Any]],
    *,
    ctx: EstateContext | None = None,
) -> dict[str, Any]:
    """Build one ODPS (Bitol) v1.0.0 descriptor document (an ordered dict) for a domain."""
    domain_name = odcs["domain"]

    descriptor: dict[str, Any] = {
        "apiVersion": API_VERSION,
        "kind": KIND,
        "id": f"dpf:odps:{domain_name}",
        "name": f"{domain_name} data product",
        "version": str(odcs.get("contract_version", "1.0.0")),
        "status": odcs.get("status", "active"),
        "domain": domain_name,
    }
    descriptor["description"] = {
        "purpose": (
            f"Entity-resolved, survivorship-governed marts and canonical tables for the "
            f"{domain_name} domain, generated by the Ergasterion factory from its declared "
            f"sources."
        ),
    }

    auth = odcs.get("authoritative_definitions")
    if auth:
        descriptor["authoritativeDefinitions"] = [
            {"url": item["url"], "type": item.get("type", "businessDefinition")} for item in auth
        ]

    input_ports = build_input_ports(entities, declarations, ctx=ctx)
    if input_ports:
        descriptor["inputPorts"] = input_ports
    descriptor["outputPorts"] = build_output_ports(domain_name, odcs, contract_docs, ctx=ctx)
    descriptor["managementPorts"] = MANAGEMENT_PORTS
    descriptor["support"] = SUPPORT_CHANNELS
    descriptor["team"] = team_from_license(ctx)

    return descriptor


def dump_yaml(descriptor: dict[str, Any]) -> str:
    body = yaml.safe_dump(
        descriptor,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=100,
    )
    return GENERATED_HEADER + body


def generate(ctx: EstateContext | None = None) -> dict[Path, str]:
    """Build the full {path: yaml_text} set of descriptors. Runs emit_contracts.generate()
    first (its own completeness gate + schema validation happen there, loud-fail included);
    this function only wraps that already-validated output set."""
    ctx = ctx or _DEFAULT_CTX
    odps_dir = _odps_dir(ctx)
    contract_files = emit_contracts.generate(ctx)
    contract_docs = {path: yaml.safe_load(text) for path, text in contract_files.items()}

    domain_odcs = emit_contracts.load_domain_odcs(ctx=ctx)
    domain_cfg = emit.load_domains(ctx=ctx)
    declarations = emit.load_declarations(domain_cfg, ctx=ctx)

    files: dict[Path, str] = {}
    for odcs in domain_odcs.values():
        entities = domain_entities(odcs)
        descriptor = build_descriptor(odcs, entities, declarations, contract_docs, ctx=ctx)
        path = odps_dir / f"{odcs['domain']}.odps.yml"
        files[path] = dump_yaml(descriptor)
    return files


def validate_all(
    files: dict[Path, str], validator: Draft201909Validator, *, ctx: EstateContext | None = None
) -> list[str]:
    root = (ctx or _DEFAULT_CTX).root
    errors: list[str] = []
    for path in sorted(files):
        doc = yaml.safe_load(files[path])
        schema_errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.absolute_path))
        for err in schema_errors:
            location = "/".join(str(p) for p in err.absolute_path) or "<root>"
            errors.append(f"{path.relative_to(root).as_posix()}: {location}: {err.message}")
    return errors


def write_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[Path]:
    odps_dir = _odps_dir(ctx or _DEFAULT_CTX)
    changed: list[Path] = []
    live = set(files)
    if odps_dir.exists():
        for existing in odps_dir.glob("*.odps.yml"):
            if existing not in live:
                changed.append(existing)
                existing.unlink()
    for path in sorted(files):
        content = files[path]
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
    return changed


def check_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[str]:
    ctx = ctx or _DEFAULT_CTX
    odps_dir = _odps_dir(ctx)
    root = ctx.root
    problems: list[str] = []
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            problems.append(f"MISSING (never generated on disk): {rel}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != files[path]:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(), files[path].splitlines(),
                    fromfile=f"{rel} (on disk)", tofile=f"{rel} (regenerated)", lineterm="",
                )
            )
            problems.append(f"DRIFT (hand-edited or stale): {rel}\n{diff}")
    if odps_dir.exists():
        live = set(files)
        for existing in sorted(odps_dir.glob("*.odps.yml")):
            if existing not in live:
                problems.append(
                    f"ORPHAN (on disk, no longer generated): {existing.relative_to(root).as_posix()}"
                )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Validate + fail if any on-disk descriptor drifted / was hand-edited (no writes).",
    )
    parser.add_argument(
        "--estate-root", type=Path, default=None,
        help="Estate root to emit descriptors against (resolved from the environment or working directory when omitted).",
    )
    args = parser.parse_args()

    ctx = EstateContext.resolve(estate_root=args.estate_root)
    validator = load_schema_validator()
    files = generate(ctx)

    schema_errors = validate_all(files, validator, ctx=ctx)
    if schema_errors:
        print(f"ODPS (Bitol) schema-validation FAIL: {len(schema_errors)} error(s) against {SCHEMA_PATH.name}:")
        for err in schema_errors:
            print(f"  {err}")
        return 1
    print(f"ODPS (Bitol) schema-validation OK: {len(files)} descriptor(s) valid against {SCHEMA_PATH.name}")

    if args.check:
        problems = check_files(files, ctx=ctx)
        if problems:
            print(f"ODPS (Bitol) descriptor gate FAIL: {len(problems)} on-disk divergence(s):")
            for problem in problems:
                print(problem)
            return 1
        print(f"ODPS (Bitol) descriptor gate OK: {len(files)} on-disk descriptor(s) byte-match the generated set")
        return 0

    changed = write_files(files, ctx=ctx)
    print(f"generated/updated {len([p for p in changed if p in files])} of {len(files)} descriptor(s)")
    for path in sorted(changed):
        marker = "wrote" if path in files else "pruned"
        print(f"  {marker} {path.relative_to(ctx.root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
