"""Deterministic dbt model emitter for source-declaration-driven onboarding.

Inputs:
  - declarations/*.yml
  - ergasterion/templates/*.j2
  - optional OpenIM model markdown files for declaration mapping validation

Outputs:
  - source-specific staging, ER bridge, AutomateDV stage, and satellite models
  - source fan-in models for hubs, links, business-vault survivorship, and ER

No LLM or runtime inference is used in the generation path.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import pprint
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

# Support installed-command and direct-script execution.
if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion.estate import EstateContext
from ergasterion.dialect_lint import DENY_LISTS, lint_models, _is_generated
from ergasterion.source_delivery import (
    canonical_contract_document,
    load_typed_declarations,
)
from ergasterion.structure_gate import (
    check_structure,
    load_structure_declarations,
    normalise_landing,
)
from ergasterion.translators.dbt import (
    annotate_production_tables,
    attach_source_physical_coords,
    bind_production_sources,
    bronze_plan_digest,
    bronze_product_dir,
    check_casefold_identities,
    load_runtime_bindings,
    production_projection_groups,
    reject_draft_generation,
)

# The ambient estate context is resolved from the working directory or environment. Functions default to it;
# a caller wanting a different estate constructs its own via EstateContext.resolve(...) and
# threads it through `ctx=`. Module path aliases below are read-only conveniences over it for
# external readers/tests that operate on the committed tree -- generation reads `ctx.*`.
_DEFAULT_CTX = EstateContext.default()

# Estate paths ride the context. Aliases remain for compatible library use.
REPO_ROOT = _DEFAULT_CTX.root
DECLARATIONS_DIR = _DEFAULT_CTX.declarations_dir
MODELS_DIR = _DEFAULT_CTX.models_dir
DOMAINS_DIR = _DEFAULT_CTX.domains_dir

# Templates are package-relative data, so an installed wheel can target any estate.
TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"

SQL_HEADER = "-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand."
YAML_HEADER = "# Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand."

# The domain-model-config sections merged from every domains/*.yml at emit time.
DOMAIN_SECTIONS = (
    "entity_configs",
    "hashdiff_exclude",
    "hub_configs",
    "link_configs",
    "bv_configs",
    "res_configs",
)

# Declared values that land in SQL identifier or ref() positions must be plain
# identifiers. Anything else -- quotes, braces, spaces, path separators -- would
# render into the emitted file as live template text or broken SQL, so the gate
# rejects it at declaration load with the file and field named.
IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _require_identifier(value: Any, where: str) -> None:
    if not isinstance(value, str) or not IDENTIFIER_RE.match(value):
        raise ValueError(
            f"{where}: {value!r} must be a plain identifier "
            f"(letters, digits, underscores, starting with a letter or underscore) -- "
            f"it renders into a SQL identifier or ref() position"
        )


def _derive_hashdiff_columns(
    entity_configs: dict[str, dict[str, Any]],
    exclusions: dict[str, set[str]],
) -> None:
    """Populate each entity's hashdiff column list in place: payload minus its
    declared exclusion set. The hashdiff column list is derived from the payload
    SSOT rather than hand-listed in the domain config, so it can never silently
    diverge from the payload by a stray edit. A domain declares only the
    per-entity exclusion set (hashdiff_exclude); the default (empty set) makes the
    hashdiff every payload column.
    """
    for entity_name, config in entity_configs.items():
        payload = config["payload"]
        exclude = exclusions.get(entity_name, set())
        unknown = exclude - set(payload)
        if unknown:
            raise ValueError(
                f"hashdiff_exclude[{entity_name!r}] names column(s) not in its payload: "
                f"{', '.join(sorted(unknown))}"
            )
        hashdiff_key = config["hashdiff"]
        config["hashed_columns"][hashdiff_key]["columns"] = [
            column for column in payload if column not in exclude
        ]


def load_domains(domains_dir: Path | None = None, *, ctx: EstateContext | None = None) -> dict[str, Any]:
    """Load and merge every per-domain model config in ``domains_dir``.

    Each domains/*.yml carries the closed vocabulary for one example domain
    (entity_configs / hashdiff_exclude / hub_configs / link_configs / bv_configs /
    res_configs). The engine itself holds no domain nouns: this loader is the single
    seam through which a domain's entities reach the templates. All domain files are
    merged into one config; two domains must not share a key in any section (a
    collision fails loudly rather than silently shadowing one behind the other). A
    second domain is therefore onboarded by DATA alone -- drop a sibling
    domains/<name>.yml plus its declarations, with zero change to this module (the
    fixture-domain test in tests/python/test_emit.py pins that guarantee).

    hashdiff_exclude values are declared as lists and used as sets; each entity's
    hashdiff column list is DERIVED here (payload minus its exclusion set), never
    hand-listed in the domain file.

    Caveat for any model-schema file a declaration references via canonical_mappings
    (the optional --openim-root hook): parse_model_attribute_schema binds only the
    FIRST '## Attribute schema' table per file -- keep exactly one such table per file.
    """
    if domains_dir is None:
        domains_dir = (ctx or _DEFAULT_CTX).domains_dir
    merged: dict[str, dict[str, Any]] = {section: {} for section in DOMAIN_SECTIONS}
    files = sorted(domains_dir.glob("*.yml"))
    if not files:
        raise ValueError(f"No domain model config found in {domains_dir}")
    for path in files:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{path}: expected a YAML mapping")
        for section in DOMAIN_SECTIONS:
            block = data.get(section, {}) or {}
            if not isinstance(block, dict):
                raise ValueError(f"{path}:{section}: expected a mapping")
            for key, value in block.items():
                if key in merged[section]:
                    raise ValueError(
                        f"{path}: {section} key {key!r} collides with an already-loaded "
                        f"domain; domains must not share {section} keys"
                    )
                merged[section][key] = value
    merged["hashdiff_exclude"] = {
        entity: set(columns) for entity, columns in merged["hashdiff_exclude"].items()
    }
    _derive_hashdiff_columns(merged["entity_configs"], merged["hashdiff_exclude"])
    return merged


def validate_bv_rules_subset_of_payload(
    bv_configs: dict[str, dict[str, Any]],
    entity_configs: dict[str, dict[str, Any]],
) -> None:
    """Emit-time gate: BV_CONFIGS[entity]['rules'] keys must be a subset of that
    entity's payload columns. 'rules' is a third independent enumeration of the
    entity's column set (alongside payload and hashdiff) -- this keeps it
    honest against the payload SSOT instead of silently drifting. Fails
    loudly, naming both the entity and the offending keys.

    Parameterised (rather than reading the module globals directly) so the
    failure path is directly testable with an injected, deliberately-broken
    bv_configs/entity_configs pair.
    """
    for entity_name, bv in bv_configs.items():
        if entity_name not in entity_configs:
            raise ValueError(f"BV_CONFIGS names unknown entity {entity_name!r}")
        payload_columns = set(entity_configs[entity_name]["payload"])
        offending = sorted(set(bv["rules"]) - payload_columns)
        if offending:
            raise ValueError(
                f"BV_CONFIGS[{entity_name!r}]['rules'] keys not in {entity_name!r} payload: "
                f"{', '.join(offending)}"
            )


def validate_domain_paths(domain: dict[str, Any]) -> None:
    """Emit-time gate: every declared model path stays inside the estate's models/
    tree. A path that is absolute, carries a ``..`` segment, or sits outside
    ``models/`` would land a generated file where the project's layer config no
    longer governs its materialisation (dbt's default of view applies there), or
    outside the estate entirely. The path stem is the emitted relation's
    identifier and follows the identifier shape."""
    for section in ("hub_configs", "link_configs", "bv_configs", "res_configs"):
        for name, config in domain.get(section, {}).items():
            declared = config.get("path")
            where = f"{section}.{name}.path"
            if not isinstance(declared, str) or not declared:
                raise ValueError(f"{where}: a declared model path is required")
            posix = declared.replace("\\", "/")
            parts = posix.split("/")
            if posix.startswith("/") or (len(parts[0]) == 2 and parts[0][1] == ":"):
                raise ValueError(f"{where}: {declared!r} must be estate-relative")
            if ".." in parts:
                raise ValueError(f"{where}: {declared!r} must not carry a '..' segment")
            if parts[0] != "models":
                raise ValueError(
                    f"{where}: {declared!r} must sit under models/ so the layer's "
                    f"materialisation config governs it"
                )
            _require_identifier(Path(posix).stem, where)


def validate_res_configs(
    res_configs: dict[str, Any], *, ctx: EstateContext | None = None
) -> None:
    """Emit-time gate: entity-resolution config values that shape the emitted
    statement are validated before render. ``merge_iterations`` unrolls one pair
    of CTEs per round, so a non-integer, zero, or negative value renders broken
    or silently degraded SQL that dialect lint and a parse both accept. A
    declared ``convergence_test`` names the estate test that proves the round
    count suffices, so a dangling name fails here rather than proving nothing."""
    ctx = ctx or _DEFAULT_CTX
    for entity, res in res_configs.items():
        if res.get("transitive_merge"):
            iterations = res.get("merge_iterations")
            if not isinstance(iterations, int) or isinstance(iterations, bool) or iterations < 1:
                raise ValueError(
                    f"res_configs.{entity}: transitive_merge requires merge_iterations "
                    f"to be an integer of at least 1, got {iterations!r}"
                )
        convergence_test = res.get("convergence_test")
        if convergence_test is not None:
            test_path = ctx.root / str(convergence_test)
            if not test_path.is_file():
                raise ValueError(
                    f"res_configs.{entity}: convergence_test {convergence_test!r} "
                    f"does not exist under the estate root"
                )


def validate_unique_source_priorities(declarations: list[dict[str, Any]]) -> None:
    """Emit-time gate: enabled sources feeding an entity must have unique priorities.

    Survivorship consumes the ordered vault list emitted by ``select_vaults``. A
    shared priority would leave source name as an undeclared tiebreaker, allowing a
    source rename to change both the winning value and its published provenance.
    """
    sources_by_entity_priority: dict[tuple[str, int], set[str]] = {}
    for vault in select_vaults(declarations):
        key = (vault["entity"], vault["source_order"])
        sources_by_entity_priority.setdefault(key, set()).add(vault["source"]["name"])

    for (entity_name, priority), source_names in sorted(sources_by_entity_priority.items()):
        if len(source_names) > 1:
            names = ", ".join(sorted(source_names))
            raise ValueError(
                f"{entity_name}: sources {names} share priority {priority} - "
                "survivorship order must be a total order; give each source feeding "
                "this entity a distinct priority"
            )


def validate_er_branch_coverage(
    declarations: list[dict[str, Any]],
    res_configs: dict[str, dict[str, Any]] | None = None,
    *,
    ctx: EstateContext | None = None,
) -> None:
    """Emit-time gate: every res_<X> model a source's bridges consume must be fed by
    an entity_resolution.<X> branch on that same source.

    A vaulted entity's bridge inner-joins res_<X> and filters `where golden_<X>_key
    is not null`. res_<X> is fanned in from the entity_resolution.<X> branches across
    all sources (see the RES loop in generate_files). If a source omits its own
    entity_resolution.<X> branch, it contributes zero records to res_<X>, resolves to
    a null golden_<X>_key, and the bridge inner-join silently drops EVERY record of
    that source downstream -- clean emit, green build, no rows. The loud-fail thesis
    forbids exactly that silent mis-emit, so this fails at emit time instead.

    The gate is keyed off the bridge's resolution MODEL (res_<X> -> <X>), not the
    vault-entity name. A rider entity (a satellite-only entity that inner-joins a
    parent's res_<X> with no entity_resolution key of its own) rides the parent's
    branch. Keying off the resolution target means those riders are satisfied by the
    source's entity_resolution.<X> branch and never false-positive. One error per
    (source, target) pair, not per entity, so several entities sharing one res model
    raise at most one error.

    A symmetric soft warning (stderr, non-fatal) fires for an entity_resolution.<X>
    branch on a source no bridge resolves against -- a branch feeding nothing.

    Branch COLUMN shape is not checked here: res_entity.sql.j2 dereferences
    branch.columns[column.name] per res column, so a branch missing an expected
    column already fails loudly (jinja2.exceptions.UndefinedError under the emitter's
    StrictUndefined Jinja environment) at render time. Duplicating it would
    break SSOT (see caveats).

    Parameterised on res_configs (rather than reading the global directly) so the
    failure path is directly testable with an injected config pair.
    """
    if res_configs is None:
        res_configs = load_domains(ctx=ctx)["res_configs"]
    res_model_to_target = {
        Path(res["path"]).stem: target for target, res in res_configs.items()
    }
    for declaration in declarations:
        source_name = declaration["source"]["name"]
        declared_branches = set(declaration.get("entity_resolution", {}))
        required: dict[str, set[str]] = {}
        for table in declaration.get("tables", {}).values():
            for vault in table.get("vault_entities", []):
                if not vault.get("enabled", True):
                    continue
                for resolution in vault.get("bridge", {}).get("resolutions", []):
                    target = res_model_to_target.get(resolution.get("model"))
                    if target is None:
                        continue
                    required.setdefault(target, set()).add(vault.get("name", vault["entity"]))
        for target in sorted(required):
            if target not in declared_branches:
                entities = ", ".join(sorted(required[target]))
                raise ValueError(
                    f"{source_name}: bridge(s) [{entities}] resolve against res_{target} "
                    f"but the source declares no entity_resolution.{target} branch; it would "
                    f"contribute no records to res_{target}, resolve to a null golden_{target}_key, "
                    f"and silently drop every row at the bridge inner-join. "
                    f"Add an entity_resolution.{target} branch to {source_name}."
                )
        for target in sorted(declared_branches - set(required)):
            print(
                f"WARN {source_name}: declares entity_resolution.{target} but no enabled bridge "
                f"resolves against res_{target}; the branch feeds no bridge.",
                file=sys.stderr,
            )


@dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


def py_literal(value: Any) -> str:
    return pprint.pformat(value, width=88, sort_dicts=False)


def dbt_set(name: str, value: Any) -> str:
    return f"{{%- set {name} = {py_literal(value)} -%}}"


def normalise_sql_newlines(text: str) -> str:
    lines = [line.rstrip() for line in text.strip().splitlines()]
    return "\n".join(lines) + "\n"


def template_env() -> Environment:
    # StrictUndefined (not the default Undefined): a missing context key or dict
    # entry must fail loudly at render time, not silently render as ''. Verified
    # gap: res_entity.sql.j2's branch.columns[column.name] with an absent
    # branch column used to emit '  as source_system,' instead of raising. Every
    # template's genuinely optional dereference is guarded explicitly (default()
    # filter or an if-guard on a setdefault'd key) rather than riding this loophole --
    # see res_entity.sql.j2's res.transitive_merge and bridge.sql.j2's
    # vault.bridge.where.
    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        trim_blocks=False,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.globals["dbt_set"] = dbt_set
    return env


def parse_model_attribute_schema(model_path: Path) -> dict[str, str]:
    text = model_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.match(r"^##\s+Attribute schema\b", line.strip()):
            start = i + 1
            break
    if start is None:
        raise ValueError(f"{model_path}: no Attribute schema section found")

    columns: dict[str, str] = {}
    seen_header = False
    for line in lines[start:]:
        stripped = line.strip()
        if stripped.startswith("## "):
            break
        if not stripped.startswith("|"):
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if len(cells) < 2:
            continue
        if not seen_header:
            if cells[0].lower() == "column":
                seen_header = True
            continue
        if set(cells[0]) <= {"-", ":", " "}:
            continue
        column = cells[0].strip("`").strip()
        type_keyword = cells[1].strip("`").split("(", 1)[0].strip().lower()
        columns[column] = type_keyword
    if not columns:
        raise ValueError(f"{model_path}: Attribute schema table parsed to zero columns")
    return columns


def load_declarations(
    domain: dict[str, Any] | None = None, *, ctx: EstateContext | None = None
) -> list[dict[str, Any]]:
    ctx = ctx or _DEFAULT_CTX
    if domain is None:
        domain = load_domains(ctx=ctx)
    declarations_dir = ctx.declarations_dir
    entity_configs = domain["entity_configs"]
    declarations: list[dict[str, Any]] = []
    for path in sorted(declarations_dir.glob("*.yml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{path}: expected a YAML mapping")
        source = data["source"]
        source.setdefault("display_name", source["name"].upper())
        source.setdefault("priority", 100)
        source["declaration_file"] = path.name
        _require_identifier(source["name"], f"{path}:source.name")
        _require_identifier(source["display_name"], f"{path}:source.display_name")
        for branch_entity, branch in data.get("entity_resolution", {}).items():
            if isinstance(branch, dict) and "model" in branch:
                _require_identifier(
                    branch["model"], f"{path}:entity_resolution.{branch_entity}.model"
                )
        for table_name, table in data.get("tables", {}).items():
            table["name"] = table_name
            table.setdefault("staging_model", f"stg_{source['name']}_{table_name}")
            table.setdefault("description", "")
            table.setdefault("seed_tests", [])
            table.setdefault("model_tests", [])
            table.setdefault("vault_entities", [])
            _require_identifier(table_name, f"{path}:tables.{table_name}")
            landing = normalise_landing(table, f"{path}:{table_name}")
            kind = landing["kind"]
            if kind == "source":
                for field in ("source_name", "identifier"):
                    _require_identifier(
                        landing[field], f"{path}:{table_name}.landing.{field}"
                    )
            if "raw_model" in table:
                _require_identifier(table["raw_model"], f"{path}:{table_name}.raw_model")
            _require_identifier(table["staging_model"], f"{path}:{table_name}.staging_model")
            for column in table.get("projection", []):
                if "name" not in column:
                    raise ValueError(f"{path}:{table_name}: projection columns need name/expression")
                if "expression" not in column:
                    # A Bronze Product Contract's typed projection column names the physical
                    # column it publishes as `source` and applies no transform, so this loader
                    # projects it onto the legacy `expression` every template already reads.
                    # One authored list therefore serves both consumers: the typed compiler
                    # (ergasterion.source_delivery) reads source/logical_type/nullable and this
                    # loader reads name/expression. A column declaring neither `expression` nor
                    # `source` still fails with the message it has always failed with.
                    source_column = column.get("source")
                    if source_column is None:
                        raise ValueError(
                            f"{path}:{table_name}: projection columns need name/expression"
                        )
                    _require_identifier(
                        source_column, f"{path}:{table_name}.projection.source"
                    )
                    column["expression"] = source_column
                _require_identifier(column["name"], f"{path}:{table_name}.projection")
            for vault in table["vault_entities"]:
                entity_name = vault["entity"]
                if entity_name not in entity_configs:
                    raise ValueError(f"{path}:{table_name}: unknown vault entity {entity_name!r}")
                vault_name = vault.setdefault("name", entity_name)
                vault.setdefault("source_model", table["staging_model"])
                vault.setdefault("bridge_model", f"br_dv_{source['name']}_{vault_name}")
                vault.setdefault("stage_model", f"stg_dv_{source['name']}_{vault_name}")
                vault.setdefault("record_source", f"!{source['display_name']}_{vault_name.upper()}")
                sat_base = entity_configs[entity_name]["satellite_base"]
                vault.setdefault("satellite_model", f"sat_{sat_base}_{source['name']}")
                vault.setdefault("enabled", True)
                for field in ("name", "source_model", "bridge_model", "stage_model", "satellite_model"):
                    _require_identifier(
                        vault[field], f"{path}:{table_name}:{vault_name}.{field}"
                    )
                if vault["enabled"] and "bridge" not in vault:
                    raise ValueError(f"{path}:{table_name}:{vault_name}: enabled vault needs bridge")
                if vault["enabled"]:
                    entity_config = entity_configs[entity_name]
                    hashdiff_columns = entity_config["hashed_columns"][entity_config["hashdiff"]]["columns"]
                    required_columns = set(entity_config["payload"]) | set(hashdiff_columns)
                    selected_columns = {column["name"] for column in vault["bridge"]["select"]}
                    missing_columns = sorted(required_columns - selected_columns)
                    if missing_columns:
                        raise ValueError(
                            f"{path}:{table_name}:{vault_name}: bridge select missing required columns: "
                            f"{', '.join(missing_columns)}"
                        )
        declarations.append(data)
    if not declarations:
        raise ValueError(f"No declarations found in {declarations_dir}")
    return sorted(declarations, key=lambda item: (item["source"]["priority"], item["source"]["name"]))


def validate_canonical_mappings(
    declarations: list[dict[str, Any]], openim_root: Path | None
) -> int:
    """Validate each declaration's optional canonical_mappings block against the OpenIM
    model referenced by openim_root, WARN-skipping (never failing) when no root is given
    or the given root does not resolve to a checkout -- the check is an investment-domain
    onboarding aid, not a factory gate (see README "What this is not").

    Returns the count of WARN-level skip conditions encountered (0 when the check ran, 1
    when it skipped). --strict-openim (main(), below) is what turns a positive count into
    a non-zero exit; this function's own behaviour -- what it prints, when it skips -- is
    unchanged either way, so the flag changes only validation strictness.

    A mapping's business_keys/attributes sections are both optional (mapping.get(...,
    {}) below): an entry that omits one or both must fall through to a plain "no attrs
    to check for this section" rather than KeyError -- see tests/python/test_emit.py's
    omission regressions.
    """
    if openim_root is None:
        print("WARN canonical mapping validation skipped: no --openim-root given")
        return 1
    if not openim_root.exists():
        print(f"WARN canonical mapping validation skipped: OpenIM repo not found at {openim_root}")
        return 1
    cache: dict[str, set[str]] = {}
    for declaration in declarations:
        source_name = declaration["source"]["name"]
        for entity_name, mapping in declaration.get("canonical_mappings", {}).items():
            model_file = mapping.get("model_file")
            if not model_file:
                raise ValueError(f"{source_name}:{entity_name}: canonical mapping needs model_file")
            if model_file not in cache:
                cache[model_file] = set(parse_model_attribute_schema(openim_root / model_file))
            declared_attrs = set(cache[model_file])
            values = []
            for section_name in ("business_keys", "attributes"):
                section = mapping.get(section_name, {})
                if not isinstance(section, dict):
                    raise ValueError(f"{source_name}:{entity_name}:{section_name}: expected mapping")
                values.extend(section.values())
            missing = sorted({value for value in values if value not in declared_attrs})
            if missing:
                raise ValueError(
                    f"{source_name}:{entity_name}: mapped attributes not in {model_file}: {missing}"
                )
    return 0


def render(env: Environment, template_name: str, **context: Any) -> str:
    return normalise_sql_newlines(env.get_template(template_name).render(**context))


def select_vaults(declarations: list[dict[str, Any]]) -> list[dict[str, Any]]:
    vaults: list[dict[str, Any]] = []
    for declaration in declarations:
        source = declaration["source"]
        for table in declaration.get("tables", {}).values():
            for vault in table.get("vault_entities", []):
                if not vault.get("enabled", True):
                    continue
                entry = dict(vault)
                entry["source"] = source
                entry["table"] = table
                entry["source_order"] = source["priority"]
                vaults.append(entry)
    return vaults


def as_template_columns(names: list[str]) -> list[dict[str, str]]:
    return [{"name": name, "expression": name} for name in names]


def bronze_product_files(
    typed: Any, *, ctx: EstateContext | None = None
) -> list[GeneratedFile]:
    """Durable canonical Bronze Product Contract artefacts. Binding-specific
    ODCS/ODPS projections are emitted by emit_contracts / emit_odps."""
    ctx = ctx or _DEFAULT_CTX
    files: list[GeneratedFile] = []
    for table in typed.production_contracts():
        document = canonical_contract_document(table)
        path = bronze_product_dir(ctx.contracts_dir, table.logical_identity) / "bronze-product.json"
        files.append(
            GeneratedFile(
                path,
                json.dumps(document, indent=2, ensure_ascii=False) + "\n",
            )
        )
    return files


def generate_files(
    declarations: list[dict[str, Any]],
    env: Environment,
    domain: dict[str, Any],
    *,
    ctx: EstateContext | None = None,
    typed: Any | None = None,
    bound: dict | None = None,
    plan_digest: str | None = None,
) -> list[GeneratedFile]:
    # Local estate root binds this run's context; every emitted path is anchored on it.
    REPO_ROOT = (ctx or _DEFAULT_CTX).root
    entity_configs = domain["entity_configs"]
    hub_configs = domain["hub_configs"]
    link_configs = domain["link_configs"]
    bv_configs = domain["bv_configs"]
    res_configs = domain["res_configs"]
    files: list[GeneratedFile] = []
    all_tables = [
        table
        for declaration in declarations
        for table in declaration.get("tables", {}).values()
    ]
    for table in all_tables:
        table.setdefault("visibility_join", "")
        table.setdefault("bronze_source_yaml", "")
    vaults = select_vaults(declarations)

    if typed is not None and bound:
        annotate_production_tables(
            declarations, typed, bound, plan_digest=plan_digest or bronze_plan_digest()
        )

    for table in all_tables:
        files.append(
            GeneratedFile(
                REPO_ROOT / "models" / "staging" / f"{table['staging_model']}.sql",
                render(env, "staging.sql.j2", generated_header=SQL_HEADER, table=table),
            )
        )

    for vault in vaults:
        entity = entity_configs[vault["entity"]]
        files.append(
            GeneratedFile(
                REPO_ROOT / "models" / "raw_vault" / "stage" / "bridge" / f"{vault['bridge_model']}.sql",
                render(env, "bridge.sql.j2", generated_header=SQL_HEADER, vault=vault),
            )
        )
        files.append(
            GeneratedFile(
                REPO_ROOT / "models" / "raw_vault" / "stage" / f"{vault['stage_model']}.sql",
                render(
                    env,
                    "automate_dv_stage.sql.j2",
                    generated_header=SQL_HEADER,
                    vault=vault,
                    entity=entity,
                ),
            )
        )
        files.append(
            GeneratedFile(
                REPO_ROOT / "models" / "raw_vault" / "satellites" / f"{vault['satellite_model']}.sql",
                render(
                    env,
                    "satellite.sql.j2",
                    generated_header=SQL_HEADER,
                    vault=vault,
                    entity=entity,
                ),
            )
        )

    for hub_entity, hub in hub_configs.items():
        source_models = [vault["stage_model"] for vault in vaults if vault["entity"] == hub_entity]
        files.append(
            GeneratedFile(
                REPO_ROOT / hub["path"],
                render(
                    env,
                    "hub.sql.j2",
                    generated_header=SQL_HEADER,
                    source_models=source_models,
                    hub=hub,
                ),
            )
        )

    for link_name, link in link_configs.items():
        source_models = [
            vault["stage_model"]
            for vault in vaults
            if link_name in entity_configs[vault["entity"]]["links"]
        ]
        files.append(
            GeneratedFile(
                REPO_ROOT / link["path"],
                render(
                    env,
                    "link.sql.j2",
                    generated_header=SQL_HEADER,
                    source_models=source_models,
                    link=link,
                ),
            )
        )

    for entity_name, bv in bv_configs.items():
        entity_vaults = [vault for vault in vaults if vault["entity"] == entity_name]
        source_satellites = [
            {"name": vault["source"]["display_name"], "model": vault["satellite_model"]}
            for vault in entity_vaults
        ]
        source_priority = [vault["source"]["display_name"] for vault in entity_vaults]
        rules = {
            attr: {"strategy": strategy, "source_priority": "__SOURCE_PRIORITY__"}
            for attr, strategy in bv["rules"].items()
        }
        # The survivorship macro expects source_priority as a dbt variable, not a literal string.
        rules_literal = py_literal(rules).replace("'__SOURCE_PRIORITY__'", "source_priority")
        content = render(
            env,
            "survivorship.sql.j2",
            generated_header=SQL_HEADER,
            entity_name=entity_name,
            bv=bv,
            source_satellites=source_satellites,
            source_priority=source_priority,
            rules_set="{%- set rules = " + rules_literal + " -%}",
        )
        files.append(GeneratedFile(REPO_ROOT / bv["path"], content))

    for entity_name, res in res_configs.items():
        branches = []
        for declaration in declarations:
            branch = declaration.get("entity_resolution", {}).get(entity_name)
            if branch:
                branches.append(branch)
        res_context = dict(res)
        res_context["columns"] = as_template_columns(res["columns"])
        res_context["output_columns"] = as_template_columns(res["output_columns"])
        files.append(
            GeneratedFile(
                REPO_ROOT / res["path"],
                render(
                    env,
                    "res_entity.sql.j2",
                    generated_header=SQL_HEADER,
                    branches=branches,
                    res=res_context,
                ),
            )
        )

    seed_tables = []
    seen_seed_names: set[str] = set()
    for table in all_tables:
        if table["landing"]["kind"] != "seed":
            continue
        if table["raw_model"] not in seen_seed_names:
            seed_tables.append(table)
            seen_seed_names.add(table["raw_model"])
    source_groups_by_name: dict[str, dict[str, Any]] = {}
    source_relation_origins: dict[tuple[str, str], str] = {}
    for declaration in declarations:
        declaration_file = declaration["source"]["declaration_file"]
        for table_name, table in declaration.get("tables", {}).items():
            if table["landing"]["kind"] != "source":
                continue
            source_name = table["landing"]["source_name"]
            identifier = table["landing"]["identifier"]
            source_relation = (source_name, identifier)
            origin = f"{declaration_file}:tables.{table_name}"
            previous = source_relation_origins.get(source_relation)
            if previous is not None:
                raise ValueError(
                    f"duplicate dbt source relation source('{source_name}', '{identifier}') "
                    f"declared by {previous} and {origin}; tests and descriptions cannot "
                    "be attached without silently dropping one declaration"
                )
            source_group = source_groups_by_name.setdefault(
                source_name, {"name": source_name, "tables": []}
            )
            source_group["tables"].append(table)
            source_relation_origins[source_relation] = origin
    attach_source_physical_coords(list(source_groups_by_name.values()))
    projection_groups = (
        production_projection_groups(typed, bound) if typed is not None and bound else []
    )
    files.append(
        GeneratedFile(
            REPO_ROOT / "models" / "staging" / "_sources.yml",
            render(
                env,
                "sources.yml.j2",
                generated_header=YAML_HEADER,
                seed_tables=seed_tables,
                source_groups=list(source_groups_by_name.values()),
                projection_source_groups=projection_groups,
                staging_tables=all_tables,
            ),
        )
    )
    if typed is not None:
        files.extend(bronze_product_files(typed, ctx=ctx or _DEFAULT_CTX))
    return files


def write_files(
    files: list[GeneratedFile], check: bool = False, *, root: Path | None = None
) -> list[Path]:
    changed: list[Path] = []
    for file in files:
        if root is not None and not file.path.resolve().is_relative_to(Path(root).resolve()):
            raise ValueError(
                f"refusing to write {file.path}: resolved outside the estate root {root}"
            )
        existing = file.path.read_text(encoding="utf-8") if file.path.exists() else None
        if existing == file.content:
            continue
        changed.append(file.path)
        if check:
            before = existing.splitlines() if existing is not None else []
            after = file.content.splitlines()
            diff = "\n".join(
                difflib.unified_diff(before, after, fromfile=str(file.path), tofile=str(file.path))
            )
            print(diff)
            continue
        file.path.parent.mkdir(parents=True, exist_ok=True)
        if file.path.suffix == ".json":
            file.path.write_bytes(file.content.encode("utf-8"))
        else:
            file.path.write_text(file.content, encoding="utf-8")
    return changed


def prune_orphaned_files(
    generated_paths: set[Path], check: bool = False, *, ctx: EstateContext | None = None
) -> list[Path]:
    """Delete generated files that are no longer in the current generated set.

    Scans the models tree for files marked with GENERATED_MARKER and removes
    any that are not in the current generated_paths set. This prevents orphaned
    files from accumulating when declarations are removed or renamed.

    Args:
        generated_paths: Set of all paths that should be generated from current
            declarations (typically from GeneratedFile objects)
        check: If True, report would-delete without deleting

    Returns:
        List of paths that were (or would be) deleted, in relative form
    """
    deleted: list[Path] = []
    ctx = ctx or _DEFAULT_CTX
    REPO_ROOT = ctx.root
    MODELS_DIR = ctx.models_dir

    # Scan for emitted SQL and YAML files marked with GENERATED_MARKER
    # Scope to models/ only to avoid dbt build artifacts in target/
    for ext in ("*.sql", "*.yml"):
        for path in MODELS_DIR.rglob(ext):
            if not _is_generated(path):
                continue
            if path in generated_paths:
                continue
            # This file was generated but is no longer in the set
            deleted.append(path.relative_to(REPO_ROOT))
            if not check:
                path.unlink()

    bronze_root = ctx.contracts_dir / "bronze"
    if bronze_root.exists():
        for path in bronze_root.rglob("bronze-product.json"):
            if path in generated_paths:
                continue
            deleted.append(path.relative_to(REPO_ROOT))
            if not check:
                path.unlink()

    # Sort for deterministic output across platforms
    return sorted(deleted)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Print diffs without writing files.")
    parser.add_argument(
        "--estate-root",
        type=Path,
        default=None,
        help=(
            "Root of the data-product ESTATE to emit against (declarations/, domains/, "
            "models/, ...). Highest-precedence override of the estate-root resolution chain "
            "(--estate-root > DPF_ESTATE_ROOT env > walk-up from cwd to the nearest "
            "dbt_project.yml+domains/ ancestor > the package's own source tree). Engine "
            "data (templates, schemas) is package-relative and NOT affected by this."
        ),
    )
    parser.add_argument(
        "--openim-root",
        type=Path,
        default=None,
        help=(
            "OpenIM repo root used for the investment domain's OPTIONAL, per-domain "
            "canonical-mapping validation. Skip-safe: absent (the default) or missing, the "
            "check WARN-skips (a domain with no canonical_mappings needs no model repo)."
        ),
    )
    parser.add_argument(
        "--domains-dir",
        type=Path,
        default=None,
        help=(
            "Directory of per-domain model-config YAML (domains/*.yml). Defaults to the "
            "resolved estate's domains/. All files are merged; a second domain is onboarded "
            "by adding a file here plus declarations, with no engine change."
        ),
    )
    parser.add_argument(
        "--strict-openim",
        action="store_true",
        help=(
            "Fail (non-zero exit) instead of WARN-skipping when the optional OpenIM "
            "canonical-mapping validation cannot run -- no --openim-root given, or the "
            "given root does not resolve to a checkout. Default: unchanged, WARN-skip "
            "only (see --openim-root above); this flag changes only the exit code, never "
            "what gets generated."
        ),
    )
    parser.add_argument(
        "--lint-target",
        default=os.environ.get("DPF_LINT_TARGET"),
        help=(
            "Additional registered adapter for the post-emit dialect gate (also read "
            "from DPF_LINT_TARGET). All declared deployment adapters are always "
            "linted; a requested registered adapter is added when it is not declared."
        ),
    )
    parser.add_argument(
        "--binding",
        type=Path,
        default=None,
        help=(
            "RuntimeBinding YAML file or directory. Required when any production "
            "Bronze source is declared; --environment must equal each binding's "
            "environment."
        ),
    )
    parser.add_argument(
        "--environment",
        default=None,
        help="Mandatory matching assertion against RuntimeBinding.environment.",
    )
    args = parser.parse_args()

    ctx = EstateContext.resolve(
        estate_root=args.estate_root,
        openim_root=args.openim_root,
        domains_dir=args.domains_dir,
    )

    domain = load_domains(ctx=ctx)
    validate_bv_rules_subset_of_payload(domain["bv_configs"], domain["entity_configs"])
    validate_domain_paths(domain)
    validate_res_configs(domain["res_configs"], ctx=ctx)
    declarations = load_declarations(domain, ctx=ctx)
    validate_unique_source_priorities(declarations)
    validate_er_branch_coverage(declarations, domain["res_configs"], ctx=ctx)
    try:
        check_casefold_identities(declarations)
        typed = load_typed_declarations(ctx)
        reject_draft_generation(typed)
    except ValueError as error:
        print(f"FAIL: {error}")
        return 1
    bound = {}
    plan_digest = None
    if typed.production_contracts():
        if args.binding is None or args.environment is None:
            print(
                "FAIL: production Bronze generation needs --binding PATH and "
                "--environment NAME"
            )
            return 2
        try:
            bindings = load_runtime_bindings(args.binding, args.environment)
            plan_digest = bronze_plan_digest()
            bound = bind_production_sources(typed, bindings)
        except ValueError as error:
            print(f"FAIL: {error}")
            return 2
    warning_count = validate_canonical_mappings(declarations, ctx.openim_root)
    env = template_env()
    files = generate_files(
        declarations, env, domain, ctx=ctx, typed=typed, bound=bound, plan_digest=plan_digest
    )
    changed = write_files(files, check=args.check, root=ctx.root)
    action = "would change" if args.check else "generated"
    summary = f"{action} {len(changed)} of {len(files)} files"
    if warning_count:
        summary += f" ({warning_count} warning{'s' if warning_count != 1 else ''})"
    print(summary)
    for path in changed:
        print(path.relative_to(ctx.root).as_posix())

    # Prune orphaned generated files (those no longer declared)
    generated_paths = {file.path for file in files}
    deleted = prune_orphaned_files(generated_paths, check=args.check, ctx=ctx)
    if deleted:
        prune_action = "would delete" if args.check else "deleted"
        print(f"{prune_action} {len(deleted)} orphaned generated file(s)")
        for path in deleted:
            print(path.as_posix())
    # Structural, machine-readable orphan signal: a stable marker line, printed on
    # EVERY run (including ORPHANS=0), independent of the prose above. A caller that
    # needs to know whether orphans exist parses this line instead of grepping the
    # human-facing message, which can be reworded without the signal moving.
    print(f"ORPHANS={len(deleted)}")

    # Factory gate: every deployment adapter declared under declarations/targets/
    # gets its own dialect pass in this invocation. Declaration loading and the
    # deployment-kind filter are shared with structure_gate rather than re-derived.
    try:
        target_declarations, _ = load_structure_declarations(ctx)
    except ValueError as error:
        print(f"structure-gate FAIL: {error}")
        return 1

    try:
        lint_targets = [
            declaration.adapter
            for declaration in target_declarations
            if declaration.kind == "deployment"
        ]
        if args.lint_target and args.lint_target not in DENY_LISTS:
            raise ValueError(
                f"--lint-target/DPF_LINT_TARGET names unknown adapter {args.lint_target!r}; "
                "it must be registered in ergasterion.dialect_lint.DENY_LISTS"
            )
        if args.lint_target:
            print(
                f"dialect-lint compatibility target {args.lint_target!r} acknowledged; "
                "checking every declared deployment adapter"
            )
            if args.lint_target not in lint_targets:
                lint_targets.append(args.lint_target)
        for lint_target in lint_targets:
            offenses = lint_models(lint_target, ctx=ctx)
            if offenses:
                print(
                    f"dialect-lint FAIL [{lint_target}]: {len(offenses)} "
                    "incompatible construct(s) in model/test SQL:"
                )
                for off in offenses:
                    rel = off.path.relative_to(ctx.root).as_posix()
                    print(f"  {rel}:{off.line_no}  [{off.token}]  {off.message}")
                return 1
            print(f"dialect-lint OK [{lint_target}]: model/test SQL clean")
    except ValueError as error:
        print(f"dialect-lint FAIL: {error}")
        return 1

    # Factory gate: the estate stays within every declared target's structural
    # budgets (declarations/targets/*.yml) -- materialisation boundaries, view
    # chain depth, statement size, identifier length, metadata payload. The
    # checks and the declaration format live in ergasterion/structure_gate.py.
    try:
        structure_offenses = check_structure(ctx)
    except ValueError as error:
        print(f"structure-gate FAIL: {error}")
        return 1
    if structure_offenses:
        print(f"structure-gate FAIL: {len(structure_offenses)} budget offense(s):")
        for offense in structure_offenses:
            print(
                f"  [{offense.adapter}] {offense.budget}: {offense.artefact} -- "
                f"{offense.message}"
            )
        return 1
    print("structure-gate OK: estate within every declared target budget")

    if args.strict_openim and warning_count:
        print(
            f"FAIL --strict-openim: OpenIM canonical mapping validation was skipped "
            f"({warning_count} warning{'s' if warning_count != 1 else ''}); rerun with "
            f"--openim-root pointed at a real checkout, or drop --strict-openim.",
            file=sys.stderr,
        )
        return 1

    # --check fails on either an unwritten diff OR an orphan that would be pruned:
    # both mean the on-disk tree does not match current declarations. Orphans used
    # to be reported (see the prose above and ORPHANS=<n>) without moving this exit
    # code, so a --check run with only orphans and no other diff exited 0 -- a
    # fail-open silently papered over by validators grepping the prose message.
    return 1 if args.check and (changed or deleted) else 0


if __name__ == "__main__":
    raise SystemExit(main())
