"""Emit deterministic ODCS v3.1 data contracts for served tables.

Ergasterion reads the compiled dbt manifest, domain configuration, and source declarations.
It writes one contract per served canonical or mart model, excluding intermediate helpers.
Each contract records schema, keys, quality checks, survivorship provenance, and any
declared authoritative-model link.

Inputs (all read-only; the declarations stay SSOT):
  - target/manifest.json          the dbt manifest (offline `dbt parse`) -- served-model
                                  schema (documented columns), materialization, and the
                                  generic + singular dbt TESTS attached to each model.
  - domains/*.yml `odcs:` block   per-domain boundary config: ODCS domain name, contract
                                  version/status, target-warehouse server, optional
                                  authoritativeDefinitions link, and the served-product
                                  list (each optionally bound to a survivorship entity).
  - declarations/*.yml            source priority order feeding each survivorship entity.

Outputs:
  - contracts/<domain>/<table>.odcs.yml   one ODCS v3.1.0 contract per served table,
                                          regenerated-never-hand-edited.

Contract ids are
`dpf:<domain>:<table>` and versions come from the domain config -- no timestamps, no
UUIDs, no manifest-metadata leakage. The same manifest regenerates byte-identical output.
Every emitted contract is validated in-process against the vendored ODCS v3.1 JSON Schema
(schemas/odcs-json-schema-v3.1.0.json) without network access.

Usage:
    python ergasterion/emit_contracts.py            # write + validate every contract
    python ergasterion/emit_contracts.py --check    # validate + fail if on-disk drifted / hand-edited
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft201909Validator

# Support installed-command and direct-script execution.
if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion import emit
from ergasterion.estate import EstateContext
from ergasterion.source_delivery import load_typed_declarations
from ergasterion.translators.dbt import (
    bind_production_sources,
    bronze_binding_dir,
    bronze_odcs_id,
    bronze_plan_digest,
    graph_contract_identity,
    landing_handle,
    load_runtime_bindings,
    reject_draft_generation,
)

# Ambient estate context; functions default to it, a caller threads its own via `ctx=`.
_DEFAULT_CTX = EstateContext.default()

# ESTATE paths -- ride the context. Aliases kept for back-compat reads.
REPO_ROOT = _DEFAULT_CTX.root
CONTRACTS_DIR = _DEFAULT_CTX.contracts_dir
MANIFEST_PATH = _DEFAULT_CTX.manifest_path
# ENGINE DATA (the vendored ODCS JSON Schema) resolves package-relative -- shipped as
# package data inside ergasterion/, never estate-anchored (two-class principle).
SCHEMA_PATH = Path(__file__).resolve().parent / "schemas" / "odcs-json-schema-v3.1.0.json"

API_VERSION = "v3.1.0"
KIND = "DataContract"
GENERATED_HEADER = (
    "# Generated by ergasterion/emit_contracts.py from the dbt manifest + declarations/domains SSOT.\n"
    "# ODCS v3.1.0 data contract -- regenerated, never hand-edited. Do not edit by hand.\n"
)

# The served product surface: models under these two layers, minus dbt's standard
# intermediate/internal helpers (`int_*` prefix, `*_base` suffix). This is a factory-level
# policy (what counts as a served product), not domain vocabulary -- it names no entity.
SERVED_LAYERS = ("canonical", "marts")

# Deterministic logicalType derivation. The dbt manifest carries no physical column types
# for these views/tables (types would require a live catalog via `dbt docs generate`, which
# is out of scope for an offline adapter). We assign an ODCS logicalType only from strong,
# documented naming/test conventions, defaulting to `string` (the served schema is
# identifier/code heavy). Physical types are intentionally omitted -- see the README.
_DATE_SUFFIXES = ("_date", "_at")
_DATE_EXACT = {"date_day", "effective_from", "effective_to"}
_STRING_SUFFIXES = ("_key", "_id", "_hk", "_lhk", "_code")


def load_schema_validator() -> Draft201909Validator:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return Draft201909Validator(schema)


def load_manifest(ctx: EstateContext | None = None) -> dict[str, Any]:
    manifest_path = (ctx or _DEFAULT_CTX).manifest_path
    if not manifest_path.exists():
        raise SystemExit(
            f"FAIL: dbt manifest not found at {manifest_path}. Run `dbt parse` first "
            f"(the build validator does this before the contract gate)."
        )
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def load_domain_odcs(ctx: EstateContext | None = None) -> dict[str, dict[str, Any]]:
    """Load the per-domain `odcs:` boundary block from every domains/*.yml.

    Returns {domain_file_stem: odcs_block}. Unlike emit.load_domains (which MERGES all
    domain vocab into one config), this keeps per-domain identity -- each domain owns its
    own server, contract version, authoritativeDefinitions and product list.
    """
    result: dict[str, dict[str, Any]] = {}
    domains_dir = (ctx or _DEFAULT_CTX).domains_dir
    files = sorted(domains_dir.glob("*.yml"))
    if not files:
        raise ValueError(f"No domain config found in {domains_dir}")
    for path in files:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        odcs = (data or {}).get("odcs")
        if not odcs:
            raise ValueError(f"{path}: missing required 'odcs:' section for the contract adapter")
        if "domain" not in odcs:
            raise ValueError(f"{path}: odcs.domain is required")
        if not odcs.get("products"):
            raise ValueError(f"{path}: odcs.products is required and must be non-empty")
        result[path.stem] = odcs
    return result


def served_models(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Every served model node keyed by model name (canonical/ + marts/, minus int_/_base)."""
    served: dict[str, dict[str, Any]] = {}
    for node in manifest["nodes"].values():
        if node.get("resource_type") != "model":
            continue
        parts = node["original_file_path"].replace("\\", "/").split("/")
        if len(parts) >= 2 and parts[0] == "models" and parts[1] in SERVED_LAYERS:
            name = node["name"]
            if name.startswith("int_") or name.endswith("_base"):
                continue
            served[name] = node
    return served


def _extract_ref(expr: str) -> str | None:
    """`{{ get_where_subquery(ref('canonical_gp')) }}` / `ref('canonical_gp')` -> canonical_gp."""
    if not isinstance(expr, str):
        return None
    match = re.search(r"ref\(\s*'([^']+)'\s*\)", expr)
    return match.group(1) if match else None


def collect_tests(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Map every served model to its dbt tests, split into column-attached generic tests
    and model-level singular (bespoke) tests, read straight from the manifest.

    Returns {model_name: {"columns": {col: [test_dict, ...]}, "singular": [test_name, ...]}}.
    A test's OWNING model is `attached_node` (never a referenced model), so a relationships
    test -- whose depends_on lists both the tested and the referenced model -- is attached
    only to the model under test.
    """
    uid_to_name = {
        uid: node["name"]
        for uid, node in manifest["nodes"].items()
        if node.get("resource_type") == "model"
    }
    out: dict[str, dict[str, Any]] = {}

    def bucket(model_name: str) -> dict[str, Any]:
        return out.setdefault(model_name, {"columns": {}, "singular": []})

    for node in manifest["nodes"].values():
        if node.get("resource_type") != "test":
            continue
        meta = node.get("test_metadata") or {}
        test_name = meta.get("name")
        if test_name is None:
            # Singular (bespoke) assertion -> table-level custom rule on every served model
            # it depends on. depends_on is the only link a singular test carries.
            for uid in node.get("depends_on", {}).get("nodes", []):
                model_name = uid_to_name.get(uid)
                if model_name is not None:
                    bucket(model_name)["singular"].append(node["name"])
            continue
        attached = node.get("attached_node")
        model_name = uid_to_name.get(attached)
        if model_name is None:
            # Fall back to the ref() named in kwargs.model if attached_node is absent.
            model_name = _extract_ref(meta.get("kwargs", {}).get("model", ""))
        if model_name is None:
            continue
        column = node.get("column_name")
        entry = {
            "name": test_name,
            "namespace": meta.get("namespace"),
            "kwargs": meta.get("kwargs", {}),
        }
        bucket(model_name)["columns"].setdefault(column, []).append(entry)

    # Deterministic ordering within each column and the singular list.
    for model in out.values():
        for tests in model["columns"].values():
            tests.sort(key=lambda t: (t["namespace"] or "", t["name"], json.dumps(t["kwargs"], sort_keys=True)))
        model["singular"] = sorted(set(model["singular"]))
    return out


def _has_test(tests: list[dict[str, Any]], name: str, namespace: str | None = None) -> bool:
    return any(t["name"] == name and t["namespace"] == namespace for t in tests)


def logical_type(column: str, tests: list[dict[str, Any]]) -> str:
    """Deterministic ODCS logicalType from column-name + test conventions (see module docstring)."""
    lower = column.lower()
    if lower in _DATE_EXACT or lower.endswith(_DATE_SUFFIXES):
        return "date"
    # A range-checked column is numeric; an accepted-values column is a string enum.
    if _has_test(tests, "accepted_range", "dbt_utils"):
        return "number"
    if lower.endswith(_STRING_SUFFIXES):
        return "string"
    return "string"


def _library_metric(metric: str, dimension: str, description: str) -> dict[str, Any]:
    return {
        "type": "library",
        "metric": metric,
        "mustBe": 0,
        "dimension": dimension,
        "description": description,
    }


def _custom_rule(implementation: str, dimension: str, description: str) -> dict[str, Any]:
    return {
        "type": "custom",
        "engine": "dbt",
        "implementation": implementation,
        "dimension": dimension,
        "description": description,
    }


def column_quality(tests: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Map a column's dbt tests to ODCS quality entries.

    not_null / unique -> the v3.1 metrics library (nullValues / duplicateValues, mustBe 0).
    relationships / accepted_values / accepted_range / expression_is_true -> custom rules
    (the "bespoke asserts -> custom rules" mapping).
    """
    quality: list[dict[str, Any]] = []
    for test in tests:
        name, ns, kwargs = test["name"], test["namespace"], test["kwargs"]
        if ns is None and name == "not_null":
            quality.append(_library_metric("nullValues", "completeness", "dbt not_null test: no null values."))
        elif ns is None and name == "unique":
            quality.append(_library_metric("duplicateValues", "uniqueness", "dbt unique test: no duplicate values."))
        elif ns is None and name == "relationships":
            to_model = _extract_ref(kwargs.get("to", "")) or kwargs.get("to", "")
            field = kwargs.get("field", "")
            quality.append(_custom_rule(
                f"dbt relationships test: every value exists in {to_model}.{field}",
                "consistency",
                "Referential-integrity check against the parent served table.",
            ))
        elif ns is None and name == "accepted_values":
            values = kwargs.get("values", [])
            quality.append(_custom_rule(
                f"dbt accepted_values test: value in {json.dumps(values)}",
                "conformity",
                "Domain/enumeration constraint on the column.",
            ))
        elif ns == "dbt_utils" and name == "accepted_range":
            bounds = {k: kwargs[k] for k in ("min_value", "max_value", "inclusive") if k in kwargs}
            quality.append(_custom_rule(
                f"dbt_utils accepted_range test: {json.dumps(bounds, sort_keys=True)}",
                "conformity",
                "Numeric range constraint on the column.",
            ))
        elif ns == "dbt_utils" and name == "expression_is_true":
            quality.append(_custom_rule(
                f"dbt_utils expression_is_true test: {kwargs.get('expression', '')}",
                "conformity",
                "Row-level boolean assertion on the column.",
            ))
        else:
            # Any other generic test still lands as a faithful custom rule rather than
            # being silently dropped (loud-fidelity over silent loss).
            qualified = f"{ns}.{name}" if ns else name
            quality.append(_custom_rule(
                f"dbt {qualified} test: {json.dumps(kwargs, sort_keys=True)}",
                "conformity",
                f"dbt {qualified} generic test.",
            ))
    return quality


def source_priority_for_entity(entity: str, declarations: list[dict[str, Any]]) -> list[str]:
    """Ordered source display_names feeding a survivorship entity, by source priority asc
    then name -- the order first_non_null survivorship resolves in (per-field source
    attribution basis)."""
    feeders: list[tuple[int, str, str]] = []
    for decl in declarations:
        source = decl["source"]
        feeds = False
        for table in decl.get("tables", {}).values():
            for vault in table.get("vault_entities", []):
                if vault.get("enabled", True) and vault.get("entity") == entity:
                    feeds = True
        if feeds:
            feeders.append((source.get("priority", 100), source["name"], source["display_name"]))
    feeders.sort(key=lambda item: (item[0], item[1]))
    return [display for _, _, display in feeders]


def survivorship_custom_properties(
    entity: str,
    bv_configs: dict[str, Any],
    declarations: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Survivorship priorities + per-field source attribution as ODCS customProperties.

    Emitted only for a product bound to an entity that has a business-vault golden-record
    config (survivorship rules). The rules are the per-field survivorship STRATEGY (the
    declarative provenance of each surviving attribute); sourcePriority is the source order
    the strategy resolves in.
    """
    if entity not in bv_configs:
        return []
    props: list[dict[str, Any]] = [{"property": "dpf.survivorship.entity", "value": entity}]
    priority = source_priority_for_entity(entity, declarations)
    if priority:
        props.append({"property": "dpf.survivorship.sourcePriority", "value": priority})
    rules = bv_configs[entity].get("rules", {})
    if rules:
        props.append({"property": "dpf.survivorship.rules", "value": dict(rules)})
    return props


def build_contract(
    table: str,
    node: dict[str, Any],
    domain_stem: str,
    odcs: dict[str, Any],
    tests: dict[str, Any],
    bv_configs: dict[str, Any],
    declarations: list[dict[str, Any]],
) -> dict[str, Any]:
    """Build one ODCS v3.1.0 contract document (an ordered dict) for a served table."""
    domain_name = odcs["domain"]
    product = odcs["products"][table] or {}
    entity = product.get("entity")

    contract: dict[str, Any] = {
        "apiVersion": API_VERSION,
        "kind": KIND,
        "id": f"dpf:{domain_name}:{table}",
        "version": str(odcs.get("contract_version", "1.0.0")),
        "status": odcs.get("status", "active"),
        "name": table,
        "domain": domain_name,
    }

    description = (node.get("description") or "").strip()
    if description:
        contract["description"] = {"purpose": " ".join(description.split())}

    server = odcs.get("server")
    if server:
        server_entry: dict[str, Any] = {"server": server["server"], "type": server["type"]}
        if server.get("environment"):
            server_entry["environment"] = server["environment"]
        if server.get("description"):
            server_entry["description"] = server["description"]
        # Pass through the warehouse-source connection fields the ODCS schema requires for
        # the declared server type (Snowflake: account/database/schema; BigQuery:
        # project/dataset) plus their optional siblings, in a fixed order. All come from the
        # domain's declarative config -- no secrets, no environment-derived host.
        for key in ("host", "port", "account", "database", "schema", "warehouse", "project", "dataset", "catalog"):
            if server.get(key) is not None:
                server_entry[key] = server[key]
        contract["servers"] = [server_entry]

    # Schema object: one served table, its documented columns, its tests as quality.
    properties: list[dict[str, Any]] = []
    model_tests = tests.get(table, {"columns": {}, "singular": []})
    pk_assigned = False
    pk_position = 0
    for column, meta in node.get("columns", {}).items():
        col_tests = model_tests["columns"].get(column, [])
        not_null = _has_test(col_tests, "not_null")
        unique = _has_test(col_tests, "unique")
        prop: dict[str, Any] = {"name": column, "logicalType": logical_type(column, col_tests)}
        col_desc = (meta.get("description") or "").strip()
        if col_desc:
            prop["description"] = " ".join(col_desc.split())
        if not_null and unique and not pk_assigned:
            pk_position += 1
            prop["primaryKey"] = True
            prop["primaryKeyPosition"] = pk_position
            pk_assigned = True
        if not_null:
            prop["required"] = True
        if unique:
            prop["unique"] = True
        quality = column_quality(col_tests)
        if quality:
            prop["quality"] = quality
        properties.append(prop)

    schema_object: dict[str, Any] = {
        "name": table,
        "physicalName": table,
        "logicalType": "object",
        "physicalType": node.get("config", {}).get("materialized", "view"),
        "properties": properties,
    }
    singular = model_tests["singular"]
    if singular:
        schema_object["quality"] = [
            _custom_rule(
                f"dbt singular data test: {test_name}",
                "consistency",
                "Bespoke table-level dbt assertion.",
            )
            for test_name in singular
        ]
    contract["schema"] = [schema_object]

    auth = odcs.get("authoritative_definitions")
    if auth:
        contract["authoritativeDefinitions"] = [
            {"url": item["url"], "type": item.get("type", "businessDefinition")} for item in auth
        ]

    custom = survivorship_custom_properties(entity, bv_configs, declarations) if entity else []
    if custom:
        contract["customProperties"] = custom

    return contract


def dump_yaml(contract: dict[str, Any]) -> str:
    body = yaml.safe_dump(
        contract,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=100,
    )
    return GENERATED_HEADER + body


_ODCS_LOGICAL = {
    "boolean": "boolean",
    "int64": "integer",
    "utf8_string": "string",
    "date": "date",
    "utc_instant": "timestamp",
    "binary": "string",
    "decimal": "number",
    "local_datetime": "timestamp",
}


def _odcs_logical_type(logical_type: Any) -> str:
    from ergasterion.source_delivery import logical_type_token

    return _ODCS_LOGICAL[logical_type_token(logical_type)]


def _bronze_quality(contract: Any) -> list[dict[str, Any]]:
    """Product-intent quality policy. Run telemetry never enters this projection."""
    quality: list[dict[str, Any]] = []
    for rule in contract.delivery.quality.rules:
        kind = rule.kind
        if kind == "not_null":
            quality.append(_library_metric("nullValues", "completeness", f"not_null on {rule.field}"))
        elif kind == "unique_key":
            quality.append(
                _library_metric("duplicateValues", "uniqueness", f"unique_key on {list(rule.fields)}")
            )
        else:
            quality.append(
                _custom_rule(
                    f"bronze quality rule {kind}",
                    "conformity",
                    f"Authored Bronze quality rule kind={kind}.",
                )
            )
    return quality


def build_bronze_contract(
    typed_table: Any, binding: Any, *, plan_digest: str
) -> dict[str, Any]:
    """Static ODCS v3.1 projection of one Bronze Product Contract. Coordinates
    come only from the selected RuntimeBinding; no operational telemetry."""
    contract = typed_table.contract
    identity = graph_contract_identity(typed_table, plan_digest=plan_digest)
    landing = binding.landing_ports[landing_handle(contract)]
    relations = binding.projection_relations
    properties = []
    for field in contract.projection:
        prop: dict[str, Any] = {
            "name": field.name,
            "logicalType": _odcs_logical_type(field.logical_type),
        }
        if not field.nullable:
            prop["required"] = True
        properties.append(prop)

    schema_object: dict[str, Any] = {
        "name": contract.interfaces.published,
        "physicalName": relations.active_alias,
        "logicalType": "object",
        "physicalType": "table",
        "properties": properties,
    }
    quality = _bronze_quality(contract)
    if quality:
        schema_object["quality"] = quality

    server_entry: dict[str, Any] = {
        "server": binding.binding_id,
        "type": "custom",
        "environment": binding.environment,
        "schema": relations.schema_ref,
    }
    database = relations.database_ref or landing.database_ref
    if database:
        server_entry["database"] = database

    lineage = [{"source": field.source, "name": field.name} for field in contract.projection]
    product = contract.product
    doc: dict[str, Any] = {
        "apiVersion": API_VERSION,
        "kind": KIND,
        "id": bronze_odcs_id(identity),
        "version": product.product_version,
        "status": "active",
        "name": identity["table"],
        "domain": product.domain,
        "dataProduct": bronze_odcs_id(identity),
        "description": {"purpose": product.description},
        "servers": [server_entry],
        "schema": [schema_object],
        "team": {"name": product.owner, "description": f"Owner {product.owner}."},
        "support": [
            {
                "channel": product.support,
                "url": f"https://example.invalid/support/{product.support}",
                "description": f"Support contact {product.support}.",
            }
        ],
        "customProperties": [
            {"property": "dpf.identity", "value": identity},
            {"property": "dpf.classification", "value": product.classification},
            {"property": "dpf.accessPolicyRef", "value": product.access_policy_ref},
            {"property": "dpf.retentionPolicyRef", "value": product.retention_policy_ref},
            {"property": "dpf.fieldLineage", "value": lineage},
        ],
    }
    return doc


def generate_bronze(
    ctx: EstateContext | None = None,
    *,
    binding_path: Path | None = None,
    environment: str | None = None,
) -> dict[Path, str]:
    """Binding-specific ODCS projections under contracts/bronze/**."""
    ctx = ctx or _DEFAULT_CTX
    typed = load_typed_declarations(ctx)
    reject_draft_generation(typed)
    if not typed.production_contracts():
        return {}
    if binding_path is None or environment is None:
        raise ValueError(
            "production Bronze ODCS generation needs --binding PATH and --environment NAME"
        )
    bindings = load_runtime_bindings(binding_path, environment)
    plan_digest = bronze_plan_digest()
    bound = bind_production_sources(typed, bindings)
    files: dict[Path, str] = {}
    for key, typed_table in typed.tables.items():
        if typed_table.kind != "production":
            continue
        binding = bound[key]
        path = (
            bronze_binding_dir(ctx.contracts_dir, typed_table.contract.logical_identity, binding.binding_id)
            / "bronze.odcs.yml"
        )
        files[path] = dump_yaml(build_bronze_contract(typed_table, binding, plan_digest=plan_digest))
    return files


def _is_bronze_path(path: Path, contracts_dir: Path) -> bool:
    bronze = (contracts_dir / "bronze").resolve()
    try:
        return path.resolve().is_relative_to(bronze)
    except (OSError, ValueError):
        return False


def generate(ctx: EstateContext | None = None) -> dict[Path, str]:
    """Build the full {path: yaml_text} set of contracts. Also runs the completeness gate."""
    ctx = ctx or _DEFAULT_CTX
    contracts_dir = ctx.contracts_dir
    manifest = load_manifest(ctx)
    domain_odcs = load_domain_odcs(ctx=ctx)
    domain = emit.load_domains(ctx=ctx)
    bv_configs = domain["bv_configs"]
    declarations = emit.load_declarations(domain, ctx=ctx)
    served = served_models(manifest)
    tests = collect_tests(manifest)

    # Completeness gate: every served model must be claimed by exactly one domain's
    # product list, and no product may name a non-served model (loud-fail thesis).
    claimed: dict[str, str] = {}
    for stem, odcs in domain_odcs.items():
        for table in odcs["products"]:
            if table in claimed:
                raise ValueError(
                    f"served product {table!r} claimed by both domains "
                    f"'{claimed[table]}' and '{stem}' -- a product belongs to one domain"
                )
            claimed[table] = stem
    served_names = set(served)
    unclaimed = sorted(served_names - set(claimed))
    if unclaimed:
        raise ValueError(
            "served table(s) have no ODCS contract: "
            + ", ".join(unclaimed)
            + " -- add each to an odcs.products list in domains/*.yml (or, if it is an "
            "internal helper, rename it int_*/*_base)."
        )
    phantom = sorted(set(claimed) - served_names)
    if phantom:
        raise ValueError(
            "odcs.products names non-served model(s): "
            + ", ".join(phantom)
            + " -- remove the entry or check the model exists under models/canonical|marts/."
        )

    files: dict[Path, str] = {}
    for stem, odcs in domain_odcs.items():
        domain_name = odcs["domain"]
        for table in odcs["products"]:
            contract = build_contract(
                table, served[table], stem, odcs, tests, bv_configs, declarations
            )
            path = contracts_dir / domain_name / f"{table}.odcs.yml"
            files[path] = dump_yaml(contract)
    return files


def validate_all(
    files: dict[Path, str], validator: Draft201909Validator, *, ctx: EstateContext | None = None
) -> list[str]:
    """Validate every generated contract against the vendored ODCS v3.1 JSON Schema."""
    root = (ctx or _DEFAULT_CTX).root
    errors: list[str] = []
    for path in sorted(files):
        doc = yaml.safe_load(files[path])
        schema_errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.absolute_path))
        for err in schema_errors:
            location = "/".join(str(p) for p in err.absolute_path) or "<root>"
            errors.append(f"{path.relative_to(root).as_posix()}: {location}: {err.message}")
    return errors


def write_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[Path]:
    contracts_dir = (ctx or _DEFAULT_CTX).contracts_dir
    changed: list[Path] = []
    live = set(files)
    # Prune stale contracts (a served table renamed/removed) so the dir can't accrete orphans.
    if contracts_dir.exists():
        for existing in contracts_dir.rglob("*.odcs.yml"):
            if _is_bronze_path(existing, contracts_dir):
                continue
            if existing not in live:
                changed.append(existing)
                existing.unlink()
    for path in sorted(files):
        content = files[path]
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Explicit LF bytes: byte-stable across platforms regardless of text-mode newline
        # translation; .gitattributes pins *.yml to eol=lf for the committed form too.
        path.write_bytes(content.encode("utf-8"))
    return changed


def check_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[str]:
    """Report every on-disk divergence from the freshly generated set (hand-edit / drift /
    missing / orphan) WITHOUT writing -- this is the byte-stable + never-hand-edited gate."""
    ctx = ctx or _DEFAULT_CTX
    contracts_dir = ctx.contracts_dir
    root = ctx.root
    problems: list[str] = []
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            problems.append(f"MISSING (never generated on disk): {rel}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != files[path]:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(), files[path].splitlines(),
                    fromfile=f"{rel} (on disk)", tofile=f"{rel} (regenerated)", lineterm="",
                )
            )
            problems.append(f"DRIFT (hand-edited or stale): {rel}\n{diff}")
    if contracts_dir.exists():
        live = set(files)
        for existing in sorted(contracts_dir.rglob("*.odcs.yml")):
            if _is_bronze_path(existing, contracts_dir):
                continue
            if existing not in live:
                problems.append(
                    f"ORPHAN (on disk, no longer generated): {existing.relative_to(root).as_posix()}"
                )
    return problems


def write_bronze_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[Path]:
    ctx = ctx or _DEFAULT_CTX
    bronze_dir = ctx.contracts_dir / "bronze"
    changed: list[Path] = []
    live = set(files)
    if bronze_dir.exists():
        for existing in bronze_dir.rglob("bronze.odcs.yml"):
            if existing not in live:
                changed.append(existing)
                existing.unlink()
    for path in sorted(files):
        content = files[path]
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
    return changed


def check_bronze_files(files: dict[Path, str], *, ctx: EstateContext | None = None) -> list[str]:
    ctx = ctx or _DEFAULT_CTX
    bronze_dir = ctx.contracts_dir / "bronze"
    root = ctx.root
    problems: list[str] = []
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            problems.append(f"MISSING (never generated on disk): {rel}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != files[path]:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(), files[path].splitlines(),
                    fromfile=f"{rel} (on disk)", tofile=f"{rel} (regenerated)", lineterm="",
                )
            )
            problems.append(f"DRIFT (hand-edited or stale): {rel}\n{diff}")
    if bronze_dir.exists():
        live = set(files)
        for existing in sorted(bronze_dir.rglob("bronze.odcs.yml")):
            if existing not in live:
                problems.append(
                    f"ORPHAN (on disk, no longer generated): {existing.relative_to(root).as_posix()}"
                )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Validate + fail if any on-disk contract drifted / was hand-edited (no writes).",
    )
    parser.add_argument(
        "--estate-root", type=Path, default=None,
        help="Estate root to emit contracts against (resolved from the environment or working directory when omitted).",
    )
    parser.add_argument(
        "--binding", type=Path, default=None,
        help="RuntimeBinding YAML file or directory for production Bronze ODCS projections.",
    )
    parser.add_argument(
        "--environment", default=None,
        help="Mandatory matching assertion against RuntimeBinding.environment.",
    )
    args = parser.parse_args()

    ctx = EstateContext.resolve(estate_root=args.estate_root)
    validator = load_schema_validator()
    files = generate(ctx)
    try:
        bronze_files = generate_bronze(ctx, binding_path=args.binding, environment=args.environment)
    except ValueError as error:
        print(f"FAIL: {error}")
        return 2

    schema_errors = validate_all(files, validator, ctx=ctx)
    bronze_schema_errors = validate_all(bronze_files, validator, ctx=ctx) if bronze_files else []
    schema_errors = schema_errors + bronze_schema_errors
    if schema_errors:
        print(f"ODCS schema-validation FAIL: {len(schema_errors)} error(s) against {SCHEMA_PATH.name}:")
        for err in schema_errors:
            print(f"  {err}")
        return 1
    print(
        f"ODCS schema-validation OK: {len(files)} served contract(s)"
        + (f" + {len(bronze_files)} bronze contract(s)" if bronze_files else "")
        + f" valid against {SCHEMA_PATH.name}"
    )

    if args.check:
        problems = check_files(files, ctx=ctx) + check_bronze_files(bronze_files, ctx=ctx)
        if problems:
            print(f"ODCS contract gate FAIL: {len(problems)} on-disk divergence(s):")
            for problem in problems:
                print(problem)
            return 1
        print(
            f"ODCS contract gate OK: {len(files)} on-disk served contract(s) byte-match"
            + (f" and {len(bronze_files)} bronze contract(s) byte-match" if bronze_files else "")
        )
        return 0

    changed = write_files(files, ctx=ctx)
    bronze_changed = write_bronze_files(bronze_files, ctx=ctx)
    print(f"generated/updated {len([p for p in changed if p in files])} of {len(files)} contract(s)")
    for path in sorted(changed):
        marker = "wrote" if path in files else "pruned"
        print(f"  {marker} {path.relative_to(ctx.root).as_posix()}")
    if bronze_files or bronze_changed:
        print(
            f"generated/updated {len([p for p in bronze_changed if p in bronze_files])} "
            f"of {len(bronze_files)} bronze contract(s)"
        )
        for path in sorted(bronze_changed):
            marker = "wrote" if path in bronze_files else "pruned"
            print(f"  {marker} {path.relative_to(ctx.root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
