"""Sync the engine's packaged scaffold data from its in-tree sources.

``ergasterion init`` resolves every asset it copies from ``ergasterion/scaffold/``,
package-relative, so a non-editable install finds them inside its own wheel.
The files under ``ergasterion/scaffold/`` are GENERATED artefacts of this engine
tree -- the same byte-stable discipline as ``contracts/`` and ``graphs/`` --
projected from the live sources by this tool:

  dbt_project.yml            <- derived from the estate's own committed
                                dbt_project.yml: the engine-generic structural
                                top only (estate-only blocks stripped)
  packages.yml               <- packages.yml, verbatim
  profiles.yml               <- profiles/profiles.yml, verbatim
  targets/<name>.yml         <- declarations/targets/<name>.yml, verbatim
  macros/<name>.sql          <- the engine-generic macro allow-set, verbatim

Edit the SOURCE (the estate file, the macros tree, the target declarations) and
re-run this tool; never edit ``ergasterion/scaffold/`` by hand. The offline
validation chain runs ``--check`` so a drifted or hand-edited scaffold fails
the lane. The tool is anchored on the engine SOURCE tree and is meaningful only
in a checkout; an installed wheel carries the synced result.

Usage:
    python ergasterion/sync_scaffold.py            # regenerate ergasterion/scaffold/
    python ergasterion/sync_scaffold.py --check    # fail (exit 1) on any drift
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

import yaml

if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion._repo_root import REPO_ROOT

SCAFFOLD_DIR = Path(__file__).resolve().parent / "scaffold"

GENERATED_NOTE = (
    "# Generated by `ergasterion init`: the engine-generic structural top only.\n"
    "# Add your own `models:` overrides as you introduce layers this estate doesn't have,\n"
    "# and a `seeds:` block once you add a domain -- seed `column_types` are authored\n"
    "# config with no generator (see GETTING-STARTED.md).\n"
)

# The project/profile name is fixed: macros/cross_db.sql dispatches every
# cross-adapter macro under this literal package name.
PROJECT_NAME = "ergasterion"

# Only macros needed by emitted, domain-neutral models belong in a new consumer estate.
# Worked-estate governance, investment calculations, and decision-log workflows remain in
# the source repository and are not copied by ``ergasterion init``.
SCAFFOLD_MACROS = (
    "automate_dv_duckdb.sql",
    "calculated_field.sql",
    "cross_db.sql",
    "entity_resolution_scoring.sql",
    "normalisation.sql",
    "survivorship.sql",
)

# Blocks the estate's own dbt_project.yml carries that are estate-specific:
# authored per-domain seed config, the estate's own append-only-log bootstrap
# hooks, and the estate's own domain-specific model-path leaf.
ESTATE_ONLY_TOP_KEYS = ("seeds", "on-run-start")
ESTATE_ONLY_MODEL_LEAVES = ("deal_approvals",)


def derive_dbt_project_top() -> str:
    """The scaffold's dbt_project.yml, derived from the estate's committed file
    (the live SSOT) with the estate-only blocks stripped, so the structural top
    a consumer starts from carries exactly the engine-generic layer config the
    emitters write into."""
    raw = yaml.safe_load((REPO_ROOT / "dbt_project.yml").read_text(encoding="utf-8"))
    for key in ESTATE_ONLY_TOP_KEYS:
        raw.pop(key, None)
    models_block = (raw.get("models") or {}).get(PROJECT_NAME)
    if isinstance(models_block, dict):
        for leaf in ESTATE_ONLY_MODEL_LEAVES:
            models_block.pop(leaf, None)
    body = yaml.safe_dump(raw, sort_keys=False, default_flow_style=False, width=100)
    return GENERATED_NOTE + "\n" + body


def generated_set() -> dict[Path, bytes]:
    """Every scaffold file as (path under ergasterion/scaffold/ -> exact bytes)."""
    files: dict[Path, bytes] = {
        Path("dbt_project.yml"): derive_dbt_project_top().encode("utf-8"),
        Path("packages.yml"): (REPO_ROOT / "packages.yml").read_bytes(),
        Path("profiles.yml"): (REPO_ROOT / "profiles" / "profiles.yml").read_bytes(),
    }
    for target_file in sorted((REPO_ROOT / "declarations" / "targets").glob("*.yml")):
        files[Path("targets") / target_file.name] = target_file.read_bytes()
    for name in SCAFFOLD_MACROS:
        macro_file = REPO_ROOT / "macros" / name
        if not macro_file.is_file():
            raise FileNotFoundError(f"required scaffold macro is missing: {macro_file}")
        files[Path("macros") / name] = macro_file.read_bytes()
    return files


def sync(check: bool = False) -> int:
    files = generated_set()
    drifted: list[str] = []

    for rel, content in sorted(files.items()):
        dest = SCAFFOLD_DIR / rel
        existing = dest.read_bytes() if dest.exists() else None
        if existing == content:
            continue
        drifted.append(rel.as_posix())
        if check:
            before = (existing or b"").decode("utf-8", errors="replace").splitlines()
            after = content.decode("utf-8", errors="replace").splitlines()
            print("\n".join(difflib.unified_diff(before, after, fromfile=str(dest), tofile=str(dest))))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(content)

    orphans: list[str] = []
    if SCAFFOLD_DIR.is_dir():
        expected = {SCAFFOLD_DIR / rel for rel in files}
        for path in sorted(SCAFFOLD_DIR.rglob("*")):
            if path.is_file() and path not in expected:
                orphans.append(path.relative_to(SCAFFOLD_DIR).as_posix())
                if not check:
                    path.unlink()

    action = "would change" if check else "synced"
    print(f"{action} {len(drifted)} of {len(files)} scaffold file(s)")
    for name in drifted:
        print(f"  {name}")
    print(f"SCAFFOLD_ORPHANS={len(orphans)}")
    for name in orphans:
        print(f"  orphan: {name}")

    if check and (drifted or orphans):
        print(
            "scaffold-sync FAIL: ergasterion/scaffold/ does not match its sources -- "
            "edit the source and run `python ergasterion/sync_scaffold.py`"
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on drift; write nothing.")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
