"""Sync the engine's packaged scaffold data from its in-tree sources.

``ergasterion init`` resolves every asset it copies from ``ergasterion/scaffold/``,
package-relative, so a non-editable install finds them inside its own wheel.
The files under ``ergasterion/scaffold/`` are GENERATED artefacts of this engine
tree -- the same byte-stable discipline as ``contracts/`` and ``graphs/`` --
projected from the live sources by this tool:

  dbt_project.yml            <- derived from the estate's own committed
                                dbt_project.yml: the engine-generic structural
                                top only (estate-only blocks stripped), with
                                target-path/log-path/packages-install-path/
                                clean-targets fixed under runtime/data/dbt/
  packages.yml               <- packages.yml, verbatim
  profiles.yml                <- derived from profiles/profiles.yml: the DuckDB
                                target's default path fixed at
                                runtime/data/ergasterion.duckdb
  targets/<name>.yml         <- declarations/targets/<name>.yml, verbatim
  macros/<name>.sql          <- the engine-generic macro allow-set, verbatim
  runtime/local.yml          <- derived: a real RuntimeBinding for the one
                                reference example (source=reference,
                                table=orders) GETTING-STARTED.md walks through --
                                all nine local ports, one parallel attempt, the
                                deterministic resource envelope, computed (never
                                hand-typed) contract/execution-plan digests
  .gitignore                 <- derived: ignores only runtime/data/, never the
                                binding itself
  estate.yml                  <- derived: a placeholder estate namespace
                                matching the reference example above

Edit the SOURCE (the estate file, the macros tree, the target declarations) and
re-run this tool; never edit ``ergasterion/scaffold/`` by hand. The offline
validation chain runs ``--check`` so a drifted or hand-edited scaffold fails
the lane. The tool is anchored on the engine SOURCE tree and is meaningful only
in a checkout; an installed wheel carries the synced result.

Usage:
    python ergasterion/sync_scaffold.py            # regenerate ergasterion/scaffold/
    python ergasterion/sync_scaffold.py --check    # fail (exit 1) on any drift
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
from typing import Any

import yaml

if __package__ in (None, ""):
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

from ergasterion._repo_root import REPO_ROOT
from ergasterion.framework.bronze_contract import (
    BackoffKind,
    BronzeProductContract,
    ContentEncoding,
    DeleteStrategy,
    DeliveryMode,
    DeliveryPolicy,
    IntervalSchedule,
    JsonlCodec,
    LandingContract,
    LogicalIdentity,
    ManagedIntegration,
    NewlineKind,
    NotNullRule,
    OpaqueBatchProgress,
    ProductFacts,
    ProjectionField,
    QualityPolicy,
    RecordKeyContract,
    RetryPolicy,
    SimpleLogicalType,
    SlaContract,
    SourceField,
    TimestampContract,
)
from ergasterion.framework.models import Layer, compute_plan_digest
from ergasterion.framework.resolver import resolve
from ergasterion.ingestion.reference_runtime import contract_digest as runtime_contract_digest
from ergasterion.source_delivery import derive_interfaces
from ergasterion.translators.local_ingestion import build_local_binding

SCAFFOLD_DIR = Path(__file__).resolve().parent / "scaffold"

# The one worked example GETTING-STARTED.md walks a reader through end to end, and the
# identity `ergasterion/scaffold/runtime/local.yml`'s binding is computed against --
# never a real product; the placeholder namespace matches `estate.yml`'s own so the
# shipped scaffold is internally consistent out of the box.
REFERENCE_NAMESPACE = "com.example.ergasterion"
REFERENCE_SOURCE = "reference"
REFERENCE_TABLE = "orders"

RUNTIME_BINDING_NOTE = (
    "# Generated by `ergasterion init`. This binding is computed for the ONE reference\n"
    "# example GETTING-STARTED.md walks through (source=reference, table=orders) -- once\n"
    "# you author your own Bronze product contract, `ergasterion plan`/`contract register`\n"
    "# report its real contract_digest; copy that value (and logical_identity) in here.\n"
    "# The nine port bindings, scheduler, outbox, runtime_resources and retention stay --\n"
    "# they are the closed local reference profile, not product-specific.\n"
)

SCAFFOLD_GITIGNORE = (
    "# The runtime data root (SQLite, DuckDB, raw objects/receipts, scratch, dbt's own\n"
    "# target/logs/packages) -- never the binding above it. See runtime/local.yml.\n"
    "runtime/data/\n"
)

SCAFFOLD_ESTATE_YML = (
    "# The target-neutral estate root. `estate.namespace` is the mandatory production\n"
    "# qualifier for every Bronze Product Contract's globally qualified identity\n"
    "# (estate_namespace, source.name, tables.<key>). Replace this placeholder with your\n"
    "# own reverse-DNS-style namespace before authoring a production contract -- a\n"
    "# seed-only estate never reads this file (ergasterion.source_delivery's\n"
    "# load_estate_namespace() only matters once a table's landing.kind is 'source').\n"
    "# See docs/specifications/bronze-product-v1.md.\n"
    "estate:\n"
    f"  namespace: {REFERENCE_NAMESPACE}\n"
)

GENERATED_NOTE = (
    "# Generated by `ergasterion init`: the engine-generic structural top only.\n"
    "# Add your own `models:` overrides as you introduce layers this estate doesn't have,\n"
    "# and a `seeds:` block once you add a domain -- seed `column_types` are authored\n"
    "# config with no generator (see GETTING-STARTED.md).\n"
)

# The project/profile name is fixed: macros/cross_db.sql dispatches every
# cross-adapter macro under this literal package name.
PROJECT_NAME = "ergasterion"

# Only macros needed by emitted, domain-neutral models belong in a new consumer estate.
# Worked-estate governance, investment calculations, and decision-log workflows remain in
# the source repository and are not copied by ``ergasterion init``.
SCAFFOLD_MACROS = (
    "automate_dv_duckdb.sql",
    "automate_dv_snowflake.sql",
    "calculated_field.sql",
    "cross_db.sql",
    "entity_resolution_scoring.sql",
    "estate_evolution.sql",
    "normalisation.sql",
    "source_delivery.sql",
    "survivorship.sql",
)

# Blocks the estate's own dbt_project.yml carries that are estate-specific:
# authored per-domain seed config, the estate's own append-only-log bootstrap
# hooks, and the estate's own domain-specific model-path leaf.
ESTATE_ONLY_TOP_KEYS = ("seeds", "on-run-start")
ESTATE_ONLY_MODEL_LEAVES = ("deal_approvals",)

# The scaffold's own runtime data root (ergasterion/scaffold/.gitignore ignores it, never
# the tracked runtime/local.yml binding beside it). Every dbt working-directory path a
# scaffolded estate's commands touch is fixed under here, so partial-parse state, dbt's
# own logs and DPF_DBT_PACKAGE_CACHE-materialised Hub packages never land at the estate
# root or leak outside this one ignored directory.
RUNTIME_TARGET_PATH = "runtime/data/dbt/target"
RUNTIME_LOG_PATH = "runtime/data/dbt/logs"
RUNTIME_PACKAGES_PATH = "runtime/data/dbt/packages"
RUNTIME_DUCKDB_DEFAULT = "runtime/data/ergasterion.duckdb"
_ENGINE_DUCKDB_DEFAULT = "target/ergasterion.duckdb"


def derive_dbt_project_top() -> str:
    """The scaffold's dbt_project.yml, derived from the estate's committed file
    (the live SSOT) with the estate-only blocks stripped and every dbt working-directory
    path fixed under the tracked runtime/local.yml binding's data root, so a consumer
    starts from exactly the engine-generic layer config the emitters write into."""
    raw = yaml.safe_load((REPO_ROOT / "dbt_project.yml").read_text(encoding="utf-8"))
    for key in ESTATE_ONLY_TOP_KEYS:
        raw.pop(key, None)
    models_block = (raw.get("models") or {}).get(PROJECT_NAME)
    if isinstance(models_block, dict):
        for leaf in ESTATE_ONLY_MODEL_LEAVES:
            models_block.pop(leaf, None)
    if "target-path" not in raw:
        raise ValueError("dbt_project.yml: expected an existing 'target-path' key to override")
    raw["target-path"] = RUNTIME_TARGET_PATH
    raw["clean-targets"] = [RUNTIME_TARGET_PATH, RUNTIME_PACKAGES_PATH, RUNTIME_LOG_PATH]
    ordered: dict[str, Any] = {}
    for key, value in raw.items():
        ordered[key] = value
        if key == "target-path":
            ordered["log-path"] = RUNTIME_LOG_PATH
            ordered["packages-install-path"] = RUNTIME_PACKAGES_PATH
    body = yaml.safe_dump(ordered, sort_keys=False, default_flow_style=False, width=100)
    return GENERATED_NOTE + "\n" + body


def derive_scaffold_profiles() -> bytes:
    """The scaffold's profiles.yml, derived from the engine's own committed
    profiles/profiles.yml with the DuckDB target's default path repointed at
    runtime/data/ergasterion.duckdb (still DPF_DUCKDB_PATH-overridable) -- everything
    else (BigQuery/Snowflake targets, every comment) is byte-identical."""
    text = (REPO_ROOT / "profiles" / "profiles.yml").read_text(encoding="utf-8")
    old = f"'{_ENGINE_DUCKDB_DEFAULT}'"
    new = f"'{RUNTIME_DUCKDB_DEFAULT}'"
    if old not in text:
        raise ValueError(
            f"profiles/profiles.yml: expected the DuckDB default path {old} to override"
        )
    return text.replace(old, new, 1).encode("utf-8")


def _omit_nulls(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _omit_nulls(item) for key, item in value.items() if item is not None}
    if isinstance(value, list):
        return [_omit_nulls(item) for item in value]
    return value


def reference_contract() -> BronzeProductContract:
    """The one worked reference example: a small, valid, production-classed Bronze
    Product Contract (append-only, opaque_batch progress, no deletes) that
    ``ergasterion/scaffold/runtime/local.yml``'s binding is computed against and that
    GETTING-STARTED.md walks a reader through end to end. Never a real product -- every
    field is a documented placeholder."""
    return BronzeProductContract(
        schema="ergasterion.bronze-product/v1",
        logical_identity=LogicalIdentity(
            estate_namespace=REFERENCE_NAMESPACE, source=REFERENCE_SOURCE, table=REFERENCE_TABLE,
        ),
        product=ProductFacts(
            product_version="1.0.0",
            display_name="Reference orders",
            description="Scaffold walkthrough example -- replace with your own source before production use.",
            owner="local-process-user",
            domain="reference",
            support="local-process-user",
            classification="synthetic",
            access_policy_ref="local-process-user",
            retention_policy_ref="local-ephemeral",
        ),
        landing=LandingContract(
            kind="source",
            source_name=REFERENCE_SOURCE,
            identifier=REFERENCE_TABLE,
            integration=ManagedIntegration(kind="managed"),
            content_encodings=(ContentEncoding.IDENTITY,),
            codec=JsonlCodec(
                kind="jsonl", version=1, charset="utf-8", newline=NewlineKind.LF,
                top_level="object", duplicate_keys="reject", number_mode="exact_decimal",
                allow_blank_lines=False,
            ),
            physical_columns=(
                SourceField(name="order_id", logical_type=SimpleLogicalType.UTF8_STRING, nullable=False),
                SourceField(name="loaded_at", logical_type=SimpleLogicalType.UTC_INSTANT, nullable=False),
            ),
        ),
        delivery=DeliveryPolicy(
            kind="production",
            mode=DeliveryMode.APPEND_ONLY,
            progress=OpaqueBatchProgress(kind="opaque_batch"),
            delete_strategy=DeleteStrategy.NONE,
            schedule=IntervalSchedule(kind="interval", every_minutes=60, anchor_at="2026-01-01T00:00:00.000000Z"),
            schedule_lateness=SlaContract(warn_after_minutes=15, error_after_minutes=60),
            timestamps=TimestampContract(load_field="loaded_at"),
            record_key=RecordKeyContract(fields=("order_id",)),
            quality=QualityPolicy(
                publication_mode="publish_valid_rows", max_error_fraction="0.01",
                rules=(NotNullRule(kind="not_null", field="order_id", severity="error"),),
            ),
            retry=RetryPolicy(max_attempts=4, backoff=BackoffKind.EXPONENTIAL, base_seconds=5, cap_seconds=300),
        ),
        projection=(
            ProjectionField(source="order_id", name="order_id", logical_type=SimpleLogicalType.UTF8_STRING, nullable=False),
            ProjectionField(source="loaded_at", name="loaded_at", logical_type=SimpleLogicalType.UTC_INSTANT, nullable=False),
        ),
        interfaces=derive_interfaces(REFERENCE_SOURCE, REFERENCE_TABLE),
    )


def derive_runtime_local_binding() -> bytes:
    """``ergasterion/scaffold/runtime/local.yml``: a real, valid ``RuntimeBinding`` for
    ``reference_contract()``, computed through the same local-ingestion translator and
    contract-digest functions the runtime itself uses -- never a hand-typed digest.

    The binding's ``contract_digest`` field is compared, at ingest time, against
    ``ergasterion.ingestion.reference_runtime.contract_digest()`` (a plain
    ``canonical_digest(contract.model_dump(...))``) -- a DIFFERENT function from
    ``ergasterion.source_delivery.compute_contract_digest()`` (which wraps the same
    canonicalisation in a ``{schema, contract}`` envelope for the contract compiler's own
    derived-digest family). Using the wrong one here would make every `ingest file`
    against the shipped binding fail closed with `superseded_contract` on a byte-identical
    contract -- so this module reads the runtime's own function, never the compiler's."""
    contract = reference_contract()
    plan = resolve(Layer.BRONZE)
    binding = build_local_binding(
        contract,
        execution_plan_digest=compute_plan_digest(plan),
        contract_digest=runtime_contract_digest(contract),
        binding_id="scaffold-reference",
    )
    document = _omit_nulls(binding.model_dump(mode="json", by_alias=True))
    body = yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=100)
    return (RUNTIME_BINDING_NOTE + "\n" + body).encode("utf-8")


def generated_set() -> dict[Path, bytes]:
    """Every scaffold file as (path under ergasterion/scaffold/ -> exact bytes)."""
    files: dict[Path, bytes] = {
        Path("dbt_project.yml"): derive_dbt_project_top().encode("utf-8"),
        Path("packages.yml"): (REPO_ROOT / "packages.yml").read_bytes(),
        Path("profiles.yml"): derive_scaffold_profiles(),
        Path("runtime/local.yml"): derive_runtime_local_binding(),
        Path(".gitignore"): SCAFFOLD_GITIGNORE.encode("utf-8"),
        Path("estate.yml"): SCAFFOLD_ESTATE_YML.encode("utf-8"),
    }
    for target_file in sorted((REPO_ROOT / "declarations" / "targets").glob("*.yml")):
        files[Path("targets") / target_file.name] = target_file.read_bytes()
    for name in SCAFFOLD_MACROS:
        macro_file = REPO_ROOT / "macros" / name
        if not macro_file.is_file():
            raise FileNotFoundError(f"required scaffold macro is missing: {macro_file}")
        files[Path("macros") / name] = macro_file.read_bytes()
    return files


def sync(check: bool = False) -> int:
    files = generated_set()
    drifted: list[str] = []

    for rel, content in sorted(files.items()):
        dest = SCAFFOLD_DIR / rel
        existing = dest.read_bytes() if dest.exists() else None
        if existing == content:
            continue
        drifted.append(rel.as_posix())
        if check:
            before = (existing or b"").decode("utf-8", errors="replace").splitlines()
            after = content.decode("utf-8", errors="replace").splitlines()
            print("\n".join(difflib.unified_diff(before, after, fromfile=str(dest), tofile=str(dest))))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(content)

    orphans: list[str] = []
    if SCAFFOLD_DIR.is_dir():
        expected = {SCAFFOLD_DIR / rel for rel in files}
        for path in sorted(SCAFFOLD_DIR.rglob("*")):
            if path.is_file() and path not in expected:
                orphans.append(path.relative_to(SCAFFOLD_DIR).as_posix())
                if not check:
                    path.unlink()

    action = "would change" if check else "synced"
    print(f"{action} {len(drifted)} of {len(files)} scaffold file(s)")
    for name in drifted:
        print(f"  {name}")
    print(f"SCAFFOLD_ORPHANS={len(orphans)}")
    for name in orphans:
        print(f"  orphan: {name}")

    if check and (drifted or orphans):
        print(
            "scaffold-sync FAIL: ergasterion/scaffold/ does not match its sources -- "
            "edit the source and run `python ergasterion/sync_scaffold.py`"
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on drift; write nothing.")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
