-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        customer_status,
        customer_business_key,
        customer_email_domain,
        customer_record_id,
        customer_source_id,
        customer_source_system,
        customer_loyalty_id,
        customer_email,
        customer_normalised_email,
        customer_name,
        customer_phone,
        customer_address_line,
        customer_city,
        customer_postal_code,
        customer_country,
        customer_marketing_consent,
        customer_preferred_channel,
        customer_buyer_segment,
        customer_as_of_date,
        customer_identity_key,
        customer_external_id
    from {{ ref("ecommerce__customer") }}
),
step_00_batch_transfer as (
    select
        customer_status,
        customer_business_key,
        customer_email_domain,
        customer_record_id,
        customer_source_id,
        customer_source_system,
        customer_loyalty_id,
        customer_email,
        customer_normalised_email,
        customer_name,
        customer_phone,
        customer_address_line,
        customer_city,
        customer_postal_code,
        customer_country,
        customer_marketing_consent,
        customer_preferred_channel,
        customer_buyer_segment,
        customer_as_of_date,
        customer_identity_key,
        customer_external_id
    from source_00
)

select
    customer_status,
    customer_business_key,
    customer_email_domain,
    customer_record_id,
    customer_source_id,
    customer_source_system,
    customer_loyalty_id,
    customer_email,
    customer_normalised_email,
    customer_name,
    customer_phone,
    customer_address_line,
    customer_city,
    customer_postal_code,
    customer_country,
    customer_marketing_consent,
    customer_preferred_channel,
    customer_buyer_segment,
    customer_as_of_date,
    customer_identity_key,
    customer_external_id,
    coalesce(customer_business_key is null, true) as violation_00
from step_00_batch_transfer
