-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
customer_contact_source as (
    select
        customer_business_key,
        customer_email,
        customer_email_domain,
        customer_phone,
        customer_address_line,
        customer_city,
        customer_postal_code,
        customer_country
    from {{ ref("ecommerce__customer_interface__base") }}
)

select
    cast(customer_business_key as {{ dpf_type('string') }}) as customer_business_key,
    cast(customer_email as {{ dpf_type('string') }}) as customer_email,
    cast(customer_email_domain as {{ dpf_type('string') }}) as customer_email_domain,
    cast(customer_phone as {{ dpf_type('string') }}) as customer_phone,
    cast(customer_address_line as {{ dpf_type('string') }}) as customer_address_line,
    cast(customer_city as {{ dpf_type('string') }}) as customer_city,
    cast(customer_postal_code as {{ dpf_type('string') }}) as customer_postal_code,
    cast(customer_country as {{ dpf_type('string') }}) as customer_country
from customer_contact_source
