-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        product_name,
        product_status,
        product_code,
        product_record_id,
        product_source_id,
        product_source_system,
        product_brand,
        product_category,
        product_list_price,
        product_currency,
        product_as_of_date
    from {{ ref("ecommerce__product") }}
),
step_00_batch_transfer as (
    select
        product_name,
        product_status,
        product_code,
        product_record_id,
        product_source_id,
        product_source_system,
        product_brand,
        product_category,
        product_list_price,
        product_currency,
        product_as_of_date
    from source_00
)

select
    product_name,
    product_status,
    product_code,
    product_record_id,
    product_source_id,
    product_source_system,
    product_brand,
    product_category,
    product_list_price,
    product_currency,
    product_as_of_date,
    coalesce(product_code is null, true) as violation_00
from step_00_batch_transfer
