-- Generated by ergasterion/emit_graph.py from declarations/domains SSOT. Regenerated, never hand-edited. Do not edit by hand.

CREATE TABLE ecommerce_nodes (
  id VARCHAR PRIMARY KEY,
  name VARCHAR,
  domain VARCHAR,
  hash_key VARCHAR,
  golden_key VARCHAR
);

CREATE TABLE ecommerce_edges (
  edge_id VARCHAR,
  src VARCHAR,
  dst VARCHAR,
  rel_type VARCHAR,
  cardinality VARCHAR,
  kind VARCHAR,
  inverse VARCHAR,
  source_key VARCHAR,
  target_key VARCHAR,
  source_column VARCHAR,
  discriminator_value VARCHAR,
  link VARCHAR,
  properties VARCHAR,
  PRIMARY KEY (edge_id),
  FOREIGN KEY (src) REFERENCES ecommerce_nodes (id),
  FOREIGN KEY (dst) REFERENCES ecommerce_nodes (id)
);

COPY ecommerce_nodes (id, name, domain, hash_key, golden_key) FROM 'ecommerce-nodes.csv' WITH (FORMAT csv, HEADER true);
COPY ecommerce_edges (edge_id, src, dst, rel_type, cardinality, kind, inverse, source_key, target_key, source_column, discriminator_value, link, properties) FROM 'ecommerce-edges.csv' WITH (FORMAT csv, HEADER true);

CREATE PROPERTY GRAPH ecommerce_graph
  NODE TABLES (
    ecommerce_nodes
      KEY (id)
      LABEL Entity PROPERTIES (id, name, domain, hash_key, golden_key)
  )
  EDGE TABLES (
    ecommerce_edges
      KEY (edge_id)
      SOURCE KEY (src) REFERENCES ecommerce_nodes (id)
      DESTINATION KEY (dst) REFERENCES ecommerce_nodes (id)
      LABEL Relationship PROPERTIES (edge_id, src, dst, rel_type, cardinality, kind, inverse, source_key, target_key, source_column, discriminator_value, link, properties)
  );
