-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_vantora_succession_events') }}
)

select
    'vantora' as source_system,
    cast(succession_event_id as string) as succession_event_id,
    cast(predecessor_gp_id as string) as predecessor_source_gp_id,
    cast(successor_gp_id as string) as successor_source_gp_id,
    cast(event_type as string) as event_type,
    {{ dpf_safe_cast('effective_date', 'date') }} as effective_date
from source
