-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_meridex_portfolio_companies') }}
)

select
    'meridex' as source_system,
    cast(meridex_company_id as string) as source_company_id,
    cast(meridex_fund_id as string) as source_fund_id,
    cast(company_name as string) as company_name,
    {{ blank_to_null('company_lei') }} as lei,
    {{ blank_to_null('shared_external_id') }} as shared_external_id,
    cast(sector as string) as sector,
    cast(country as string) as country
from source
