-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_cartivo_orders') }}
)

select
    'cartivo' as source_system,
    cast(cartivo_record_id as string) as source_record_id,
    cast(cartivo_order_id as string) as source_order_id,
    cast(cartivo_customer_id as string) as source_customer_id,
    {{ dpf_safe_cast('order_date', 'date') }} as order_date,
    cast(order_status as string) as order_status,
    cast(currency as string) as currency,
    {{ dpf_safe_cast('order_total', 'numeric') }} as order_total,
    cast(channel as string) as channel
from source
