-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_vantora_valuations') }}
)

select
    'vantora' as source_system,
    cast(valuation_id as string) as valuation_id,
    cast(vantora_fund_id as string) as source_fund_id,
    cast(vantora_company_id as string) as source_company_id,
    {{ dpf_safe_cast('valuation_date', 'date') }} as valuation_date,
    {{ dpf_safe_cast('value_usd', 'numeric') }} as value_usd,
    cast(method as string) as method,
    cast(valuation_level as string) as valuation_level,
    {{ dpf_safe_cast('confidence_score', 'float') }} as confidence_score
from source
