-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_meridex_legal_vehicles') }}
)

select
    'meridex' as source_system,
    cast(vehicle_id as string) as vehicle_natural_id,
    cast(meridex_fund_id as string) as source_fund_id,
    {{ blank_to_null('parent_vehicle_id') }} as parent_vehicle_id,
    cast(vehicle_name as string) as vehicle_name,
    cast(vehicle_type as string) as vehicle_type,
    cast(jurisdiction as string) as jurisdiction,
    {{ dpf_safe_cast('incorporation_date', 'date') }} as incorporation_date,
    {{ blank_to_null('vehicle_lei') }} as lei
from source
