-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_cartivo_customers') }}
)

select
    'cartivo' as source_system,
    cast(cartivo_record_id as string) as source_record_id,
    cast(cartivo_customer_id as string) as source_customer_id,
    {{ blank_to_null('loyalty_id') }} as loyalty_id,
    cast(email as string) as email,
    cast(full_name as string) as full_name,
    {{ blank_to_null('phone') }} as phone,
    {{ blank_to_null('address_line') }} as address_line,
    {{ blank_to_null('city') }} as city,
    {{ blank_to_null('postal_code') }} as postal_code,
    {{ blank_to_null('country') }} as country,
    {{ blank_to_null('marketing_consent') }} as marketing_consent,
    {{ blank_to_null('preferred_channel') }} as preferred_channel,
    cast(null as string) as buyer_segment,
    cast(customer_status as string) as customer_status,
    {{ dpf_safe_cast('as_of_date', 'date') }} as as_of_date
from source
