-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_chrono_valuations') }}
)

select
    'chrono' as source_system,
    cast(mark_uid as string) as valuation_id,
    cast(vehicle_code as string) as source_fund_id,
    cast(asset_uid as string) as source_company_id,
    {{ dpf_safe_cast('mark_date', 'date') }} as valuation_date,
    {{ dpf_safe_cast('usd_fair_value', 'numeric') }} as value_usd,
    cast(mark_method as string) as method,
    cast(fair_value_bucket as string) as valuation_level,
    {{ dpf_safe_cast('extraction_confidence', 'float') }} as confidence_score
from source
