-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_vantora_cash_flows') }}
)

select
    'vantora' as source_system,
    cast(cash_flow_id as string) as cash_flow_id,
    cast(vantora_fund_id as string) as source_fund_id,
    {{ dpf_safe_cast('cash_flow_date', 'date') }} as cash_flow_date,
    cast(cash_flow_type as string) as cash_flow_type,
    cast(direction as string) as direction,
    {{ dpf_safe_cast('amount_usd', 'numeric') }} as amount_usd,
    cast(currency as string) as currency
from source
