-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_mercaro_products') }}
)

select
    'mercaro' as source_system,
    cast(mercaro_record_id as string) as source_record_id,
    cast(mercaro_product_id as string) as source_product_id,
    cast(shared_product_code as string) as shared_product_code,
    cast(product_name as string) as product_name,
    cast(brand as string) as brand,
    cast(category as string) as category,
    {{ dpf_safe_cast('list_price', 'numeric') }} as list_price,
    cast(currency as string) as currency,
    cast(product_status as string) as product_status,
    {{ dpf_safe_cast('as_of_date', 'date') }} as as_of_date
from source
