-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_chrono_funds') }}
)

select
    'chrono' as source_system,
    cast(chrono_row_uid as string) as source_record_id,
    cast(chrono_vehicle_code as string) as source_fund_id,
    cast(vehicle_display_name as string) as fund_name,
    cast(vehicle_group_name as string) as fund_family_name,
    cast(vehicle_form as string) as vehicle_type,
    cast(manager_master_code as string) as source_gp_id,
    cast(manager_name_text as string) as gp_name,
    {{ blank_to_null('manager_lei') }} as gp_lei,
    {{ blank_to_null('legal_entity_identifier') }} as lei,
    {{ blank_to_null('vendor_crosswalk_id') }} as shared_external_id,
    cast(private_market_bucket as string) as asset_class,
    cast(investment_style as string) as strategy,
    {{ dpf_safe_cast('launch_year', 'int') }} as vintage_year,
    {{ dpf_safe_cast('commitment_amount_usd', 'numeric') }} as committed_capital_usd,
    cast(reporting_ccy as string) as currency,
    cast(domicile_iso2 as string) as domicile,
    cast(lifecycle_state as string) as fund_status,
    {{ dpf_safe_cast('snapshot_date', 'date') }} as as_of_date
from source
