-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('raw_chrono_cash_flows') }}
)

select
    'chrono' as source_system,
    cast(event_uid as string) as cash_flow_id,
    cast(vehicle_code as string) as source_fund_id,
    {{ dpf_safe_cast('event_date', 'date') }} as cash_flow_date,
    cast(event_kind as string) as cash_flow_type,
    cast(investor_direction as string) as direction,
    {{ dpf_safe_cast('usd_amount', 'numeric') }} as amount_usd,
    cast(currency_code as string) as currency
from source
