-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        relatio_record_id,
        relatio_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        customer_status,
        as_of_date
    from {{ ref("ecommerce__relatio_customer_extract") }}
),
step_00_batch_transfer as (
    select
        relatio_record_id,
        relatio_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        customer_status,
        as_of_date
    from source_00
)

select
    relatio_record_id,
    relatio_customer_id,
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    customer_status,
    as_of_date,
    coalesce(relatio_record_id is null, true) as violation_00,
    coalesce(email is null, true) as violation_01
from step_00_batch_transfer
