-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        cartivo_record_id,
        cartivo_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        as_of_date,
        violation_00,
        violation_01
    from {{ ref("ecommerce__cartivo_customer_extract__checked") }}
),
violations as (
    select
        'cartivo_record_id_not_null' as rule_name,
        cartivo_record_id,
        cartivo_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        as_of_date
    from quarantined
    where violation_00

    union all

    select
        'cartivo_record_id_unique' as rule_name,
        cartivo_record_id,
        cartivo_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        as_of_date
    from quarantined
    where violation_01
)

select
    rule_name,
    cartivo_record_id,
    cartivo_customer_id,
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    marketing_consent,
    preferred_channel,
    customer_status,
    as_of_date
from violations
