-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        product_name,
        brand,
        category,
        currency,
        product_status,
        source_record_id,
        source_product_id,
        product_code,
        list_price,
        as_of_date,
        source_system,
        violation_00,
        violation_01
    from {{ ref("ecommerce__product__checked_pre") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        product_name,
        brand,
        category,
        currency,
        product_status,
        source_record_id,
        source_product_id,
        product_code,
        list_price,
        as_of_date,
        source_system
    from quarantined
    where violation_00

    union all

    select
        'product_code_not_null' as rule_name,
        product_name,
        brand,
        category,
        currency,
        product_status,
        source_record_id,
        source_product_id,
        product_code,
        list_price,
        as_of_date,
        source_system
    from quarantined
    where violation_01
)

select
    rule_name,
    product_name,
    brand,
    category,
    currency,
    product_status,
    source_record_id,
    source_product_id,
    product_code,
    list_price,
    as_of_date,
    source_system
from violations
