-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_post_input as (
    select
        product_name,
        product_status,
        product_code,
        product_record_id,
        product_source_id,
        product_source_system,
        product_brand,
        product_category,
        product_list_price,
        product_currency,
        product_as_of_date
    from {{ ref("ecommerce__product__checked_post") }}
)

select
    product_name,
    product_status,
    product_code,
    product_record_id,
    product_source_id,
    product_source_system,
    product_brand,
    product_category,
    product_list_price,
    product_currency,
    product_as_of_date
from checked_post_input
