-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (order_status = 'fulfilled') as predicate_00
    from {{ ref("ecommerce__order_star__prefilter") }}
),
counted as (
    select
        'fulfilled_lines_only' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
