-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

select
    cast({{ dpf_publish_timestamp() }} as {{ dpf_type('timestamp') }}) as published_at,
    cast(count(*) as {{ dpf_type('int') }}) as row_count
from {{ ref("ecommerce__relatio_customer") }}
