-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
resolution_input as (
    select
        customer_status,
        customer_business_key,
        customer_email_domain,
        customer_record_id,
        customer_source_id,
        customer_source_system,
        customer_loyalty_id,
        customer_email,
        customer_normalised_email,
        customer_name,
        customer_phone,
        customer_address_line,
        customer_city,
        customer_postal_code,
        customer_country,
        customer_marketing_consent,
        customer_preferred_channel,
        customer_buyer_segment,
        customer_as_of_date,
        customer_identity_key,
        customer_external_id,
        resolution_record_key,
        resolution_entity_key
    from {{ ref("ecommerce__customer__resolution") }}
),
survivorship_customer_status as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_status as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_status is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_status
    where pick_rank = 1
),
survivorship_customer_business_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_business_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_business_key is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_business_key
    where pick_rank = 1
),
survivorship_customer_email_domain as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_email_domain as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_email_domain is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_email_domain
    where pick_rank = 1
),
survivorship_customer_record_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_record_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_record_id is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_record_id
    where pick_rank = 1
),
survivorship_customer_source_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_source_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_source_id is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_source_id
    where pick_rank = 1
),
survivorship_customer_source_system as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_source_system as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_source_system is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_source_system
    where pick_rank = 1
),
survivorship_customer_loyalty_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_loyalty_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_loyalty_id is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_loyalty_id
    where pick_rank = 1
),
survivorship_customer_email as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_email as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_email is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_email
    where pick_rank = 1
),
survivorship_customer_normalised_email as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_normalised_email as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_normalised_email is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_normalised_email
    where pick_rank = 1
),
survivorship_customer_name as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_name as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_name is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_name
    where pick_rank = 1
),
survivorship_customer_phone as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_phone as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_phone is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_phone
    where pick_rank = 1
),
survivorship_customer_address_line as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_address_line as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_address_line is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_address_line
    where pick_rank = 1
),
survivorship_customer_city as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_city as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_city is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_city
    where pick_rank = 1
),
survivorship_customer_postal_code as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_postal_code as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_postal_code is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_postal_code
    where pick_rank = 1
),
survivorship_customer_country as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_country as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_country is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_country
    where pick_rank = 1
),
survivorship_customer_marketing_consent as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_marketing_consent as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_marketing_consent is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_marketing_consent
    where pick_rank = 1
),
survivorship_customer_preferred_channel as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_preferred_channel as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_preferred_channel is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_preferred_channel
    where pick_rank = 1
),
survivorship_customer_buyer_segment as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_buyer_segment as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_buyer_segment is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_buyer_segment
    where pick_rank = 1
),
survivorship_customer_as_of_date as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_as_of_date as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_as_of_date is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_as_of_date
    where pick_rank = 1
),
survivorship_customer_identity_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_identity_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_identity_key is null then 1 else 0 end, customer_as_of_date desc, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_identity_key
    where pick_rank = 1
),
survivorship_customer_external_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            customer_external_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when customer_external_id is null then 1 else 0 end, case when customer_source_system = 'relatio' then 1 when customer_source_system = 'cartivo' then 2 when customer_source_system = 'mercaro' then 3 else 4 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_customer_external_id
    where pick_rank = 1
),
curation_entities as (
    select distinct
        resolution_entity_key
    from resolution_input
),
curation_survivor as (
    select
        survivorship_customer_status.attribute_value as customer_status,
        survivorship_customer_business_key.attribute_value as customer_business_key,
        survivorship_customer_email_domain.attribute_value as customer_email_domain,
        survivorship_customer_record_id.attribute_value as customer_record_id,
        survivorship_customer_source_id.attribute_value as customer_source_id,
        survivorship_customer_source_system.attribute_value as customer_source_system,
        survivorship_customer_loyalty_id.attribute_value as customer_loyalty_id,
        survivorship_customer_email.attribute_value as customer_email,
        survivorship_customer_normalised_email.attribute_value as customer_normalised_email,
        survivorship_customer_name.attribute_value as customer_name,
        survivorship_customer_phone.attribute_value as customer_phone,
        survivorship_customer_address_line.attribute_value as customer_address_line,
        survivorship_customer_city.attribute_value as customer_city,
        survivorship_customer_postal_code.attribute_value as customer_postal_code,
        survivorship_customer_country.attribute_value as customer_country,
        survivorship_customer_marketing_consent.attribute_value as customer_marketing_consent,
        survivorship_customer_preferred_channel.attribute_value as customer_preferred_channel,
        survivorship_customer_buyer_segment.attribute_value as customer_buyer_segment,
        survivorship_customer_as_of_date.attribute_value as customer_as_of_date,
        survivorship_customer_identity_key.attribute_value as customer_identity_key,
        survivorship_customer_external_id.attribute_value as customer_external_id
    from curation_entities as entities
    left join survivorship_customer_status
        on survivorship_customer_status.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_business_key
        on survivorship_customer_business_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_email_domain
        on survivorship_customer_email_domain.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_record_id
        on survivorship_customer_record_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_source_id
        on survivorship_customer_source_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_source_system
        on survivorship_customer_source_system.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_loyalty_id
        on survivorship_customer_loyalty_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_email
        on survivorship_customer_email.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_normalised_email
        on survivorship_customer_normalised_email.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_name
        on survivorship_customer_name.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_phone
        on survivorship_customer_phone.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_address_line
        on survivorship_customer_address_line.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_city
        on survivorship_customer_city.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_postal_code
        on survivorship_customer_postal_code.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_country
        on survivorship_customer_country.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_marketing_consent
        on survivorship_customer_marketing_consent.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_preferred_channel
        on survivorship_customer_preferred_channel.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_buyer_segment
        on survivorship_customer_buyer_segment.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_as_of_date
        on survivorship_customer_as_of_date.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_identity_key
        on survivorship_customer_identity_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_customer_external_id
        on survivorship_customer_external_id.resolution_entity_key = entities.resolution_entity_key
)

select
    customer_status,
    customer_business_key,
    customer_email_domain,
    customer_record_id,
    customer_source_id,
    customer_source_system,
    customer_loyalty_id,
    customer_email,
    customer_normalised_email,
    customer_name,
    customer_phone,
    customer_address_line,
    customer_city,
    customer_postal_code,
    customer_country,
    customer_marketing_consent,
    customer_preferred_channel,
    customer_buyer_segment,
    customer_as_of_date,
    customer_identity_key,
    customer_external_id,
    coalesce(customer_business_key is not null and count(*) over (partition by customer_business_key) > 1, true) as violation_00,
    coalesce(customer_external_id is null, true) as violation_01
from curation_survivor
