-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        mercaro_record_id,
        mercaro_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date,
        violation_00,
        violation_01
    from {{ ref("ecommerce__mercaro_product__checked") }}
),
violations as (
    select
        'mercaro_record_id_not_null' as rule_name,
        mercaro_record_id,
        mercaro_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date
    from quarantined
    where violation_00

    union all

    select
        'shared_product_code_not_null' as rule_name,
        mercaro_record_id,
        mercaro_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date
    from quarantined
    where violation_01
)

select
    rule_name,
    mercaro_record_id,
    mercaro_product_id,
    shared_product_code,
    product_name,
    brand,
    category,
    list_price,
    currency,
    product_status,
    as_of_date
from violations
