-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        cartivo_record_id,
        cartivo_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        as_of_date
    from {{ ref("ecommerce__cartivo_customer__checked") }}
),
step_02_schema_transform as (
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        cast(cartivo_record_id as {{ dpf_type('string') }}) as source_record_id,
        cast(cartivo_customer_id as {{ dpf_type('string') }}) as source_customer_id,
        cast(as_of_date as {{ dpf_type('date') }}) as as_of_date
    from checked_input
),
step_03_calculated_fields as (
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        cast(('cartivo') as {{ dpf_type('string') }}) as source_system,
        cast((nullif(lower(trim(email)), '')) as {{ dpf_type('string') }}) as normalised_email,
        cast((coalesce(nullif(loyalty_id, ''), nullif(lower(trim(email)), ''))) as {{ dpf_type('string') }}) as customer_business_key,
        cast(({{ dpf_crm_email_domain("email") }}) as {{ dpf_type('string') }}) as customer_email_domain,
        cast((null) as {{ dpf_type('string') }}) as buyer_segment
    from step_02_schema_transform
)

select
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    marketing_consent,
    preferred_channel,
    customer_status,
    source_record_id,
    source_customer_id,
    as_of_date,
    source_system,
    normalised_email,
    customer_business_key,
    customer_email_domain,
    buyer_segment
from step_03_calculated_fields
