-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date,
        violation_00,
        violation_01
    from {{ ref("ecommerce__mercaro_order_line__checked") }}
),
violations as (
    select
        'mercaro_record_id_not_null' as rule_name,
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from quarantined
    where violation_00

    union all

    select
        'mercaro_order_id_not_null' as rule_name,
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from quarantined
    where violation_01
)

select
    rule_name,
    mercaro_record_id,
    mercaro_order_id,
    mercaro_product_id,
    line_number,
    quantity,
    unit_price,
    line_revenue,
    currency,
    order_date
from violations
