-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from {{ ref("ecommerce__mercaro_order_line_extract") }}
),
step_00_batch_transfer as (
    select
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from source_00
)

select
    mercaro_record_id,
    mercaro_order_id,
    mercaro_product_id,
    line_number,
    quantity,
    unit_price,
    line_revenue,
    currency,
    order_date,
    coalesce(mercaro_record_id is null, true) as violation_00,
    coalesce(mercaro_order_id is null, true) as violation_01
from step_00_batch_transfer
