-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        cartivo_record_id,
        cartivo_order_id,
        cartivo_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from {{ ref("ecommerce__cartivo_order_line_extract__checked") }}
)

select
    cartivo_record_id,
    cartivo_order_id,
    cartivo_product_id,
    line_number,
    quantity,
    unit_price,
    line_revenue,
    currency,
    order_date
from checked_input
