-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        relatio_record_id,
        relatio_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        customer_status,
        as_of_date,
        violation_00,
        violation_01
    from {{ ref("ecommerce__relatio_customer__checked") }}
),
violations as (
    select
        'relatio_record_id_not_null' as rule_name,
        relatio_record_id,
        relatio_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        customer_status,
        as_of_date
    from quarantined
    where violation_00

    union all

    select
        'email_not_null' as rule_name,
        relatio_record_id,
        relatio_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        customer_status,
        as_of_date
    from quarantined
    where violation_01
)

select
    rule_name,
    relatio_record_id,
    relatio_customer_id,
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    customer_status,
    as_of_date
from violations
