-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        cartivo_record_id,
        cartivo_order_id,
        cartivo_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from {{ ref("ecommerce__cartivo_order_line_extract") }}
),
step_00_batch_transfer as (
    select
        cartivo_record_id,
        cartivo_order_id,
        cartivo_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from source_00
)

select
    cartivo_record_id,
    cartivo_order_id,
    cartivo_product_id,
    line_number,
    quantity,
    unit_price,
    line_revenue,
    currency,
    order_date,
    coalesce(cartivo_record_id is null, true) as violation_00,
    coalesce(cartivo_order_id is null, true) as violation_01
from step_00_batch_transfer
