-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
dim_customer_segment_source as (
    select distinct
        customer_business_key,
        segment_name,
        line_order_date
    from {{ ref("ecommerce__order_star__base") }}
),
dim_customer_segment_marked as (
    select
        customer_business_key,
        segment_name,
        line_order_date,
        case
            when row_number() over (partition by customer_business_key order by line_order_date) = 1 then 1
            when segment_name is distinct from lag(segment_name) over (partition by customer_business_key order by line_order_date) then 1
            else 0
        end as dpf_version_start
    from dim_customer_segment_source
),
dim_customer_segment_numbered as (
    select
        customer_business_key,
        segment_name,
        line_order_date,
        sum(dpf_version_start) over (partition by customer_business_key order by line_order_date rows between unbounded preceding and current row) as dpf_version_number
    from dim_customer_segment_marked
),
dim_customer_segment_collapsed as (
    select
        customer_business_key,
        segment_name,
        dpf_version_number,
        min(line_order_date) as effective_from
    from dim_customer_segment_numbered
    group by customer_business_key, segment_name, dpf_version_number
),
dim_customer_segment_ranged as (
    select
        customer_business_key,
        segment_name,
        effective_from,
        lead(effective_from) over (partition by customer_business_key order by effective_from) as effective_to
    from dim_customer_segment_collapsed
)

select
    cast(customer_business_key as {{ dpf_type('string') }}) as customer_business_key,
    cast(segment_name as {{ dpf_type('string') }}) as segment_name,
    cast(effective_from as {{ dpf_type('date') }}) as effective_from,
    cast(effective_to as {{ dpf_type('date') }}) as effective_to
from dim_customer_segment_ranged
