-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from {{ ref("ecommerce__cartivo_customer") }}
    union all
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from {{ ref("ecommerce__mercaro_customer") }}
    union all
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from {{ ref("ecommerce__relatio_customer") }}
),
step_00_batch_transfer as (
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from source_00
)

select
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    marketing_consent,
    preferred_channel,
    customer_status,
    source_record_id,
    source_customer_id,
    as_of_date,
    source_system,
    normalised_email,
    customer_business_key,
    customer_email_domain,
    buyer_segment,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(customer_business_key is null, true) as violation_01
from step_00_batch_transfer
