-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        coalesce(merged_00.product_code, merged_01.product_code) as product_code,
        merged_00.order_line_record_id as order_line_record_id,
        merged_00.order_id as order_id,
        merged_00.order_line_source_product_id as order_line_source_product_id,
        merged_00.line_number as line_number,
        merged_00.line_quantity as line_quantity,
        merged_00.line_unit_price as line_unit_price,
        merged_00.line_revenue as line_revenue,
        merged_00.line_currency as line_currency,
        merged_00.line_order_date as line_order_date,
        merged_00.order_line_source_system as order_line_source_system,
        merged_01.product_name as product_name,
        merged_01.product_status as product_status,
        merged_01.product_record_id as product_record_id,
        merged_01.product_source_id as product_source_id,
        merged_01.product_source_system as product_source_system,
        merged_01.product_brand as product_brand,
        merged_01.product_category as product_category,
        merged_01.product_list_price as product_list_price,
        merged_01.product_currency as product_currency,
        merged_01.product_as_of_date as product_as_of_date
    from {{ ref("ecommerce__order_line") }} as merged_00
    full join {{ ref("ecommerce__product") }} as merged_01
        on merged_00.product_code = merged_01.product_code
),
step_00_batch_transfer as (
    select
        product_code,
        order_line_record_id,
        order_id,
        order_line_source_product_id,
        line_number,
        line_quantity,
        line_unit_price,
        line_revenue,
        line_currency,
        line_order_date,
        order_line_source_system,
        product_name,
        product_status,
        product_record_id,
        product_source_id,
        product_source_system,
        product_brand,
        product_category,
        product_list_price,
        product_currency,
        product_as_of_date
    from source_00
)

select
    product_code,
    order_line_record_id,
    order_id,
    order_line_source_product_id,
    line_number,
    line_quantity,
    line_unit_price,
    line_revenue,
    line_currency,
    line_order_date,
    order_line_source_system,
    product_name,
    product_status,
    product_record_id,
    product_source_id,
    product_source_system,
    product_brand,
    product_category,
    product_list_price,
    product_currency,
    product_as_of_date,
    coalesce(product_code is null, true) as violation_00
from step_00_batch_transfer
