-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment,
        violation_00,
        violation_01
    from {{ ref("ecommerce__customer__checked_pre") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from quarantined
    where violation_00

    union all

    select
        'customer_business_key_not_null' as rule_name,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        source_record_id,
        source_customer_id,
        as_of_date,
        source_system,
        normalised_email,
        customer_business_key,
        customer_email_domain,
        buyer_segment
    from quarantined
    where violation_01
)

select
    rule_name,
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    marketing_consent,
    preferred_channel,
    customer_status,
    source_record_id,
    source_customer_id,
    as_of_date,
    source_system,
    normalised_email,
    customer_business_key,
    customer_email_domain,
    buyer_segment
from violations
