-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        mercaro_record_id,
        mercaro_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date
    from {{ ref("ecommerce__mercaro_product__checked") }}
),
step_02_schema_transform as (
    select
        product_name,
        brand,
        category,
        currency,
        product_status,
        cast(mercaro_record_id as {{ dpf_type('string') }}) as source_record_id,
        cast(mercaro_product_id as {{ dpf_type('string') }}) as source_product_id,
        cast(shared_product_code as {{ dpf_type('string') }}) as product_code,
        cast(list_price as {{ dpf_decimal_type(12, 2) }}) as list_price,
        cast(as_of_date as {{ dpf_type('date') }}) as as_of_date
    from checked_input
),
step_03_calculated_fields as (
    select
        product_name,
        brand,
        category,
        currency,
        product_status,
        source_record_id,
        source_product_id,
        product_code,
        list_price,
        as_of_date,
        cast(('mercaro') as {{ dpf_type('string') }}) as source_system
    from step_02_schema_transform
)

select
    product_name,
    brand,
    category,
    currency,
    product_status,
    source_record_id,
    source_product_id,
    product_code,
    list_price,
    as_of_date,
    source_system
from step_03_calculated_fields
