-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        cartivo_record_id,
        cartivo_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date
    from {{ ref("ecommerce__cartivo_product_extract__checked") }}
)

select
    cartivo_record_id,
    cartivo_product_id,
    shared_product_code,
    product_name,
    brand,
    category,
    list_price,
    currency,
    product_status,
    as_of_date
from checked_input
