-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        mercaro_record_id,
        mercaro_order_id,
        mercaro_product_id,
        line_number,
        quantity,
        unit_price,
        line_revenue,
        currency,
        order_date
    from {{ ref("raw_mercaro_order_lines") }}
)

select
    mercaro_record_id,
    mercaro_order_id,
    mercaro_product_id,
    line_number,
    quantity,
    unit_price,
    line_revenue,
    currency,
    order_date,
    coalesce(mercaro_record_id is null, true) as violation_00,
    coalesce(mercaro_record_id is not null and count(*) over (partition by mercaro_record_id) > 1, true) as violation_01
from source_00
