-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        mercaro_record_id,
        mercaro_product_id,
        shared_product_code,
        product_name,
        brand,
        category,
        list_price,
        currency,
        product_status,
        as_of_date
    from {{ ref("raw_mercaro_products") }}
)

select
    mercaro_record_id,
    mercaro_product_id,
    shared_product_code,
    product_name,
    brand,
    category,
    list_price,
    currency,
    product_status,
    as_of_date,
    coalesce(mercaro_record_id is null, true) as violation_00,
    coalesce(mercaro_record_id is not null and count(*) over (partition by mercaro_record_id) > 1, true) as violation_01
from source_00
