-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        cartivo_record_id,
        cartivo_customer_id,
        loyalty_id,
        email,
        full_name,
        phone,
        address_line,
        city,
        postal_code,
        country,
        marketing_consent,
        preferred_channel,
        customer_status,
        as_of_date
    from {{ ref("raw_cartivo_customers") }}
)

select
    cartivo_record_id,
    cartivo_customer_id,
    loyalty_id,
    email,
    full_name,
    phone,
    address_line,
    city,
    postal_code,
    country,
    marketing_consent,
    preferred_channel,
    customer_status,
    as_of_date,
    coalesce(cartivo_record_id is null, true) as violation_00,
    coalesce(cartivo_record_id is not null and count(*) over (partition by cartivo_record_id) > 1, true) as violation_01
from source_00
