-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = ['stg_dv_vantora_portfolio_companies',
 'stg_dv_vantora_valuations',
 'stg_dv_meridex_portfolio_companies',
 'stg_dv_portiq_portfolio_companies',
 'stg_dv_chrono_portfolio_companies',
 'stg_dv_chrono_valuations'] -%}
{%- set src_pk = 'fund_portfolio_company_lhk' -%}
{%- set src_fk = ['fund_hk', 'portfolio_company_hk'] -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.link(
    src_pk=src_pk,
    src_fk=src_fk,
    src_extra_columns=none,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
