-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = ['stg_dv_vantora_legal_vehicles', 'stg_dv_meridex_legal_vehicles'] -%}
{%- set src_pk = 'investment_vehicle_lhk' -%}
{%- set src_fk = ['fund_hk', 'legal_vehicle_hk'] -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.link(
    src_pk=src_pk,
    src_fk=src_fk,
    src_extra_columns=none,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
