-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = ['stg_dv_cartivo_orders', 'stg_dv_mercaro_orders'] -%}
{%- set src_pk = 'order_customer_lhk' -%}
{%- set src_fk = ['order_hk', 'customer_hk'] -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.link(
    src_pk=src_pk,
    src_fk=src_fk,
    src_extra_columns=none,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
