-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date,
        violation_00,
        violation_01,
        violation_02,
        violation_03
    from {{ ref("investment__vantora_succession_event_extract__checked") }}
),
violations as (
    select
        'succession_event_id_not_null' as rule_name,
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date
    from quarantined
    where violation_00

    union all

    select
        'succession_event_id_unique' as rule_name,
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date
    from quarantined
    where violation_01

    union all

    select
        'predecessor_gp_id_not_null' as rule_name,
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date
    from quarantined
    where violation_02

    union all

    select
        'successor_gp_id_not_null' as rule_name,
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date
    from quarantined
    where violation_03
)

select
    rule_name,
    succession_event_id,
    predecessor_gp_id,
    successor_gp_id,
    event_type,
    effective_date
from violations
