-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        source_record_id,
        source_fund_id,
        source_company_id,
        source_valued_on,
        source_value_usd,
        source_method,
        source_valuation_level,
        source_confidence_score,
        valuation_source_system
    from {{ ref("investment__chrono_valuation") }}
    union all
    select
        source_record_id,
        source_fund_id,
        source_company_id,
        source_valued_on,
        source_value_usd,
        source_method,
        source_valuation_level,
        source_confidence_score,
        valuation_source_system
    from {{ ref("investment__vantora_valuation") }}
),
step_00_batch_transfer as (
    select
        source_record_id,
        source_fund_id,
        source_company_id,
        source_valued_on,
        source_value_usd,
        source_method,
        source_valuation_level,
        source_confidence_score,
        valuation_source_system
    from source_00
)

select
    source_record_id,
    source_fund_id,
    source_company_id,
    source_valued_on,
    source_value_usd,
    source_method,
    source_valuation_level,
    source_confidence_score,
    valuation_source_system,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(source_valued_on is null, true) as violation_01
from step_00_batch_transfer
