-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence,
        violation_00,
        violation_01
    from {{ ref("investment__chrono_valuation__checked") }}
),
violations as (
    select
        'mark_uid_not_null' as rule_name,
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence
    from quarantined
    where violation_00

    union all

    select
        'mark_date_not_null' as rule_name,
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence
    from quarantined
    where violation_01
)

select
    rule_name,
    mark_uid,
    vehicle_code,
    asset_uid,
    mark_date,
    usd_fair_value,
    mark_method,
    fair_value_bucket,
    extraction_confidence
from violations
