-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
prefilter_input as (
    select
        decision_id,
        deal_external_identity,
        decision_outcome,
        decision_conditions,
        decision_actor,
        decision_decided_at,
        decision_rank,
        decision_is_final
    from {{ ref("investment__deal_decision_current__prefilter") }}
),
step_04_data_filtering as (
    select
        decision_id,
        deal_external_identity,
        decision_outcome,
        decision_conditions,
        decision_actor,
        decision_decided_at,
        decision_rank,
        decision_is_final
    from prefilter_input
    where (decision_rank = 1)
)

select
    decision_id,
    deal_external_identity,
    decision_outcome,
    decision_conditions,
    decision_actor,
    decision_decided_at,
    decision_rank,
    decision_is_final
from step_04_data_filtering
