-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        chrono_row_uid,
        chrono_vehicle_code,
        vehicle_display_name,
        vehicle_group_name,
        vehicle_form,
        manager_master_code,
        manager_name_text,
        manager_lei,
        legal_entity_identifier,
        vendor_crosswalk_id,
        private_market_bucket,
        investment_style,
        launch_year,
        commitment_amount_usd,
        reporting_ccy,
        domicile_iso2,
        lifecycle_state,
        snapshot_date
    from {{ ref("investment__chrono_gp__checked") }}
),
step_02_schema_transform as (
    select
        cast(chrono_row_uid as {{ dpf_type('string') }}) as source_record_id,
        cast(manager_master_code as {{ dpf_type('string') }}) as source_gp_id,
        cast(manager_name_text as {{ dpf_type('string') }}) as source_name,
        cast(manager_lei as {{ dpf_type('string') }}) as source_lei,
        cast(domicile_iso2 as {{ dpf_type('string') }}) as source_domicile,
        cast(snapshot_date as {{ dpf_type('date') }}) as source_reported_on
    from checked_input
),
step_03_calculated_fields as (
    select
        source_record_id,
        source_gp_id,
        source_name,
        source_lei,
        source_domicile,
        source_reported_on,
        cast((null) as {{ dpf_type('string') }}) as source_external_id,
        cast((null) as {{ dpf_type('date') }}) as source_relationship_start_date,
        cast(('chrono') as {{ dpf_type('string') }}) as gp_source_system,
        cast((concat('chrono', ':', source_record_id)) as {{ dpf_type('string') }}) as gp_identity_key,
        cast(({{ dpf_investment_normalised_name("source_name") }}) as {{ dpf_type('string') }}) as gp_normalised_name,
        cast((nullif(trim(source_lei), '')) as {{ dpf_type('string') }}) as gp_lei,
        cast((null) as {{ dpf_type('string') }}) as gp_external_id
    from step_02_schema_transform
)

select
    source_record_id,
    source_gp_id,
    source_name,
    source_lei,
    source_domicile,
    source_reported_on,
    source_external_id,
    source_relationship_start_date,
    gp_source_system,
    gp_identity_key,
    gp_normalised_name,
    gp_lei,
    gp_external_id
from step_03_calculated_fields
