-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(
    materialized='incremental',
    incremental_strategy=dpf_incremental_strategy({"bigquery": "merge", "duckdb": "delete+insert"}),
    unique_key=["gp_hk", "effective_from", "hashdiff_basis_version"]
) }}

with
sat_gp_detail_source as (
    select distinct
        gp_business_key,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        gp_source_id,
        gp_reported_on
    from {{ ref("investment__gp_vault__base") }}
    where gp_business_key is not null
),
sat_gp_detail_fingerprinted as (
    select
        {{ dpf_vault_hash(["gp_business_key"]) }} as gp_hk,
        {{ dpf_vault_hash(["gp_name", "gp_domicile", "gp_relationship_start_on", "gp_lei"]) }} as hashdiff,
        1 as hashdiff_basis_version,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        gp_source_id,
        gp_reported_on as effective_from,
        {{ dpf_publish_timestamp() }} as load_datetime,
        'investment.gp_vault' as record_source
    from sat_gp_detail_source
),
sat_gp_detail_unstored as (
    select
        gp_hk,
        hashdiff,
        hashdiff_basis_version,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        gp_source_id,
        effective_from,
        load_datetime,
        record_source
    from sat_gp_detail_fingerprinted
    where {{ dpf_vault_new_versions("sat_gp_detail_fingerprinted", "gp_hk", "hashdiff", "effective_from", "hashdiff_basis_version", "current") }}
)

select
    cast(gp_hk as {{ dpf_type('string') }}) as gp_hk,
    cast(hashdiff as {{ dpf_type('string') }}) as hashdiff,
    cast(hashdiff_basis_version as {{ dpf_type('int') }}) as hashdiff_basis_version,
    cast(gp_name as {{ dpf_type('string') }}) as gp_name,
    cast(gp_domicile as {{ dpf_type('string') }}) as gp_domicile,
    cast(gp_relationship_start_on as {{ dpf_type('date') }}) as gp_relationship_start_on,
    cast(gp_lei as {{ dpf_type('string') }}) as gp_lei,
    cast(gp_source_id as {{ dpf_type('string') }}) as gp_source_id,
    cast(effective_from as {{ dpf_type('date') }}) as effective_from,
    cast(load_datetime as {{ dpf_type('timestamp') }}) as load_datetime,
    cast(record_source as {{ dpf_type('string') }}) as record_source
from sat_gp_detail_unstored
