-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        vehicle_id,
        vantora_fund_id,
        parent_vehicle_id,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        vehicle_lei,
        violation_00,
        violation_01,
        violation_02
    from {{ ref("investment__vantora_legal_vehicle_extract__checked") }}
),
violations as (
    select
        'vehicle_id_not_null' as rule_name,
        vehicle_id,
        vantora_fund_id,
        parent_vehicle_id,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        vehicle_lei
    from quarantined
    where violation_00

    union all

    select
        'vehicle_id_unique' as rule_name,
        vehicle_id,
        vantora_fund_id,
        parent_vehicle_id,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        vehicle_lei
    from quarantined
    where violation_01

    union all

    select
        'vehicle_name_not_null' as rule_name,
        vehicle_id,
        vantora_fund_id,
        parent_vehicle_id,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        vehicle_lei
    from quarantined
    where violation_02
)

select
    rule_name,
    vehicle_id,
    vantora_fund_id,
    parent_vehicle_id,
    vehicle_name,
    vehicle_type,
    jurisdiction,
    incorporation_date,
    vehicle_lei
from violations
