-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_record_id,
        source_external_deal_id,
        source_name,
        source_target_entity_id,
        source_strategy,
        source_originating_team,
        source_channel,
        source_sourced_on,
        source_structure,
        source_converted_record_type,
        source_converted_record_id,
        deal_source_system,
        deal_identity_key,
        deal_normalised_name,
        deal_external_id
    from {{ ref("investment__deal_conformed__checked") }}
),
step_02_calculated_fields as (
    select
        source_record_id,
        source_external_deal_id,
        source_name,
        source_target_entity_id,
        source_strategy,
        source_originating_team,
        source_channel,
        source_sourced_on,
        source_structure,
        source_converted_record_type,
        source_converted_record_id,
        deal_source_system,
        deal_identity_key,
        deal_normalised_name,
        deal_external_id,
        cast((coalesce(deal_external_id, deal_identity_key)) as {{ dpf_type('string') }}) as deal_business_key,
        cast((nullif(trim(source_target_entity_id), '')) as {{ dpf_type('string') }}) as deal_target_company_external_id,
        cast((case when source_converted_record_type = 'fund_investment' then nullif(trim(source_converted_record_id), '') end) as {{ dpf_type('string') }}) as deal_converted_fund_external_id,
        cast((upper(trim(nullif(trim(source_target_entity_id), '')))) as {{ dpf_type('string') }}) as deal_target_company_lookup_key,
        cast((case when source_converted_record_type = 'fund_investment' then upper(trim(nullif(trim(source_converted_record_id), ''))) end) as {{ dpf_type('string') }}) as deal_converted_fund_lookup_key
    from checked_input
),
step_03_data_enrichment as (
    select
        base.source_record_id,
        base.source_external_deal_id,
        base.source_name,
        base.source_target_entity_id,
        base.source_strategy,
        base.source_originating_team,
        base.source_channel,
        base.source_sourced_on,
        base.source_structure,
        base.source_converted_record_type,
        base.source_converted_record_id,
        base.deal_source_system,
        base.deal_identity_key,
        base.deal_normalised_name,
        base.deal_external_id,
        base.deal_business_key,
        base.deal_target_company_external_id,
        base.deal_converted_fund_external_id,
        base.deal_target_company_lookup_key,
        base.deal_converted_fund_lookup_key,
        lookup_0.company_business_key,
        lookup_1.fund_business_key
    from step_02_calculated_fields as base
    left join {{ ref("investment__company_external_index") }} as lookup_0
        on base.deal_target_company_lookup_key = lookup_0.company_external_lookup_key
    left join {{ ref("investment__fund_external_index") }} as lookup_1
        on base.deal_converted_fund_lookup_key = lookup_1.fund_external_lookup_key
)

select
    source_record_id,
    source_external_deal_id,
    source_name,
    source_target_entity_id,
    source_strategy,
    source_originating_team,
    source_channel,
    source_sourced_on,
    source_structure,
    source_converted_record_type,
    source_converted_record_id,
    deal_source_system,
    deal_identity_key,
    deal_normalised_name,
    deal_external_id,
    deal_business_key,
    deal_target_company_external_id,
    deal_converted_fund_external_id,
    deal_target_company_lookup_key,
    deal_converted_fund_lookup_key,
    company_business_key,
    fund_business_key
from step_03_data_enrichment
