-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id,
        violation_00,
        violation_01,
        violation_02,
        violation_03
    from {{ ref("investment__origo_deal_extract__checked") }}
),
violations as (
    select
        'deal_id_not_null' as rule_name,
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from quarantined
    where violation_00

    union all

    select
        'deal_id_unique' as rule_name,
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from quarantined
    where violation_01

    union all

    select
        'deal_name_not_null' as rule_name,
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from quarantined
    where violation_02

    union all

    select
        'sourced_date_not_null' as rule_name,
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from quarantined
    where violation_03
)

select
    rule_name,
    deal_id,
    external_deal_id,
    deal_name,
    target_entity_id,
    strategy,
    originating_team,
    source_channel,
    sourced_date,
    structure,
    converted_record_type,
    converted_record_id
from violations
