-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
pending_records as (
    select
        resolution_record_key
    from {{ ref("investment__gp_vault__resolution") }}
    where resolution_pending
),
banded_pairs as (
    select
        resolution_record_key as record_key_a,
        cast(null as {{ dpf_type('string') }}) as record_key_b,
        cast(null as {{ dpf_type('numeric') }}) as match_score,
        'unresolved' as review_band
    from pending_records
)

select
    record_key_a,
    record_key_b,
    match_score,
    review_band
from banded_pairs
