-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        fund_source_system,
        fund_identity_key,
        fund_normalised_name,
        fund_normalised_gp_name,
        fund_lei,
        fund_external_id,
        fund_gp_lei,
        fund_business_key,
        fund_record_id,
        fund_source_id,
        fund_name,
        fund_family_name,
        fund_vehicle_type,
        fund_gp_source_id,
        fund_gp_name,
        fund_asset_class,
        fund_strategy,
        fund_vintage_year,
        fund_committed_capital_usd,
        fund_currency,
        fund_domicile,
        fund_status,
        fund_reported_on,
        fund_gp_business_key,
        fund_external_identity,
        violation_00,
        violation_01
    from {{ ref("investment__fund_vault__checked_post") }}
),
violations as (
    select
        'fund_business_key_not_null' as rule_name,
        fund_source_system,
        fund_identity_key,
        fund_normalised_name,
        fund_normalised_gp_name,
        fund_lei,
        fund_external_id,
        fund_gp_lei,
        fund_business_key,
        fund_record_id,
        fund_source_id,
        fund_name,
        fund_family_name,
        fund_vehicle_type,
        fund_gp_source_id,
        fund_gp_name,
        fund_asset_class,
        fund_strategy,
        fund_vintage_year,
        fund_committed_capital_usd,
        fund_currency,
        fund_domicile,
        fund_status,
        fund_reported_on,
        fund_gp_business_key,
        fund_external_identity
    from quarantined
    where violation_00

    union all

    select
        'fund_business_key_unique' as rule_name,
        fund_source_system,
        fund_identity_key,
        fund_normalised_name,
        fund_normalised_gp_name,
        fund_lei,
        fund_external_id,
        fund_gp_lei,
        fund_business_key,
        fund_record_id,
        fund_source_id,
        fund_name,
        fund_family_name,
        fund_vehicle_type,
        fund_gp_source_id,
        fund_gp_name,
        fund_asset_class,
        fund_strategy,
        fund_vintage_year,
        fund_committed_capital_usd,
        fund_currency,
        fund_domicile,
        fund_status,
        fund_reported_on,
        fund_gp_business_key,
        fund_external_identity
    from quarantined
    where violation_01
)

select
    rule_name,
    fund_source_system,
    fund_identity_key,
    fund_normalised_name,
    fund_normalised_gp_name,
    fund_lei,
    fund_external_id,
    fund_gp_lei,
    fund_business_key,
    fund_record_id,
    fund_source_id,
    fund_name,
    fund_family_name,
    fund_vehicle_type,
    fund_gp_source_id,
    fund_gp_name,
    fund_asset_class,
    fund_strategy,
    fund_vintage_year,
    fund_committed_capital_usd,
    fund_currency,
    fund_domicile,
    fund_status,
    fund_reported_on,
    fund_gp_business_key,
    fund_external_identity
from violations
