-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
golden_gp_hub as (
    select
        gp_hk,
        gp_business_key,
        load_datetime,
        record_source
    from {{ ref("investment__gp_vault__hub_gp") }}
),
golden_gp_gp_detail_ranked as (
    select
        gp_hk,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        effective_from,
        row_number() over (partition by gp_hk order by hashdiff_basis_version desc, effective_from desc) as dpf_version_rank
    from {{ ref("investment__gp_vault__sat_gp_detail") }}
),
golden_gp_gp_detail_current as (
    select
        gp_hk,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        effective_from
    from golden_gp_gp_detail_ranked
    where dpf_version_rank = 1
),
golden_gp_gp_name_candidates as (
    select
        gp_hk,
        gp_name as dpf_value,
        effective_from,
        1 as dpf_source_priority
    from golden_gp_gp_detail_current
    where gp_name is not null
),
golden_gp_gp_name_ranked as (
    select
        gp_hk,
        dpf_value,
        row_number() over (partition by gp_hk order by effective_from desc, dpf_source_priority asc) as dpf_version_rank
    from golden_gp_gp_name_candidates
),
golden_gp_gp_name as (
    select
        gp_hk,
        dpf_value
    from golden_gp_gp_name_ranked
    where dpf_version_rank = 1
),
golden_gp_gp_domicile_candidates as (
    select
        gp_hk,
        gp_domicile as dpf_value,
        effective_from,
        1 as dpf_source_priority
    from golden_gp_gp_detail_current
    where gp_domicile is not null
),
golden_gp_gp_domicile_ranked as (
    select
        gp_hk,
        dpf_value,
        row_number() over (partition by gp_hk order by dpf_source_priority asc, effective_from desc) as dpf_version_rank
    from golden_gp_gp_domicile_candidates
),
golden_gp_gp_domicile as (
    select
        gp_hk,
        dpf_value
    from golden_gp_gp_domicile_ranked
    where dpf_version_rank = 1
),
golden_gp_gp_relationship_start_on_candidates as (
    select
        gp_hk,
        gp_relationship_start_on as dpf_value,
        effective_from,
        1 as dpf_source_priority
    from golden_gp_gp_detail_current
    where gp_relationship_start_on is not null
),
golden_gp_gp_relationship_start_on_ranked as (
    select
        gp_hk,
        dpf_value,
        row_number() over (partition by gp_hk order by dpf_source_priority asc, effective_from desc) as dpf_version_rank
    from golden_gp_gp_relationship_start_on_candidates
),
golden_gp_gp_relationship_start_on as (
    select
        gp_hk,
        dpf_value
    from golden_gp_gp_relationship_start_on_ranked
    where dpf_version_rank = 1
),
golden_gp_gp_lei_candidates as (
    select
        gp_hk,
        gp_lei as dpf_value,
        effective_from,
        1 as dpf_source_priority
    from golden_gp_gp_detail_current
    where gp_lei is not null
),
golden_gp_gp_lei_ranked as (
    select
        gp_hk,
        dpf_value,
        row_number() over (partition by gp_hk order by dpf_source_priority asc, effective_from desc) as dpf_version_rank
    from golden_gp_gp_lei_candidates
),
golden_gp_gp_lei as (
    select
        gp_hk,
        dpf_value
    from golden_gp_gp_lei_ranked
    where dpf_version_rank = 1
),
golden_gp_joined as (
    select
        golden_gp_hub.gp_hk as gp_hk,
        golden_gp_hub.gp_business_key as gp_business_key,
        golden_gp_gp_name.dpf_value as gp_name,
        golden_gp_gp_domicile.dpf_value as gp_domicile,
        golden_gp_gp_relationship_start_on.dpf_value as gp_relationship_start_on,
        golden_gp_gp_lei.dpf_value as gp_lei,
        golden_gp_hub.load_datetime as load_datetime,
        golden_gp_hub.record_source as record_source
    from golden_gp_hub
    left join golden_gp_gp_name
        on golden_gp_gp_name.gp_hk = golden_gp_hub.gp_hk
    left join golden_gp_gp_domicile
        on golden_gp_gp_domicile.gp_hk = golden_gp_hub.gp_hk
    left join golden_gp_gp_relationship_start_on
        on golden_gp_gp_relationship_start_on.gp_hk = golden_gp_hub.gp_hk
    left join golden_gp_gp_lei
        on golden_gp_gp_lei.gp_hk = golden_gp_hub.gp_hk
)

select
    cast(gp_hk as {{ dpf_type('string') }}) as gp_hk,
    cast(gp_business_key as {{ dpf_type('string') }}) as gp_business_key,
    cast(gp_name as {{ dpf_type('string') }}) as gp_name,
    cast(gp_domicile as {{ dpf_type('string') }}) as gp_domicile,
    cast(gp_relationship_start_on as {{ dpf_type('date') }}) as gp_relationship_start_on,
    cast(gp_lei as {{ dpf_type('string') }}) as gp_lei,
    cast(load_datetime as {{ dpf_type('timestamp') }}) as load_datetime,
    cast(record_source as {{ dpf_type('string') }}) as record_source
from golden_gp_joined
