-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(
    materialized='incremental',
    incremental_strategy=dpf_incremental_strategy({"bigquery": "merge", "duckdb": "delete+insert"}),
    unique_key=["fund_business_key", "calendar_year"]
) }}

with
prefilter_input as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis,
        fund_invested_capital_usd,
        fund_total_value_usd,
        fund_total_value_multiple,
        fund_clears_hurdle,
        fund_benchmark_id,
        calendar_year,
        calendar_quarter,
        calendar_quarter_label,
        calendar_is_quarter_end,
        benchmark_index_value,
        benchmark_label,
        fund_department_code
    from {{ ref("investment__fund_performance_summary__prefilter") }}
),
step_02_data_filtering as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis,
        fund_invested_capital_usd,
        fund_total_value_usd,
        fund_total_value_multiple,
        fund_clears_hurdle,
        fund_benchmark_id,
        calendar_year,
        calendar_quarter,
        calendar_quarter_label,
        calendar_is_quarter_end,
        benchmark_index_value,
        benchmark_label,
        fund_department_code
    from prefilter_input
    where (source_nav_usd is not null)
),
step_03_data_aggregation as (
    select
        fund_business_key,
        calendar_year,
        fund_external_id,
        source_name,
        source_strategy,
        cast((count(*)) as {{ dpf_type('int') }}) as fund_valuation_count,
        cast((max(source_nav_usd)) as {{ dpf_decimal_type(18, 2) }}) as fund_closing_nav_usd,
        cast((max(source_called_capital_usd)) as {{ dpf_decimal_type(18, 2) }}) as fund_called_capital_usd,
        cast((max(source_distributed_capital_usd)) as {{ dpf_decimal_type(18, 2) }}) as fund_distributed_capital_usd,
        cast((max(fund_invested_capital_usd)) as {{ dpf_decimal_type(18, 2) }}) as fund_invested_capital_usd,
        cast((max(fund_total_value_usd)) as {{ dpf_decimal_type(18, 2) }}) as fund_total_value_usd
    from step_02_data_filtering
    group by
        fund_business_key,
        calendar_year,
        fund_external_id,
        source_name,
        source_strategy
)

select
    fund_business_key,
    calendar_year,
    fund_external_id,
    source_name,
    source_strategy,
    fund_valuation_count,
    fund_closing_nav_usd,
    fund_called_capital_usd,
    fund_distributed_capital_usd,
    fund_invested_capital_usd,
    fund_total_value_usd
from step_03_data_aggregation
