-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
prefilter_input as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source,
        company_external_lookup_key
    from {{ ref("investment__company_external_index__prefilter") }}
),
step_03_data_filtering as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source,
        company_external_lookup_key
    from prefilter_input
    where (company_external_lookup_key is not null)
),
step_04_data_aggregation as (
    select
        company_external_lookup_key,
        cast((min(company_business_key)) as {{ dpf_type('string') }}) as company_business_key,
        cast((count(distinct company_business_key)) as {{ dpf_type('int') }}) as company_entity_count
    from step_03_data_filtering
    group by
        company_external_lookup_key
)

select
    company_external_lookup_key,
    company_business_key,
    company_entity_count,
    coalesce(company_external_lookup_key is null, true) as violation_00,
    coalesce(company_external_lookup_key is not null and count(*) over (partition by company_external_lookup_key) > 1, true) as violation_01,
    coalesce(company_entity_count is not null and (company_entity_count > 1), true) as violation_02
from step_04_data_aggregation
