-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_record_id,
        source_fund_id,
        source_company_id,
        source_valued_on,
        source_value_usd,
        source_method,
        source_valuation_level,
        source_confidence_score,
        valuation_source_system
    from {{ ref("investment__holding_valuation_conformed__checked") }}
),
step_02_calculated_fields as (
    select
        source_record_id,
        source_fund_id,
        source_company_id,
        source_valued_on,
        source_value_usd,
        source_method,
        source_valuation_level,
        source_confidence_score,
        valuation_source_system,
        cast((case when source_confidence_score >= 0.90 then 'high' when source_confidence_score >= 0.75 then 'medium' else 'low' end) as {{ dpf_type('string') }}) as valuation_confidence_band
    from checked_input
),
step_03_data_enrichment as (
    select
        base.source_record_id,
        base.source_fund_id,
        base.source_company_id,
        base.source_valued_on,
        base.source_value_usd,
        base.source_method,
        base.source_valuation_level,
        base.source_confidence_score,
        base.valuation_source_system,
        base.valuation_confidence_band,
        lookup_0.fund_business_key
    from step_02_calculated_fields as base
    left join {{ ref("investment__fund_conformed") }} as lookup_0
        on base.source_fund_id = lookup_0.source_fund_id
       and base.valuation_source_system = lookup_0.fund_source_system
)

select
    source_record_id,
    source_fund_id,
    source_company_id,
    source_valued_on,
    source_value_usd,
    source_method,
    source_valuation_level,
    source_confidence_score,
    valuation_source_system,
    valuation_confidence_band,
    fund_business_key
from step_03_data_enrichment
