-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        vantora_record_id,
        vantora_fund_id,
        fund_name,
        fund_family_name,
        vehicle_type,
        gp_source_id,
        gp_name,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        committed_capital_usd,
        currency,
        domicile,
        fund_status,
        as_of_date
    from {{ ref("investment__vantora_fund_extract__checked") }}
)

select
    vantora_record_id,
    vantora_fund_id,
    fund_name,
    fund_family_name,
    vehicle_type,
    gp_source_id,
    gp_name,
    fund_lei,
    shared_external_id,
    asset_class,
    strategy,
    vintage_year,
    committed_capital_usd,
    currency,
    domicile,
    fund_status,
    as_of_date
from checked_input
