-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on,
        violation_00,
        violation_01
    from {{ ref("investment__chrono_portfolio_company__checked") }}
),
violations as (
    select
        'asset_uid_not_null' as rule_name,
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on
    from quarantined
    where violation_00

    union all

    select
        'issuer_name_text_not_null' as rule_name,
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on
    from quarantined
    where violation_01
)

select
    rule_name,
    asset_uid,
    vehicle_code,
    issuer_name_text,
    issuer_lei,
    vendor_company_id,
    industry_group,
    industry_detail,
    country_iso2,
    holding_status,
    first_reported_on
from violations
