-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source,
        violation_00
    from {{ ref("investment__company_external_index__checked_pre") }}
),
violations as (
    select
        'company_business_key_not_null' as rule_name,
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source
    from quarantined
    where violation_00
)

select
    rule_name,
    portfolio_company_hk,
    company_business_key,
    company_name,
    company_sector,
    company_sub_sector,
    company_country,
    company_status,
    company_lei,
    company_external_id,
    load_datetime,
    record_source
from violations
