-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        vehicle_id,
        vantora_fund_id,
        parent_vehicle_id,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        vehicle_lei
    from {{ ref("raw_vantora_legal_vehicles") }}
)

select
    vehicle_id,
    vantora_fund_id,
    parent_vehicle_id,
    vehicle_name,
    vehicle_type,
    jurisdiction,
    incorporation_date,
    vehicle_lei,
    coalesce(vehicle_id is null, true) as violation_00,
    coalesce(vehicle_id is not null and count(*) over (partition by vehicle_id) > 1, true) as violation_01,
    coalesce(vehicle_name is null, true) as violation_02
from source_00
