-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at
    from {{ ref("investment__vantora_portfolio_company_extract") }}
),
step_00_batch_transfer as (
    select
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at
    from source_00
)

select
    vantora_company_id,
    vantora_fund_id,
    company_name,
    company_lei,
    shared_external_id,
    sector,
    sub_sector,
    country,
    status,
    first_seen_at,
    coalesce(vantora_company_id is null, true) as violation_00,
    coalesce(company_name is null, true) as violation_01
from step_00_batch_transfer
