-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(
    materialized='incremental',
    incremental_strategy=dpf_incremental_strategy({"bigquery": "merge", "duckdb": "delete+insert"}),
    unique_key=["deal_fund_lhk"]
) }}

with
link_deal_fund_source as (
    select distinct
        deal_business_key,
        deal_fund_business_key
    from {{ ref("investment__deal_vault__base") }}
    where deal_business_key is not null and deal_fund_business_key is not null
),
link_deal_fund_keyed as (
    select
        {{ dpf_vault_hash(["deal_business_key", "deal_fund_business_key"]) }} as deal_fund_lhk,
        {{ dpf_vault_hash(["deal_business_key"]) }} as deal_hk,
        {{ dpf_vault_hash(["deal_fund_business_key"]) }} as fund_hk,
        deal_business_key,
        deal_fund_business_key,
        {{ dpf_publish_timestamp() }} as load_datetime,
        'investment.deal_vault' as record_source
    from link_deal_fund_source
),
link_deal_fund_unstored as (
    select
        deal_fund_lhk,
        deal_hk,
        fund_hk,
        load_datetime,
        record_source
    from link_deal_fund_keyed
    where {{ dpf_vault_unstored_key("link_deal_fund_keyed", "deal_fund_lhk") }}
)

select
    cast(deal_fund_lhk as {{ dpf_type('string') }}) as deal_fund_lhk,
    cast(deal_hk as {{ dpf_type('string') }}) as deal_hk,
    cast(fund_hk as {{ dpf_type('string') }}) as fund_hk,
    cast(load_datetime as {{ dpf_type('timestamp') }}) as load_datetime,
    cast(record_source as {{ dpf_type('string') }}) as record_source
from link_deal_fund_unstored
