-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (coalesce(decision_is_final, false) = false) as predicate_00
    from {{ ref("investment__deal_review_worklist__prefilter") }}
),
counted as (
    select
        'deals_no_final_decision_settles' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
