-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at
    from {{ ref("investment__vantora_portfolio_company__checked") }}
),
step_02_schema_transform as (
    select
        cast(vantora_company_id as {{ dpf_type('string') }}) as source_company_id,
        cast(vantora_fund_id as {{ dpf_type('string') }}) as source_fund_id,
        cast(company_name as {{ dpf_type('string') }}) as source_name,
        cast(company_lei as {{ dpf_type('string') }}) as source_lei,
        cast(shared_external_id as {{ dpf_type('string') }}) as source_external_id,
        cast(sector as {{ dpf_type('string') }}) as source_sector,
        cast(sub_sector as {{ dpf_type('string') }}) as source_sub_sector,
        cast(country as {{ dpf_type('string') }}) as source_country,
        cast(status as {{ dpf_type('string') }}) as source_status,
        cast(first_seen_at as {{ dpf_type('date') }}) as source_reported_on
    from checked_input
),
step_03_calculated_fields as (
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        cast((source_company_id) as {{ dpf_type('string') }}) as source_record_id,
        cast(('vantora') as {{ dpf_type('string') }}) as company_source_system,
        cast((concat('vantora', ':', source_company_id)) as {{ dpf_type('string') }}) as company_identity_key,
        cast(({{ dpf_investment_normalised_name("source_name") }}) as {{ dpf_type('string') }}) as company_normalised_name,
        cast((nullif(trim(source_lei), '')) as {{ dpf_type('string') }}) as company_lei,
        cast((nullif(trim(source_external_id), '')) as {{ dpf_type('string') }}) as company_external_id
    from step_02_schema_transform
)

select
    source_company_id,
    source_fund_id,
    source_name,
    source_lei,
    source_external_id,
    source_sector,
    source_sub_sector,
    source_country,
    source_status,
    source_reported_on,
    source_record_id,
    company_source_system,
    company_identity_key,
    company_normalised_name,
    company_lei,
    company_external_id
from step_03_calculated_fields
