-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        source_record_id,
        source_predecessor_gp_id,
        source_successor_gp_id,
        source_event_type,
        source_effective_on,
        succession_source_system,
        violation_00,
        violation_01
    from {{ ref("investment__gp_succession__checked") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        source_record_id,
        source_predecessor_gp_id,
        source_successor_gp_id,
        source_event_type,
        source_effective_on,
        succession_source_system
    from quarantined
    where violation_00

    union all

    select
        'source_effective_on_not_null' as rule_name,
        source_record_id,
        source_predecessor_gp_id,
        source_successor_gp_id,
        source_event_type,
        source_effective_on,
        succession_source_system
    from quarantined
    where violation_01
)

select
    rule_name,
    source_record_id,
    source_predecessor_gp_id,
    source_successor_gp_id,
    source_event_type,
    source_effective_on,
    succession_source_system
from violations
