-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        chrono_row_uid,
        chrono_vehicle_code,
        vehicle_display_name,
        vehicle_group_name,
        vehicle_form,
        manager_master_code,
        manager_name_text,
        manager_lei,
        legal_entity_identifier,
        vendor_crosswalk_id,
        private_market_bucket,
        investment_style,
        launch_year,
        commitment_amount_usd,
        reporting_ccy,
        domicile_iso2,
        lifecycle_state,
        snapshot_date,
        violation_00
    from {{ ref("investment__chrono_gp__checked") }}
),
violations as (
    select
        'manager_name_text_not_null' as rule_name,
        chrono_row_uid,
        chrono_vehicle_code,
        vehicle_display_name,
        vehicle_group_name,
        vehicle_form,
        manager_master_code,
        manager_name_text,
        manager_lei,
        legal_entity_identifier,
        vendor_crosswalk_id,
        private_market_bucket,
        investment_style,
        launch_year,
        commitment_amount_usd,
        reporting_ccy,
        domicile_iso2,
        lifecycle_state,
        snapshot_date
    from quarantined
    where violation_00
)

select
    rule_name,
    chrono_row_uid,
    chrono_vehicle_code,
    vehicle_display_name,
    vehicle_group_name,
    vehicle_form,
    manager_master_code,
    manager_name_text,
    manager_lei,
    legal_entity_identifier,
    vendor_crosswalk_id,
    private_market_bucket,
    investment_style,
    launch_year,
    commitment_amount_usd,
    reporting_ccy,
    domicile_iso2,
    lifecycle_state,
    snapshot_date
from violations
