-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code
    from {{ ref("investment__chrono_cash_flow__checked") }}
),
step_02_schema_transform as (
    select
        cast(event_uid as {{ dpf_type('string') }}) as source_record_id,
        cast(vehicle_code as {{ dpf_type('string') }}) as source_fund_id,
        cast(event_date as {{ dpf_type('date') }}) as source_cash_flow_on,
        cast(event_kind as {{ dpf_type('string') }}) as source_cash_flow_type,
        cast(investor_direction as {{ dpf_type('string') }}) as source_direction,
        cast(usd_amount as {{ dpf_decimal_type(18, 2) }}) as source_amount_usd,
        cast(currency_code as {{ dpf_type('string') }}) as source_currency
    from checked_input
),
step_03_calculated_fields as (
    select
        source_record_id,
        source_fund_id,
        source_cash_flow_on,
        source_cash_flow_type,
        source_direction,
        source_amount_usd,
        source_currency,
        cast(('chrono') as {{ dpf_type('string') }}) as cash_flow_source_system
    from step_02_schema_transform
)

select
    source_record_id,
    source_fund_id,
    source_cash_flow_on,
    source_cash_flow_type,
    source_direction,
    source_amount_usd,
    source_currency,
    cash_flow_source_system
from step_03_calculated_fields
