-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from {{ ref("investment__chrono_portfolio_company") }}
    union all
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from {{ ref("investment__meridex_portfolio_company") }}
    union all
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from {{ ref("investment__portiq_portfolio_company") }}
    union all
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from {{ ref("investment__vantora_portfolio_company") }}
),
step_00_batch_transfer as (
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from source_00
)

select
    source_company_id,
    source_fund_id,
    source_name,
    source_lei,
    source_external_id,
    source_sector,
    source_sub_sector,
    source_country,
    source_status,
    source_reported_on,
    source_record_id,
    company_source_system,
    company_identity_key,
    company_normalised_name,
    company_lei,
    company_external_id,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(company_identity_key is null, true) as violation_01
from step_00_batch_transfer
