-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
resolution_input as (
    select
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id,
        company_business_key,
        company_record_id,
        company_source_id,
        company_fund_source_id,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_reported_on,
        resolution_record_key,
        resolution_entity_key
    from {{ ref("investment__portfolio_company_vault__resolution") }}
),
survivorship_company_source_system as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_source_system as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_source_system is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_source_system
    where pick_rank = 1
),
survivorship_company_identity_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_identity_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_identity_key is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_identity_key
    where pick_rank = 1
),
survivorship_company_normalised_name as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_normalised_name as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_normalised_name is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_normalised_name
    where pick_rank = 1
),
survivorship_company_lei as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_lei as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_lei is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_lei
    where pick_rank = 1
),
survivorship_company_external_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_external_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_external_id is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_external_id
    where pick_rank = 1
),
survivorship_company_business_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_business_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_business_key is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_business_key
    where pick_rank = 1
),
survivorship_company_record_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_record_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_record_id is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_record_id
    where pick_rank = 1
),
survivorship_company_source_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_source_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_source_id is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_source_id
    where pick_rank = 1
),
survivorship_company_fund_source_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_fund_source_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_fund_source_id is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_fund_source_id
    where pick_rank = 1
),
survivorship_company_name as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_name as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_name is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_name
    where pick_rank = 1
),
survivorship_company_sector as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_sector as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_sector is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_sector
    where pick_rank = 1
),
survivorship_company_sub_sector as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_sub_sector as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_sub_sector is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_sub_sector
    where pick_rank = 1
),
survivorship_company_country as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_country as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_country is null then 1 else 0 end, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_country
    where pick_rank = 1
),
survivorship_company_status as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_status as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_status is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_status
    where pick_rank = 1
),
survivorship_company_reported_on as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            company_reported_on as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when company_reported_on is null then 1 else 0 end, company_reported_on desc, case when company_source_system = 'vantora' then 1 when company_source_system = 'chrono' then 2 when company_source_system = 'meridex' then 3 when company_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_company_reported_on
    where pick_rank = 1
),
curation_entities as (
    select distinct
        resolution_entity_key
    from resolution_input
),
curation_survivor as (
    select
        survivorship_company_source_system.attribute_value as company_source_system,
        survivorship_company_identity_key.attribute_value as company_identity_key,
        survivorship_company_normalised_name.attribute_value as company_normalised_name,
        survivorship_company_lei.attribute_value as company_lei,
        survivorship_company_external_id.attribute_value as company_external_id,
        survivorship_company_business_key.attribute_value as company_business_key,
        survivorship_company_record_id.attribute_value as company_record_id,
        survivorship_company_source_id.attribute_value as company_source_id,
        survivorship_company_fund_source_id.attribute_value as company_fund_source_id,
        survivorship_company_name.attribute_value as company_name,
        survivorship_company_sector.attribute_value as company_sector,
        survivorship_company_sub_sector.attribute_value as company_sub_sector,
        survivorship_company_country.attribute_value as company_country,
        survivorship_company_status.attribute_value as company_status,
        survivorship_company_reported_on.attribute_value as company_reported_on
    from curation_entities as entities
    left join survivorship_company_source_system
        on survivorship_company_source_system.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_identity_key
        on survivorship_company_identity_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_normalised_name
        on survivorship_company_normalised_name.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_lei
        on survivorship_company_lei.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_external_id
        on survivorship_company_external_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_business_key
        on survivorship_company_business_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_record_id
        on survivorship_company_record_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_source_id
        on survivorship_company_source_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_fund_source_id
        on survivorship_company_fund_source_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_name
        on survivorship_company_name.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_sector
        on survivorship_company_sector.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_sub_sector
        on survivorship_company_sub_sector.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_country
        on survivorship_company_country.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_status
        on survivorship_company_status.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_company_reported_on
        on survivorship_company_reported_on.resolution_entity_key = entities.resolution_entity_key
)

select
    company_source_system,
    company_identity_key,
    company_normalised_name,
    company_lei,
    company_external_id,
    company_business_key,
    company_record_id,
    company_source_id,
    company_fund_source_id,
    company_name,
    company_sector,
    company_sub_sector,
    company_country,
    company_status,
    company_reported_on,
    coalesce(company_business_key is null, true) as violation_00,
    coalesce(company_business_key is not null and count(*) over (partition by company_business_key) > 1, true) as violation_01
from curation_survivor
