-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at,
        violation_00,
        violation_01
    from {{ ref("investment__vantora_portfolio_company__checked") }}
),
violations as (
    select
        'vantora_company_id_not_null' as rule_name,
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at
    from quarantined
    where violation_00

    union all

    select
        'company_name_not_null' as rule_name,
        vantora_company_id,
        vantora_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        sub_sector,
        country,
        status,
        first_seen_at
    from quarantined
    where violation_01
)

select
    rule_name,
    vantora_company_id,
    vantora_fund_id,
    company_name,
    company_lei,
    shared_external_id,
    sector,
    sub_sector,
    country,
    status,
    first_seen_at
from violations
