-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        cash_flow_id,
        vantora_fund_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from {{ ref("raw_vantora_cash_flows") }}
)

select
    cash_flow_id,
    vantora_fund_id,
    cash_flow_date,
    cash_flow_type,
    direction,
    amount_usd,
    currency,
    coalesce(cash_flow_id is null, true) as violation_00,
    coalesce(cash_flow_id is not null and count(*) over (partition by cash_flow_id) > 1, true) as violation_01,
    coalesce(vantora_fund_id is null, true) as violation_02,
    coalesce(cash_flow_date is null, true) as violation_03
from source_00
