-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        deal_hk,
        deal_business_key,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_originating_team,
        deal_target_company_external_id,
        deal_converted_record_type,
        deal_converted_fund_external_id,
        deal_external_identity,
        load_datetime,
        record_source
    from {{ ref("investment__deal_vault__golden_deal") }}
),
step_00_batch_transfer as (
    select
        deal_hk,
        deal_business_key,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_originating_team,
        deal_target_company_external_id,
        deal_converted_record_type,
        deal_converted_fund_external_id,
        deal_external_identity,
        load_datetime,
        record_source
    from source_00
)

select
    deal_hk,
    deal_business_key,
    deal_name,
    deal_strategy,
    deal_structure,
    deal_channel,
    deal_originating_team,
    deal_target_company_external_id,
    deal_converted_record_type,
    deal_converted_fund_external_id,
    deal_external_identity,
    load_datetime,
    record_source,
    coalesce(deal_business_key is null, true) as violation_00
from step_00_batch_transfer
