-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from {{ ref("investment__origo_deal_extract") }}
),
step_00_batch_transfer as (
    select
        deal_id,
        external_deal_id,
        deal_name,
        target_entity_id,
        strategy,
        originating_team,
        source_channel,
        sourced_date,
        structure,
        converted_record_type,
        converted_record_id
    from source_00
)

select
    deal_id,
    external_deal_id,
    deal_name,
    target_entity_id,
    strategy,
    originating_team,
    source_channel,
    sourced_date,
    structure,
    converted_record_type,
    converted_record_id,
    coalesce(deal_id is null, true) as violation_00,
    coalesce(deal_name is null, true) as violation_01
from step_00_batch_transfer
