-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        vantora_gp_id,
        gp_name,
        gp_lei,
        shared_external_id,
        domicile,
        relationship_start_date
    from {{ ref("investment__vantora_gp_extract__checked") }}
)

select
    vantora_gp_id,
    gp_name,
    gp_lei,
    shared_external_id,
    domicile,
    relationship_start_date
from checked_input
