-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on
    from {{ ref("investment__chrono_portfolio_company_extract__checked") }}
)

select
    asset_uid,
    vehicle_code,
    issuer_name_text,
    issuer_lei,
    vendor_company_id,
    industry_group,
    industry_detail,
    country_iso2,
    holding_status,
    first_reported_on
from checked_input
