-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence
    from {{ ref("investment__chrono_valuation_extract__checked") }}
)

select
    mark_uid,
    vehicle_code,
    asset_uid,
    mark_date,
    usd_fair_value,
    mark_method,
    fair_value_bucket,
    extraction_confidence
from checked_input
