-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (decision_rank = 1) as predicate_00
    from {{ ref("investment__deal_decision_current__prefilter") }}
),
counted as (
    select
        'latest_decision_per_item_only' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
