-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_post_input as (
    select
        vehicle_source_system,
        vehicle_identity_key,
        vehicle_normalised_name,
        vehicle_lei,
        vehicle_business_key,
        vehicle_record_id,
        vehicle_source_id,
        vehicle_fund_source_id,
        vehicle_parent_source_id,
        vehicle_name,
        vehicle_type,
        vehicle_jurisdiction,
        vehicle_incorporated_on,
        vehicle_reported_on,
        vehicle_fund_business_key
    from {{ ref("investment__legal_vehicle_vault__checked_post") }}
)

select
    vehicle_source_system,
    vehicle_identity_key,
    vehicle_normalised_name,
    vehicle_lei,
    vehicle_business_key,
    vehicle_record_id,
    vehicle_source_id,
    vehicle_fund_source_id,
    vehicle_parent_source_id,
    vehicle_name,
    vehicle_type,
    vehicle_jurisdiction,
    vehicle_incorporated_on,
    vehicle_reported_on,
    vehicle_fund_business_key
from checked_post_input
