-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis
    from {{ ref("investment__fund_performance__checked") }}
),
step_02_calculated_fields as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis,
        cast((source_called_capital_usd - fund_recallable_distributions_usd - fund_fee_offset_usd) as {{ dpf_decimal_type(18, 2) }}) as fund_invested_capital_usd,
        cast((source_nav_usd + source_distributed_capital_usd) as {{ dpf_decimal_type(18, 2) }}) as fund_total_value_usd,
        cast((case when (source_called_capital_usd - fund_recallable_distributions_usd - fund_fee_offset_usd) > 0 then (source_nav_usd + source_distributed_capital_usd) / (source_called_capital_usd - fund_recallable_distributions_usd - fund_fee_offset_usd) end) as {{ dpf_decimal_type(12, 6) }}) as fund_total_value_multiple,
        cast((case when fund_hurdle_rate is null then null when (source_called_capital_usd - fund_recallable_distributions_usd - fund_fee_offset_usd) <= 0 then null else ((source_nav_usd + source_distributed_capital_usd) / (source_called_capital_usd - fund_recallable_distributions_usd - fund_fee_offset_usd)) >= fund_hurdle_rate end) as {{ dpf_type('boolean') }}) as fund_clears_hurdle,
        cast(('MSCI_ACWI') as {{ dpf_type('string') }}) as fund_benchmark_id
    from checked_input
),
step_03_data_enrichment_asof_1_keys as (
    select
        distinct fund_benchmark_id,
        source_valued_on
    from step_02_calculated_fields
),
step_03_data_enrichment_asof_1_ranked as (
    select
        keys.fund_benchmark_id,
        keys.source_valued_on,
        reference.benchmark_index_value,
        reference.benchmark_label,
        row_number() over (
            partition by keys.fund_benchmark_id, keys.source_valued_on
            order by reference.benchmark_on desc, reference.benchmark_index_value, reference.benchmark_label
        ) as match_rank
    from step_03_data_enrichment_asof_1_keys as keys
    left join {{ ref("reference__benchmark_index") }} as reference
        on keys.fund_benchmark_id = reference.benchmark_id
       and reference.benchmark_on <= keys.source_valued_on
),
step_03_data_enrichment_asof_1 as (
    select
        fund_benchmark_id,
        source_valued_on,
        benchmark_index_value,
        benchmark_label
    from step_03_data_enrichment_asof_1_ranked
    where match_rank = 1
),
step_03_data_enrichment_asof_2_keys as (
    select
        distinct fund_external_id,
        source_valued_on
    from step_02_calculated_fields
),
step_03_data_enrichment_asof_2_ranked as (
    select
        keys.fund_external_id,
        keys.source_valued_on,
        reference.fund_department_code,
        row_number() over (
            partition by keys.fund_external_id, keys.source_valued_on
            order by reference.department_effective_from desc, reference.fund_department_code
        ) as match_rank
    from step_03_data_enrichment_asof_2_keys as keys
    left join {{ ref("reference__fund_department") }} as reference
        on keys.fund_external_id = reference.fund_external_identity
       and reference.department_effective_from <= keys.source_valued_on
),
step_03_data_enrichment_asof_2 as (
    select
        fund_external_id,
        source_valued_on,
        fund_department_code
    from step_03_data_enrichment_asof_2_ranked
    where match_rank = 1
),
step_03_data_enrichment as (
    select
        base.source_record_id,
        base.source_fund_id,
        base.source_valued_on,
        base.source_nav_usd,
        base.source_called_capital_usd,
        base.source_distributed_capital_usd,
        base.nav_source_system,
        base.fund_nav_source_key,
        base.fund_business_key,
        base.fund_external_id,
        base.source_name,
        base.source_strategy,
        base.source_currency,
        base.fund_recallable_distributions_usd,
        base.fund_fee_offset_usd,
        base.fund_hurdle_rate,
        base.fund_hurdle_basis,
        base.fund_invested_capital_usd,
        base.fund_total_value_usd,
        base.fund_total_value_multiple,
        base.fund_clears_hurdle,
        base.fund_benchmark_id,
        lookup_0.calendar_year,
        lookup_0.calendar_quarter,
        lookup_0.calendar_quarter_label,
        lookup_0.calendar_is_quarter_end,
        lookup_1.benchmark_index_value,
        lookup_1.benchmark_label,
        lookup_2.fund_department_code
    from step_02_calculated_fields as base
    left join {{ ref("reference__investment_calendar") }} as lookup_0
        on base.source_valued_on = lookup_0.calendar_date
    left join step_03_data_enrichment_asof_1 as lookup_1
        on base.fund_benchmark_id = lookup_1.fund_benchmark_id
       and base.source_valued_on = lookup_1.source_valued_on
    left join step_03_data_enrichment_asof_2 as lookup_2
        on base.fund_external_id = lookup_2.fund_external_id
       and base.source_valued_on = lookup_2.source_valued_on
)

select
    source_record_id,
    source_fund_id,
    source_valued_on,
    source_nav_usd,
    source_called_capital_usd,
    source_distributed_capital_usd,
    nav_source_system,
    fund_nav_source_key,
    fund_business_key,
    fund_external_id,
    source_name,
    source_strategy,
    source_currency,
    fund_recallable_distributions_usd,
    fund_fee_offset_usd,
    fund_hurdle_rate,
    fund_hurdle_basis,
    fund_invested_capital_usd,
    fund_total_value_usd,
    fund_total_value_multiple,
    fund_clears_hurdle,
    fund_benchmark_id,
    calendar_year,
    calendar_quarter,
    calendar_quarter_label,
    calendar_is_quarter_end,
    benchmark_index_value,
    benchmark_label,
    fund_department_code
from step_03_data_enrichment
