-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        source_record_id,
        source_external_deal_id,
        source_name,
        source_target_entity_id,
        source_strategy,
        source_originating_team,
        source_channel,
        source_sourced_on,
        source_structure,
        source_converted_record_type,
        source_converted_record_id,
        deal_source_system,
        deal_identity_key,
        deal_normalised_name,
        deal_external_id,
        deal_business_key,
        deal_target_company_external_id,
        deal_converted_fund_external_id,
        deal_target_company_lookup_key,
        deal_converted_fund_lookup_key,
        company_business_key,
        fund_business_key,
        violation_00,
        violation_01
    from {{ ref("investment__deal_vault__checked_pre") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        source_record_id,
        source_external_deal_id,
        source_name,
        source_target_entity_id,
        source_strategy,
        source_originating_team,
        source_channel,
        source_sourced_on,
        source_structure,
        source_converted_record_type,
        source_converted_record_id,
        deal_source_system,
        deal_identity_key,
        deal_normalised_name,
        deal_external_id,
        deal_business_key,
        deal_target_company_external_id,
        deal_converted_fund_external_id,
        deal_target_company_lookup_key,
        deal_converted_fund_lookup_key,
        company_business_key,
        fund_business_key
    from quarantined
    where violation_00

    union all

    select
        'source_name_not_null' as rule_name,
        source_record_id,
        source_external_deal_id,
        source_name,
        source_target_entity_id,
        source_strategy,
        source_originating_team,
        source_channel,
        source_sourced_on,
        source_structure,
        source_converted_record_type,
        source_converted_record_id,
        deal_source_system,
        deal_identity_key,
        deal_normalised_name,
        deal_external_id,
        deal_business_key,
        deal_target_company_external_id,
        deal_converted_fund_external_id,
        deal_target_company_lookup_key,
        deal_converted_fund_lookup_key,
        company_business_key,
        fund_business_key
    from quarantined
    where violation_01
)

select
    rule_name,
    source_record_id,
    source_external_deal_id,
    source_name,
    source_target_entity_id,
    source_strategy,
    source_originating_team,
    source_channel,
    source_sourced_on,
    source_structure,
    source_converted_record_type,
    source_converted_record_id,
    deal_source_system,
    deal_identity_key,
    deal_normalised_name,
    deal_external_id,
    deal_business_key,
    deal_target_company_external_id,
    deal_converted_fund_external_id,
    deal_target_company_lookup_key,
    deal_converted_fund_lookup_key,
    company_business_key,
    fund_business_key
from violations
