-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        cash_flow_id,
        portiq_fund_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from {{ ref("investment__portiq_cash_flow_extract__checked") }}
)

select
    cash_flow_id,
    portiq_fund_id,
    cash_flow_date,
    cash_flow_type,
    direction,
    amount_usd,
    currency
from checked_input
