-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        source_vehicle_id,
        source_fund_id,
        source_parent_vehicle_id,
        source_name,
        source_vehicle_type,
        source_jurisdiction,
        source_incorporation_text,
        source_lei,
        source_record_id,
        source_incorporated_on,
        source_reported_on,
        vehicle_source_system,
        vehicle_identity_key,
        vehicle_normalised_name,
        vehicle_lei,
        violation_00,
        violation_01
    from {{ ref("investment__legal_vehicle_conformed__checked") }}
),
violations as (
    select
        'source_record_id_not_null' as rule_name,
        source_vehicle_id,
        source_fund_id,
        source_parent_vehicle_id,
        source_name,
        source_vehicle_type,
        source_jurisdiction,
        source_incorporation_text,
        source_lei,
        source_record_id,
        source_incorporated_on,
        source_reported_on,
        vehicle_source_system,
        vehicle_identity_key,
        vehicle_normalised_name,
        vehicle_lei
    from quarantined
    where violation_00

    union all

    select
        'vehicle_identity_key_not_null' as rule_name,
        source_vehicle_id,
        source_fund_id,
        source_parent_vehicle_id,
        source_name,
        source_vehicle_type,
        source_jurisdiction,
        source_incorporation_text,
        source_lei,
        source_record_id,
        source_incorporated_on,
        source_reported_on,
        vehicle_source_system,
        vehicle_identity_key,
        vehicle_normalised_name,
        vehicle_lei
    from quarantined
    where violation_01
)

select
    rule_name,
    source_vehicle_id,
    source_fund_id,
    source_parent_vehicle_id,
    source_name,
    source_vehicle_type,
    source_jurisdiction,
    source_incorporation_text,
    source_lei,
    source_record_id,
    source_incorporated_on,
    source_reported_on,
    vehicle_source_system,
    vehicle_identity_key,
    vehicle_normalised_name,
    vehicle_lei
from violations
