-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code,
        violation_00,
        violation_01
    from {{ ref("investment__chrono_cash_flow__checked") }}
),
violations as (
    select
        'event_uid_not_null' as rule_name,
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code
    from quarantined
    where violation_00

    union all

    select
        'event_date_not_null' as rule_name,
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code
    from quarantined
    where violation_01
)

select
    rule_name,
    event_uid,
    vehicle_code,
    event_date,
    event_kind,
    investor_direction,
    usd_amount,
    currency_code
from violations
