-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on
    from {{ ref("investment__chrono_portfolio_company_extract") }}
),
step_00_batch_transfer as (
    select
        asset_uid,
        vehicle_code,
        issuer_name_text,
        issuer_lei,
        vendor_company_id,
        industry_group,
        industry_detail,
        country_iso2,
        holding_status,
        first_reported_on
    from source_00
)

select
    asset_uid,
    vehicle_code,
    issuer_name_text,
    issuer_lei,
    vendor_company_id,
    industry_group,
    industry_detail,
    country_iso2,
    holding_status,
    first_reported_on,
    coalesce(asset_uid is null, true) as violation_00,
    coalesce(issuer_name_text is null, true) as violation_01
from step_00_batch_transfer
