-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        portiq_company_id,
        portiq_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country,
        violation_00,
        violation_01,
        violation_02
    from {{ ref("investment__portiq_portfolio_company_extract__checked") }}
),
violations as (
    select
        'portiq_company_id_not_null' as rule_name,
        portiq_company_id,
        portiq_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from quarantined
    where violation_00

    union all

    select
        'portiq_company_id_unique' as rule_name,
        portiq_company_id,
        portiq_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from quarantined
    where violation_01

    union all

    select
        'company_name_not_null' as rule_name,
        portiq_company_id,
        portiq_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from quarantined
    where violation_02
)

select
    rule_name,
    portiq_company_id,
    portiq_fund_id,
    company_name,
    company_lei,
    shared_external_id,
    sector,
    country
from violations
