-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
evaluated as (
    select
        (source_nav_usd is not null) as predicate_00
    from {{ ref("investment__fund_performance_summary__prefilter") }}
),
counted as (
    select
        'valuation_dates_with_a_stated_value' as predicate_name,
        {{ dpf_excluded_count('predicate_00') }} as excluded_count
    from evaluated
)

select
    predicate_name,
    excluded_count
from counted
