-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code
    from {{ ref("raw_chrono_cash_flows") }}
)

select
    event_uid,
    vehicle_code,
    event_date,
    event_kind,
    investor_direction,
    usd_amount,
    currency_code,
    coalesce(event_uid is null, true) as violation_00,
    coalesce(event_uid is not null and count(*) over (partition by event_uid) > 1, true) as violation_01,
    coalesce(vehicle_code is null, true) as violation_02,
    coalesce(event_date is null, true) as violation_03
from source_00
