-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
resolution_input as (
    select
        gp_source_system,
        gp_identity_key,
        gp_normalised_name,
        gp_lei,
        gp_external_id,
        gp_business_key,
        gp_record_id,
        gp_source_id,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_reported_on,
        resolution_record_key,
        resolution_entity_key
    from {{ ref("investment__gp_vault__resolution") }}
),
survivorship_gp_source_system as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_source_system as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_source_system is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_source_system
    where pick_rank = 1
),
survivorship_gp_identity_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_identity_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_identity_key is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_identity_key
    where pick_rank = 1
),
survivorship_gp_normalised_name as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_normalised_name as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_normalised_name is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_normalised_name
    where pick_rank = 1
),
survivorship_gp_lei as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_lei as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_lei is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_lei
    where pick_rank = 1
),
survivorship_gp_external_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_external_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_external_id is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_external_id
    where pick_rank = 1
),
survivorship_gp_business_key as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_business_key as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_business_key is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_business_key
    where pick_rank = 1
),
survivorship_gp_record_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_record_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_record_id is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_record_id
    where pick_rank = 1
),
survivorship_gp_source_id as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_source_id as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_source_id is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_source_id
    where pick_rank = 1
),
survivorship_gp_name as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_name as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_name is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_name
    where pick_rank = 1
),
survivorship_gp_domicile as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_domicile as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_domicile is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_domicile
    where pick_rank = 1
),
survivorship_gp_relationship_start_on as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_relationship_start_on as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_relationship_start_on is null then 1 else 0 end, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_relationship_start_on
    where pick_rank = 1
),
survivorship_gp_reported_on as (
    select
        resolution_entity_key,
        attribute_value
    from (
        select
            resolution_entity_key,
            gp_reported_on as attribute_value,
            row_number() over (
                partition by resolution_entity_key
                order by case when gp_reported_on is null then 1 else 0 end, gp_reported_on desc, case when gp_source_system = 'vantora' then 1 when gp_source_system = 'chrono' then 2 when gp_source_system = 'meridex' then 3 when gp_source_system = 'portiq' then 4 else 5 end, resolution_record_key
            ) as pick_rank
        from resolution_input
    ) as ranked_gp_reported_on
    where pick_rank = 1
),
curation_entities as (
    select distinct
        resolution_entity_key
    from resolution_input
),
curation_survivor as (
    select
        survivorship_gp_source_system.attribute_value as gp_source_system,
        survivorship_gp_identity_key.attribute_value as gp_identity_key,
        survivorship_gp_normalised_name.attribute_value as gp_normalised_name,
        survivorship_gp_lei.attribute_value as gp_lei,
        survivorship_gp_external_id.attribute_value as gp_external_id,
        survivorship_gp_business_key.attribute_value as gp_business_key,
        survivorship_gp_record_id.attribute_value as gp_record_id,
        survivorship_gp_source_id.attribute_value as gp_source_id,
        survivorship_gp_name.attribute_value as gp_name,
        survivorship_gp_domicile.attribute_value as gp_domicile,
        survivorship_gp_relationship_start_on.attribute_value as gp_relationship_start_on,
        survivorship_gp_reported_on.attribute_value as gp_reported_on
    from curation_entities as entities
    left join survivorship_gp_source_system
        on survivorship_gp_source_system.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_identity_key
        on survivorship_gp_identity_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_normalised_name
        on survivorship_gp_normalised_name.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_lei
        on survivorship_gp_lei.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_external_id
        on survivorship_gp_external_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_business_key
        on survivorship_gp_business_key.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_record_id
        on survivorship_gp_record_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_source_id
        on survivorship_gp_source_id.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_name
        on survivorship_gp_name.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_domicile
        on survivorship_gp_domicile.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_relationship_start_on
        on survivorship_gp_relationship_start_on.resolution_entity_key = entities.resolution_entity_key
    left join survivorship_gp_reported_on
        on survivorship_gp_reported_on.resolution_entity_key = entities.resolution_entity_key
)

select
    gp_source_system,
    gp_identity_key,
    gp_normalised_name,
    gp_lei,
    gp_external_id,
    gp_business_key,
    gp_record_id,
    gp_source_id,
    gp_name,
    gp_domicile,
    gp_relationship_start_on,
    gp_reported_on,
    coalesce(gp_business_key is null, true) as violation_00,
    coalesce(gp_business_key is not null and count(*) over (partition by gp_business_key) > 1, true) as violation_01
from curation_survivor
