-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
pit_fund_fund_detail_ranked as (
    select
        fund_hk,
        effective_from,
        dense_rank() over (partition by fund_hk order by hashdiff_basis_version desc) as dpf_version_rank
    from {{ ref("investment__fund_vault__sat_fund_detail") }}
),
pit_fund_fund_detail_scoped as (
    select
        fund_hk,
        effective_from
    from pit_fund_fund_detail_ranked
    where dpf_version_rank = 1
),
pit_fund_fund_observed_ranked as (
    select
        fund_hk,
        effective_from,
        dense_rank() over (partition by fund_hk order by hashdiff_basis_version desc) as dpf_version_rank
    from {{ ref("investment__fund_vault__sat_fund_observed") }}
),
pit_fund_fund_observed_scoped as (
    select
        fund_hk,
        effective_from
    from pit_fund_fund_observed_ranked
    where dpf_version_rank = 1
),
pit_fund_spine as (
    select distinct
        fund_hk,
        effective_from as as_of
    from pit_fund_fund_detail_scoped
    union distinct
    select distinct
        fund_hk,
        effective_from as as_of
    from pit_fund_fund_observed_scoped
),
pit_fund_fund_detail as (
    select
        pit_fund_spine.fund_hk as fund_hk,
        pit_fund_spine.as_of as as_of,
        max(pit_fund_fund_detail_stored.effective_from) as fund_detail_effective_from
    from pit_fund_spine
    left join pit_fund_fund_detail_scoped as pit_fund_fund_detail_stored
        on pit_fund_fund_detail_stored.fund_hk = pit_fund_spine.fund_hk
        and pit_fund_fund_detail_stored.effective_from <= pit_fund_spine.as_of
    group by pit_fund_spine.fund_hk, pit_fund_spine.as_of
),
pit_fund_fund_observed as (
    select
        pit_fund_spine.fund_hk as fund_hk,
        pit_fund_spine.as_of as as_of,
        max(pit_fund_fund_observed_stored.effective_from) as fund_observed_effective_from
    from pit_fund_spine
    left join pit_fund_fund_observed_scoped as pit_fund_fund_observed_stored
        on pit_fund_fund_observed_stored.fund_hk = pit_fund_spine.fund_hk
        and pit_fund_fund_observed_stored.effective_from <= pit_fund_spine.as_of
    group by pit_fund_spine.fund_hk, pit_fund_spine.as_of
),
pit_fund_joined as (
    select
        pit_fund_spine.fund_hk as fund_hk,
        pit_fund_spine.as_of as as_of,
        pit_fund_fund_detail.fund_detail_effective_from as fund_detail_effective_from,
        pit_fund_fund_observed.fund_observed_effective_from as fund_observed_effective_from
    from pit_fund_spine
    left join pit_fund_fund_detail
        on pit_fund_fund_detail.fund_hk = pit_fund_spine.fund_hk and pit_fund_fund_detail.as_of = pit_fund_spine.as_of
    left join pit_fund_fund_observed
        on pit_fund_fund_observed.fund_hk = pit_fund_spine.fund_hk and pit_fund_fund_observed.as_of = pit_fund_spine.as_of
)

select
    cast(fund_hk as {{ dpf_type('string') }}) as fund_hk,
    cast(as_of as {{ dpf_type('date') }}) as as_of,
    cast(fund_detail_effective_from as {{ dpf_type('date') }}) as fund_detail_effective_from,
    cast(fund_observed_effective_from as {{ dpf_type('date') }}) as fund_observed_effective_from
from pit_fund_joined
