-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        meridex_company_id,
        meridex_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country,
        violation_00,
        violation_01
    from {{ ref("investment__meridex_portfolio_company__checked") }}
),
violations as (
    select
        'meridex_company_id_not_null' as rule_name,
        meridex_company_id,
        meridex_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from quarantined
    where violation_00

    union all

    select
        'company_name_not_null' as rule_name,
        meridex_company_id,
        meridex_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from quarantined
    where violation_01
)

select
    rule_name,
    meridex_company_id,
    meridex_fund_id,
    company_name,
    company_lei,
    shared_external_id,
    sector,
    country
from violations
