-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        succession_event_id,
        predecessor_gp_id,
        successor_gp_id,
        event_type,
        effective_date
    from {{ ref("investment__vantora_succession_event_extract__checked") }}
)

select
    succession_event_id,
    predecessor_gp_id,
    successor_gp_id,
    event_type,
    effective_date
from checked_input
