-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        valuation_id,
        vantora_fund_id,
        vantora_company_id,
        valuation_date,
        value_usd,
        method,
        valuation_level,
        confidence_score
    from {{ ref("raw_vantora_valuations") }}
)

select
    valuation_id,
    vantora_fund_id,
    vantora_company_id,
    valuation_date,
    value_usd,
    method,
    valuation_level,
    confidence_score,
    coalesce(valuation_id is null, true) as violation_00,
    coalesce(valuation_id is not null and count(*) over (partition by valuation_id) > 1, true) as violation_01,
    coalesce(vantora_fund_id is null, true) as violation_02,
    coalesce(valuation_date is null, true) as violation_03
from source_00
