-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        meridex_company_id,
        meridex_fund_id,
        company_name,
        company_lei,
        shared_external_id,
        sector,
        country
    from {{ ref("raw_meridex_portfolio_companies") }}
)

select
    meridex_company_id,
    meridex_fund_id,
    company_name,
    company_lei,
    shared_external_id,
    sector,
    country,
    coalesce(meridex_company_id is null, true) as violation_00,
    coalesce(meridex_company_id is not null and count(*) over (partition by meridex_company_id) > 1, true) as violation_01,
    coalesce(company_name is null, true) as violation_02
from source_00
