-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
pending_records as (
    select
        resolution_record_key,
        fund_normalised_name,
        fund_asset_class,
        fund_reported_on
    from {{ ref("investment__fund_vault__resolution") }}
    where resolution_pending
),
candidate_pairs as (
    select
        left_side.resolution_record_key as record_key_a,
        right_side.resolution_record_key as record_key_b,
        {{ dpf_investment_entity_match_score("left_side.fund_normalised_name", "right_side.fund_normalised_name", "left_side.fund_asset_class", "right_side.fund_asset_class", "left_side.fund_reported_on", "right_side.fund_reported_on") }} as match_score
    from pending_records as left_side
    inner join pending_records as right_side
        on left_side.fund_asset_class = right_side.fund_asset_class
       and left_side.resolution_record_key < right_side.resolution_record_key
),
banded_pairs as (
    select
        record_key_a,
        record_key_b,
        match_score,
        case
            when match_score is null then 'unscored'
            when match_score >= 0.85 then 'accepted'
            when match_score >= 0.65 then 'review'
            else 'rejected'
        end as review_band
    from candidate_pairs
)

select
    record_key_a,
    record_key_b,
    match_score,
    review_band
from banded_pairs
