-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        decision_id,
        deal_external_identity,
        decision_outcome,
        decision_conditions,
        decision_actor,
        decision_decided_at,
        decision_rank,
        decision_is_final
    from {{ ref("investment__deal_decision_queue__checked") }}
),
step_02_data_enrichment as (
    select
        base.decision_id,
        base.deal_external_identity,
        base.decision_outcome,
        base.decision_conditions,
        base.decision_actor,
        base.decision_decided_at,
        base.decision_rank,
        base.decision_is_final,
        lookup_0.deal_name,
        lookup_0.deal_strategy,
        lookup_0.deal_originating_team
    from checked_input as base
    left join {{ ref("investment__deal_vault__golden_deal") }} as lookup_0
        on base.deal_external_identity = lookup_0.deal_business_key
)

select
    decision_id,
    deal_external_identity,
    decision_outcome,
    decision_conditions,
    decision_actor,
    decision_decided_at,
    decision_rank,
    decision_is_final,
    deal_name,
    deal_strategy,
    deal_originating_team
from step_02_data_enrichment
