-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        meridex_fund_id,
        fund_name,
        gp_name,
        gp_lei,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        currency,
        domicile
    from {{ ref("investment__meridex_fund_extract__checked") }}
)

select
    meridex_fund_id,
    fund_name,
    gp_name,
    gp_lei,
    fund_lei,
    shared_external_id,
    asset_class,
    strategy,
    vintage_year,
    currency,
    domicile
from checked_input
