-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system
    from {{ ref("investment__meridex_fund_nav") }}
),
step_00_batch_transfer as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system
    from source_00
)

select
    source_record_id,
    source_fund_id,
    source_valued_on,
    source_nav_usd,
    source_called_capital_usd,
    source_distributed_capital_usd,
    nav_source_system,
    coalesce(source_record_id is null, true) as violation_00,
    coalesce(source_valued_on is null, true) as violation_01
from step_00_batch_transfer
