-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id
    from {{ ref("investment__portfolio_company_conformed__checked") }}
),
step_02_calculated_fields as (
    select
        source_company_id,
        source_fund_id,
        source_name,
        source_lei,
        source_external_id,
        source_sector,
        source_sub_sector,
        source_country,
        source_status,
        source_reported_on,
        source_record_id,
        company_source_system,
        company_identity_key,
        company_normalised_name,
        company_lei,
        company_external_id,
        cast((coalesce(company_lei, company_external_id, company_normalised_name)) as {{ dpf_type('string') }}) as company_business_key
    from checked_input
)

select
    source_company_id,
    source_fund_id,
    source_name,
    source_lei,
    source_external_id,
    source_sector,
    source_sub_sector,
    source_country,
    source_status,
    source_reported_on,
    source_record_id,
    company_source_system,
    company_identity_key,
    company_normalised_name,
    company_lei,
    company_external_id,
    company_business_key
from step_02_calculated_fields
