-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source
    from {{ ref("investment__portfolio_company_vault__golden_portfolio_company") }}
),
step_00_batch_transfer as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source
    from source_00
)

select
    portfolio_company_hk,
    company_business_key,
    company_name,
    company_sector,
    company_sub_sector,
    company_country,
    company_status,
    company_lei,
    company_external_id,
    load_datetime,
    record_source,
    coalesce(company_business_key is null, true) as violation_00
from step_00_batch_transfer
