-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        source_record_id,
        source_vehicle_id,
        source_cash_flow_on,
        source_cash_flow_type,
        source_direction,
        source_amount_usd,
        source_currency,
        vehicle_cash_flow_source_system
    from {{ ref("investment__legal_vehicle_cash_flow__checked") }}
),
step_02_calculated_fields as (
    select
        source_record_id,
        source_vehicle_id,
        source_cash_flow_on,
        source_cash_flow_type,
        source_direction,
        source_amount_usd,
        source_currency,
        vehicle_cash_flow_source_system,
        cast((case when source_direction = 'inflow' then source_amount_usd else -source_amount_usd end) as {{ dpf_decimal_type(18, 2) }}) as vehicle_cash_flow_signed_amount_usd
    from checked_input
),
step_03_data_enrichment as (
    select
        base.source_record_id,
        base.source_vehicle_id,
        base.source_cash_flow_on,
        base.source_cash_flow_type,
        base.source_direction,
        base.source_amount_usd,
        base.source_currency,
        base.vehicle_cash_flow_source_system,
        base.vehicle_cash_flow_signed_amount_usd,
        lookup_0.vehicle_business_key,
        lookup_0.fund_business_key
    from step_02_calculated_fields as base
    left join {{ ref("investment__legal_vehicle_conformed") }} as lookup_0
        on base.source_vehicle_id = lookup_0.source_vehicle_id
       and base.vehicle_cash_flow_source_system = lookup_0.vehicle_source_system
)

select
    source_record_id,
    source_vehicle_id,
    source_cash_flow_on,
    source_cash_flow_type,
    source_direction,
    source_amount_usd,
    source_currency,
    vehicle_cash_flow_source_system,
    vehicle_cash_flow_signed_amount_usd,
    vehicle_business_key,
    fund_business_key
from step_03_data_enrichment
