-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        event_uid,
        vehicle_code,
        event_date,
        event_kind,
        investor_direction,
        usd_amount,
        currency_code
    from {{ ref("investment__chrono_cash_flow_extract__checked") }}
)

select
    event_uid,
    vehicle_code,
    event_date,
    event_kind,
    investor_direction,
    usd_amount,
    currency_code
from checked_input
