-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        portiq_fund_id,
        fund_name,
        gp_name,
        gp_lei,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        currency
    from {{ ref("investment__portiq_fund_extract__checked") }}
)

select
    portiq_fund_id,
    fund_name,
    gp_name,
    gp_lei,
    fund_lei,
    shared_external_id,
    asset_class,
    strategy,
    vintage_year,
    currency
from checked_input
