-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        nav_id,
        meridex_fund_id,
        nav_date,
        nav_usd,
        called_capital_usd,
        distributed_capital_usd,
        violation_00,
        violation_01
    from {{ ref("investment__meridex_fund_nav__checked") }}
),
violations as (
    select
        'nav_id_not_null' as rule_name,
        nav_id,
        meridex_fund_id,
        nav_date,
        nav_usd,
        called_capital_usd,
        distributed_capital_usd
    from quarantined
    where violation_00

    union all

    select
        'nav_date_not_null' as rule_name,
        nav_id,
        meridex_fund_id,
        nav_date,
        nav_usd,
        called_capital_usd,
        distributed_capital_usd
    from quarantined
    where violation_01
)

select
    rule_name,
    nav_id,
    meridex_fund_id,
    nav_date,
    nav_usd,
    called_capital_usd,
    distributed_capital_usd
from violations
