-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        meridex_fund_id,
        fund_name,
        gp_name,
        gp_lei,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        currency,
        domicile
    from {{ ref("raw_meridex_funds") }}
)

select
    meridex_fund_id,
    fund_name,
    gp_name,
    gp_lei,
    fund_lei,
    shared_external_id,
    asset_class,
    strategy,
    vintage_year,
    currency,
    domicile,
    coalesce(meridex_fund_id is null, true) as violation_00,
    coalesce(meridex_fund_id is not null and count(*) over (partition by meridex_fund_id) > 1, true) as violation_01,
    coalesce(fund_name is null, true) as violation_02
from source_00
