-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        chrono_row_uid,
        chrono_vehicle_code,
        vehicle_display_name,
        vehicle_group_name,
        vehicle_form,
        manager_master_code,
        manager_name_text,
        manager_lei,
        legal_entity_identifier,
        vendor_crosswalk_id,
        private_market_bucket,
        investment_style,
        launch_year,
        commitment_amount_usd,
        reporting_ccy,
        domicile_iso2,
        lifecycle_state,
        snapshot_date
    from {{ ref("investment__chrono_fund__checked") }}
),
step_02_schema_transform as (
    select
        cast(chrono_row_uid as {{ dpf_type('string') }}) as source_record_id,
        cast(chrono_vehicle_code as {{ dpf_type('string') }}) as source_fund_id,
        cast(vehicle_display_name as {{ dpf_type('string') }}) as source_name,
        cast(vehicle_group_name as {{ dpf_type('string') }}) as source_family_name,
        cast(vehicle_form as {{ dpf_type('string') }}) as source_vehicle_type,
        cast(legal_entity_identifier as {{ dpf_type('string') }}) as source_lei,
        cast(vendor_crosswalk_id as {{ dpf_type('string') }}) as source_external_id,
        cast(manager_master_code as {{ dpf_type('string') }}) as source_gp_id,
        cast(manager_name_text as {{ dpf_type('string') }}) as source_gp_name,
        cast(manager_lei as {{ dpf_type('string') }}) as source_gp_lei,
        cast(private_market_bucket as {{ dpf_type('string') }}) as source_asset_class,
        cast(investment_style as {{ dpf_type('string') }}) as source_strategy,
        cast(launch_year as {{ dpf_type('int') }}) as source_vintage_year,
        cast(commitment_amount_usd as {{ dpf_decimal_type(18, 2) }}) as source_committed_capital_usd,
        cast(reporting_ccy as {{ dpf_type('string') }}) as source_currency,
        cast(domicile_iso2 as {{ dpf_type('string') }}) as source_domicile,
        cast(lifecycle_state as {{ dpf_type('string') }}) as source_status,
        cast(snapshot_date as {{ dpf_type('date') }}) as source_reported_on
    from checked_input
),
step_03_calculated_fields as (
    select
        source_record_id,
        source_fund_id,
        source_name,
        source_family_name,
        source_vehicle_type,
        source_lei,
        source_external_id,
        source_gp_id,
        source_gp_name,
        source_gp_lei,
        source_asset_class,
        source_strategy,
        source_vintage_year,
        source_committed_capital_usd,
        source_currency,
        source_domicile,
        source_status,
        source_reported_on,
        cast(('chrono') as {{ dpf_type('string') }}) as fund_source_system,
        cast((concat('chrono', ':', source_record_id)) as {{ dpf_type('string') }}) as fund_identity_key,
        cast(({{ dpf_investment_normalised_name("source_name") }}) as {{ dpf_type('string') }}) as fund_normalised_name,
        cast(({{ dpf_investment_normalised_name("source_gp_name") }}) as {{ dpf_type('string') }}) as fund_normalised_gp_name,
        cast((nullif(trim(source_lei), '')) as {{ dpf_type('string') }}) as fund_lei,
        cast((nullif(trim(source_external_id), '')) as {{ dpf_type('string') }}) as fund_external_id,
        cast((nullif(trim(source_gp_lei), '')) as {{ dpf_type('string') }}) as fund_gp_lei
    from step_02_schema_transform
)

select
    source_record_id,
    source_fund_id,
    source_name,
    source_family_name,
    source_vehicle_type,
    source_lei,
    source_external_id,
    source_gp_id,
    source_gp_name,
    source_gp_lei,
    source_asset_class,
    source_strategy,
    source_vintage_year,
    source_committed_capital_usd,
    source_currency,
    source_domicile,
    source_status,
    source_reported_on,
    fund_source_system,
    fund_identity_key,
    fund_normalised_name,
    fund_normalised_gp_name,
    fund_lei,
    fund_external_id,
    fund_gp_lei
from step_03_calculated_fields
