-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(
    materialized='incremental',
    incremental_strategy=dpf_incremental_strategy({"bigquery": "merge", "duckdb": "delete+insert"}),
    unique_key=["deal_hk", "effective_from", "hashdiff_basis_version"]
) }}

with
sat_deal_detail_source as (
    select distinct
        deal_business_key,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_target_company_external_id,
        deal_sourced_on
    from {{ ref("investment__deal_vault__base") }}
    where deal_business_key is not null
),
sat_deal_detail_fingerprinted as (
    select
        {{ dpf_vault_hash(["deal_business_key"]) }} as deal_hk,
        {{ dpf_vault_hash(["deal_name", "deal_strategy", "deal_structure", "deal_target_company_external_id"]) }} as hashdiff,
        1 as hashdiff_basis_version,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_target_company_external_id,
        deal_sourced_on as effective_from,
        {{ dpf_publish_timestamp() }} as load_datetime,
        'investment.deal_vault' as record_source
    from sat_deal_detail_source
),
sat_deal_detail_unstored as (
    select
        deal_hk,
        hashdiff,
        hashdiff_basis_version,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_target_company_external_id,
        effective_from,
        load_datetime,
        record_source
    from sat_deal_detail_fingerprinted
    where {{ dpf_vault_new_versions("sat_deal_detail_fingerprinted", "deal_hk", "hashdiff", "effective_from", "hashdiff_basis_version", "current") }}
)

select
    cast(deal_hk as {{ dpf_type('string') }}) as deal_hk,
    cast(hashdiff as {{ dpf_type('string') }}) as hashdiff,
    cast(hashdiff_basis_version as {{ dpf_type('int') }}) as hashdiff_basis_version,
    cast(deal_name as {{ dpf_type('string') }}) as deal_name,
    cast(deal_strategy as {{ dpf_type('string') }}) as deal_strategy,
    cast(deal_structure as {{ dpf_type('string') }}) as deal_structure,
    cast(deal_channel as {{ dpf_type('string') }}) as deal_channel,
    cast(deal_target_company_external_id as {{ dpf_type('string') }}) as deal_target_company_external_id,
    cast(effective_from as {{ dpf_type('date') }}) as effective_from,
    cast(load_datetime as {{ dpf_type('timestamp') }}) as load_datetime,
    cast(record_source as {{ dpf_type('string') }}) as record_source
from sat_deal_detail_unstored
