-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(
    materialized='incremental',
    incremental_strategy=dpf_incremental_strategy({"bigquery": "merge", "duckdb": "delete+insert"}),
    unique_key=["gp_hk"]
) }}

with
hub_gp_source as (
    select distinct
        gp_business_key
    from {{ ref("investment__gp_vault__base") }}
    where gp_business_key is not null
),
hub_gp_keyed as (
    select
        {{ dpf_vault_hash(["gp_business_key"]) }} as gp_hk,
        gp_business_key,
        {{ dpf_publish_timestamp() }} as load_datetime,
        'investment.gp_vault' as record_source
    from hub_gp_source
),
hub_gp_unstored as (
    select
        gp_hk,
        gp_business_key,
        load_datetime,
        record_source
    from hub_gp_keyed
    where {{ dpf_vault_unstored_key("hub_gp_keyed", "gp_hk") }}
)

select
    cast(gp_hk as {{ dpf_type('string') }}) as gp_hk,
    cast(gp_business_key as {{ dpf_type('string') }}) as gp_business_key,
    cast(load_datetime as {{ dpf_type('timestamp') }}) as load_datetime,
    cast(record_source as {{ dpf_type('string') }}) as record_source
from hub_gp_unstored
