-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        portiq_fund_id,
        fund_name,
        gp_name,
        gp_lei,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        currency,
        violation_00
    from {{ ref("investment__portiq_gp__checked") }}
),
violations as (
    select
        'gp_name_not_null' as rule_name,
        portiq_fund_id,
        fund_name,
        gp_name,
        gp_lei,
        fund_lei,
        shared_external_id,
        asset_class,
        strategy,
        vintage_year,
        currency
    from quarantined
    where violation_00
)

select
    rule_name,
    portiq_fund_id,
    fund_name,
    gp_name,
    gp_lei,
    fund_lei,
    shared_external_id,
    asset_class,
    strategy,
    vintage_year,
    currency
from violations
