-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis,
        violation_00,
        violation_01
    from {{ ref("investment__fund_performance__checked") }}
),
violations as (
    select
        'fund_business_key_not_null' as rule_name,
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis
    from quarantined
    where violation_00

    union all

    select
        'source_valued_on_not_null' as rule_name,
        source_record_id,
        source_fund_id,
        source_valued_on,
        source_nav_usd,
        source_called_capital_usd,
        source_distributed_capital_usd,
        nav_source_system,
        fund_nav_source_key,
        fund_business_key,
        fund_external_id,
        source_name,
        source_strategy,
        source_currency,
        fund_recallable_distributions_usd,
        fund_fee_offset_usd,
        fund_hurdle_rate,
        fund_hurdle_basis
    from quarantined
    where violation_01
)

select
    rule_name,
    source_record_id,
    source_fund_id,
    source_valued_on,
    source_nav_usd,
    source_called_capital_usd,
    source_distributed_capital_usd,
    nav_source_system,
    fund_nav_source_key,
    fund_business_key,
    fund_external_id,
    source_name,
    source_strategy,
    source_currency,
    fund_recallable_distributions_usd,
    fund_fee_offset_usd,
    fund_hurdle_rate,
    fund_hurdle_basis
from violations
