-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        vehicle_cash_flow_id,
        vehicle_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency,
        violation_00,
        violation_01,
        violation_02,
        violation_03
    from {{ ref("investment__vantora_vehicle_cash_flow_extract__checked") }}
),
violations as (
    select
        'vehicle_cash_flow_id_not_null' as rule_name,
        vehicle_cash_flow_id,
        vehicle_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from quarantined
    where violation_00

    union all

    select
        'vehicle_cash_flow_id_unique' as rule_name,
        vehicle_cash_flow_id,
        vehicle_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from quarantined
    where violation_01

    union all

    select
        'vehicle_id_not_null' as rule_name,
        vehicle_cash_flow_id,
        vehicle_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from quarantined
    where violation_02

    union all

    select
        'cash_flow_date_not_null' as rule_name,
        vehicle_cash_flow_id,
        vehicle_id,
        cash_flow_date,
        cash_flow_type,
        direction,
        amount_usd,
        currency
    from quarantined
    where violation_03
)

select
    rule_name,
    vehicle_cash_flow_id,
    vehicle_id,
    cash_flow_date,
    cash_flow_type,
    direction,
    amount_usd,
    currency
from violations
