-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence
    from {{ ref("investment__chrono_valuation_extract") }}
),
step_00_batch_transfer as (
    select
        mark_uid,
        vehicle_code,
        asset_uid,
        mark_date,
        usd_fair_value,
        mark_method,
        fair_value_bucket,
        extraction_confidence
    from source_00
)

select
    mark_uid,
    vehicle_code,
    asset_uid,
    mark_date,
    usd_fair_value,
    mark_method,
    fair_value_bucket,
    extraction_confidence,
    coalesce(mark_uid is null, true) as violation_00,
    coalesce(mark_date is null, true) as violation_01
from step_00_batch_transfer
