-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_origo_deals') }}
),

deal_resolution as (
    select * from {{ ref('res_deal') }}
),

company_lookup as (
    select * from {{ ref('int_deal_target_company') }}
)

select
    source.source_deal_id as source_deal_id,
    source.target_entity_id as target_entity_id,
    source.target_entity_id as target_company_external_id,
    source.sourced_date as effective_from,
    deal_resolution.golden_deal_key as golden_deal_key,
    company_lookup.golden_portfolio_company_key as golden_portfolio_company_key
from source
inner join deal_resolution
    on deal_resolution.source_system = source.source_system
    and deal_resolution.source_id = source.source_deal_id
    and deal_resolution.source_record_id = source.source_record_id
left join company_lookup
    on company_lookup.company_external_id = source.target_entity_id
where deal_resolution.golden_deal_key is not null
    and company_lookup.golden_portfolio_company_key is not null
