-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_chrono_valuations') }}
),

fund_resolution as (
    select * from {{ ref('res_fund') }}
),

company_resolution as (
    select * from {{ ref('res_portfolio_company') }}
)

select
    source.source_system as source_system,
    source.valuation_id as valuation_id,
    source.source_fund_id as source_fund_id,
    source.source_company_id as source_company_id,
    source.valuation_date as valuation_date,
    source.value_usd as value_usd,
    source.method as method,
    source.valuation_level as valuation_level,
    source.confidence_score as confidence_score,
    source.valuation_date as effective_from,
    fund_resolution.golden_fund_key as golden_fund_key,
    fund_resolution.resolution_tier as fund_resolution_tier,
    fund_resolution.confidence as fund_resolution_confidence,
    company_resolution.golden_portfolio_company_key as golden_portfolio_company_key,
    company_resolution.resolution_tier as portfolio_company_resolution_tier,
    company_resolution.confidence as portfolio_company_resolution_confidence
from source
inner join fund_resolution
    on fund_resolution.source_system = source.source_system
    and fund_resolution.source_id = source.source_fund_id
inner join company_resolution
    on company_resolution.source_system = source.source_system
    and company_resolution.source_id = source.source_company_id
where fund_resolution.golden_fund_key is not null
    and company_resolution.golden_portfolio_company_key is not null
