-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_portiq_funds') }}
),

gp_resolution as (
    select * from {{ ref('res_gp') }}
)

select
    source.source_system as source_system,
    concat(source.source_fund_id, ':gp') as source_gp_id,
    source.source_fund_id as source_fund_id,
    source.gp_name as gp_name,
    source.gp_lei as lei,
    cast(null as string) as shared_external_id,
    cast(null as string) as domicile,
    cast(null as date) as relationship_start_date,
    cast(null as date) as effective_from,
    gp_resolution.golden_gp_key as golden_gp_key,
    gp_resolution.resolution_tier as gp_resolution_tier,
    gp_resolution.confidence as gp_resolution_confidence
from source
inner join gp_resolution
    on gp_resolution.source_system = source.source_system
    and gp_resolution.source_id = concat(source.source_fund_id, ':gp')
where gp_resolution.golden_gp_key is not null
