-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_vantora_gps') }}
),

gp_resolution as (
    select * from {{ ref('res_gp') }}
)

select
    source.source_system as source_system,
    source.source_gp_id as source_gp_id,
    cast(null as string) as source_fund_id,
    source.gp_name as gp_name,
    source.lei as lei,
    source.shared_external_id as shared_external_id,
    source.domicile as domicile,
    source.relationship_start_date as relationship_start_date,
    source.relationship_start_date as effective_from,
    gp_resolution.golden_gp_key as golden_gp_key,
    gp_resolution.resolution_tier as gp_resolution_tier,
    gp_resolution.confidence as gp_resolution_confidence
from source
inner join gp_resolution
    on gp_resolution.source_system = source.source_system
    and gp_resolution.source_id = source.source_gp_id
where gp_resolution.golden_gp_key is not null
