-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_vantora_vehicle_cash_flows') }}
)

select
    source.cash_flow_id as cash_flow_id,
    source.vehicle_natural_id as vehicle_natural_id,
    source.cash_flow_date as cash_flow_date,
    source.cash_flow_type as cash_flow_type,
    source.direction as direction,
    source.amount_usd as amount_usd,
    source.currency as currency,
    source.cash_flow_date as effective_from,
    {{ stable_golden_key('legal_vehicle', 'source.vehicle_natural_id') }} as golden_legal_vehicle_key
from source
