-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with source as (
    select * from {{ ref('stg_vantora_succession_events') }}
),

predecessor_gp_resolution as (
    select * from {{ ref('res_gp') }}
),

successor_gp_resolution as (
    select * from {{ ref('res_gp') }}
)

select
    source.succession_event_id as succession_event_id,
    source.predecessor_source_gp_id as predecessor_source_gp_id,
    source.successor_source_gp_id as successor_source_gp_id,
    source.event_type as event_type,
    source.effective_date as effective_date,
    source.effective_date as effective_from,
    predecessor_gp_resolution.golden_gp_key as golden_predecessor_gp_key,
    successor_gp_resolution.golden_gp_key as golden_successor_gp_key
from source
inner join predecessor_gp_resolution
    on predecessor_gp_resolution.source_system = source.source_system
    and predecessor_gp_resolution.source_id = source.predecessor_source_gp_id
inner join successor_gp_resolution
    on successor_gp_resolution.source_system = source.source_system
    and successor_gp_resolution.source_id = source.successor_source_gp_id
where predecessor_gp_resolution.golden_gp_key is not null
    and successor_gp_resolution.golden_gp_key is not null
