-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = ['stg_dv_vantora_portfolio_companies',
 'stg_dv_meridex_portfolio_companies',
 'stg_dv_portiq_portfolio_companies',
 'stg_dv_chrono_portfolio_companies'] -%}
{%- set src_pk = 'portfolio_company_hk' -%}
{%- set src_nk = 'golden_portfolio_company_key' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.hub(
    src_pk=src_pk,
    src_nk=src_nk,
    src_extra_columns=none,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
