-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = ['stg_dv_cartivo_products', 'stg_dv_mercaro_products'] -%}
{%- set src_pk = 'product_hk' -%}
{%- set src_nk = 'golden_product_key' -%}
{%- set src_ldts = 'load_datetime' -%}
{%- set src_source = 'record_source' -%}

{{ automate_dv.hub(
    src_pk=src_pk,
    src_nk=src_nk,
    src_extra_columns=none,
    src_ldts=src_ldts,
    src_source=src_source,
    source_model=source_model
) }}
