-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{{ config(materialized='table', schema='business_vault') }}

{%- set source_satellites = [{'name': 'VANTORA', 'model': 'sat_legal_vehicle_vantora'},
 {'name': 'MERIDEX', 'model': 'sat_legal_vehicle_meridex'}] -%}

{%- set source_priority = ['VANTORA', 'MERIDEX'] -%}

{%- set rules = {'vehicle_natural_id': {'strategy': 'first_non_null',
                        'source_priority': source_priority},
 'source_fund_id': {'strategy': 'first_non_null',
                    'source_priority': source_priority},
 'parent_vehicle_id': {'strategy': 'first_non_null',
                       'source_priority': source_priority},
 'vehicle_name': {'strategy': 'first_non_null',
                  'source_priority': source_priority},
 'vehicle_type': {'strategy': 'first_non_null',
                  'source_priority': source_priority},
 'jurisdiction': {'strategy': 'first_non_null',
                  'source_priority': source_priority},
 'incorporation_date': {'strategy': 'first_non_null',
                        'source_priority': source_priority},
 'lei': {'strategy': 'first_non_null', 'source_priority': source_priority}} -%}

{{ survivorship_golden_record(
    entity='legal_vehicle',
    hub_model='hub_legal_vehicle',
    hub_pk='legal_vehicle_hk',
    hub_nk='golden_legal_vehicle_key',
    source_satellites=source_satellites,
    attribute_rules=rules
) }}
