-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{{ config(materialized='table', schema='business_vault') }}

{%- set source_satellites = [{'name': 'VANTORA', 'model': 'sat_portfolio_company_vantora'},
 {'name': 'MERIDEX', 'model': 'sat_portfolio_company_meridex'},
 {'name': 'PORTIQ', 'model': 'sat_portfolio_company_portiq'},
 {'name': 'CHRONO', 'model': 'sat_portfolio_company_chrono'}] -%}

{%- set source_priority = ['VANTORA', 'MERIDEX', 'PORTIQ', 'CHRONO'] -%}

{%- set rules = {'source_company_id': {'strategy': 'first_non_null',
                       'source_priority': source_priority},
 'source_fund_id': {'strategy': 'first_non_null',
                    'source_priority': source_priority},
 'company_name': {'strategy': 'first_non_null',
                  'source_priority': source_priority},
 'lei': {'strategy': 'first_non_null', 'source_priority': source_priority},
 'shared_external_id': {'strategy': 'first_non_null',
                        'source_priority': source_priority},
 'sector': {'strategy': 'first_non_null', 'source_priority': source_priority},
 'sub_sector': {'strategy': 'first_non_null', 'source_priority': source_priority},
 'country': {'strategy': 'first_non_null', 'source_priority': source_priority},
 'status': {'strategy': 'most_recent', 'source_priority': source_priority},
 'first_seen_at': {'strategy': 'most_recent', 'source_priority': source_priority},
 'portfolio_company_resolution_tier': {'strategy': 'first_non_null',
                                       'source_priority': source_priority},
 'portfolio_company_resolution_confidence': {'strategy': 'first_non_null',
                                             'source_priority': source_priority}} -%}

{{ survivorship_golden_record(
    entity='portfolio_company',
    hub_model='hub_portfolio_company',
    hub_pk='portfolio_company_hk',
    hub_nk='golden_portfolio_company_key',
    source_satellites=source_satellites,
    attribute_rules=rules
) }}
