"""The dbt translator: static Bronze contract tests, schema projections,
generated sources, integrity/timeliness diagnostics and staging joins on
visibility identities.

This translator never claims execution ownership. The local-ingestion
translator owns every Bronze occurrence; this one observes contract, schema,
publish, lineage and metadata so generated dbt artefacts stay projections of
the same graph/contract identity. Operational telemetry never enters the
artefacts this module places in ODCS/ODPS -- those projections live in
``emit_contracts`` / ``emit_odps``. dbt diagnostic tests may *read* the
published-ledger and stream-status relations; they do not write product facts.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined
from pydantic import ValidationError

from ergasterion.framework.bronze_contract import BronzeProductContract, LogicalIdentity
from ergasterion.framework.models import (
    ExecutionPlan,
    Layer,
    TranslationResult,
    compute_plan_digest,
)
from ergasterion.framework.resolver import resolve
from ergasterion.framework.runtime_binding import RuntimeBinding
from ergasterion.source_delivery import TypedDeclarations, TypedTable
from ergasterion.translators.base import Translator

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"
SQL_HEADER = "-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand."
YAML_HEADER = "# Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand."

_OBSERVED = frozenset(
    {
        "bronze.contract",
        "bronze.schema",
        "bronze.publish",
        "bronze.lineage",
        "bronze.metadata",
    }
)

BINDING_ID_RE = re.compile(r"^[a-z][a-z0-9_-]{0,62}$")
PRODUCTION_IDENTITY_RE = re.compile(r"^[a-z_][a-z0-9_]*$")

MANAGED_DELIVERY_ID = "_ergasterion_delivery_id"
MANAGED_EPOCH = "_ergasterion_visibility_epoch"
MANAGED_KIND = "_ergasterion_visibility_kind"
MANAGED_ID = "_ergasterion_visibility_id"

PROJECTION_SOURCE_TABLES = (
    "published_ledger",
    "stream_status",
    "active_alias",
)


def bronze_plan() -> ExecutionPlan:
    return resolve(Layer.BRONZE)


def bronze_plan_digest() -> str:
    return compute_plan_digest(bronze_plan())


def identity_key(identity: LogicalIdentity) -> str:
    """The same compact JSON key the reference projection ledger stores."""
    return json.dumps(
        {
            "estate_namespace": identity.estate_namespace,
            "source": identity.source,
            "table": identity.table,
        },
        sort_keys=True,
        separators=(",", ":"),
    )


def graph_contract_identity(
    table: TypedTable, *, plan_digest: str | None = None
) -> dict[str, str]:
    """One identity shared by runtime, ODCS, ODPS and dbt. Product facts and
    digests only -- no attempt, heartbeat, committed_at or other run telemetry."""
    if table.contract is None or table.contract_digest is None:
        raise ValueError(f"{table.source_name}.{table.table_name}: draft has no contract identity")
    ident = table.contract.logical_identity
    return {
        "estate_namespace": ident.estate_namespace,
        "source": ident.source,
        "table": ident.table,
        "product_version": table.contract.product.product_version,
        "contract_digest": table.contract_digest,
        "source_schema_digest": table.source_schema_digest or "",
        "published_schema_digest": table.published_schema_digest or "",
        "execution_plan_digest": plan_digest or bronze_plan_digest(),
        "domain": table.contract.product.domain,
    }


def bronze_odcs_id(identity: dict[str, str]) -> str:
    return (
        f"dpf:bronze:{identity['estate_namespace']}:{identity['source']}:{identity['table']}"
    )


def bronze_odps_id(identity: dict[str, str]) -> str:
    return (
        f"dpf:bronze:odps:{identity['estate_namespace']}:{identity['source']}:{identity['table']}"
    )


def landing_handle(contract: BronzeProductContract) -> str:
    return f"{contract.landing.source_name}.{contract.landing.identifier}"


def projection_source_name(contract: BronzeProductContract) -> str:
    return f"bronze_{contract.logical_identity.source}_{contract.logical_identity.table}"


def visibility_columns(contract: BronzeProductContract) -> tuple[str, str, str]:
    integration = contract.landing.integration
    if integration.kind == "managed":
        return MANAGED_EPOCH, MANAGED_KIND, MANAGED_ID
    return (
        integration.visibility_epoch_column,
        integration.visibility_kind_column,
        integration.visibility_id_column,
    )


def bronze_product_dir(contracts_dir: Path, identity: LogicalIdentity) -> Path:
    return contracts_dir / "bronze" / identity.estate_namespace / identity.source / identity.table


def bronze_binding_dir(contracts_dir: Path, identity: LogicalIdentity, binding_id: str) -> Path:
    return bronze_product_dir(contracts_dir, identity) / "bindings" / binding_id


def check_casefold_identities(declarations: list[dict[str, Any]]) -> None:
    """Production and source-backed identities must already be canonical;
    two names that differ only by case fail rather than fold."""
    seen: dict[tuple[str, str], str] = {}
    for declaration in declarations:
        source_name = declaration["source"]["name"]
        for table_name, table in declaration.get("tables", {}).items():
            landing = table.get("landing") or {}
            if landing.get("kind") != "source":
                continue
            origin = f"{declaration['source'].get('declaration_file', source_name)}:{table_name}"
            folded = (source_name.casefold(), str(table_name).casefold())
            previous = seen.get(folded)
            if previous is not None and previous != origin:
                raise ValueError(
                    f"case-fold identity collision between {previous} and {origin}"
                )
            seen[folded] = origin
            delivery = table.get("delivery") or {}
            if delivery.get("kind") == "production":
                if not isinstance(source_name, str) or not PRODUCTION_IDENTITY_RE.match(source_name):
                    raise ValueError(
                        f"{origin}: production source name {source_name!r} must already be lowercase"
                    )
                if not isinstance(table_name, str) or not PRODUCTION_IDENTITY_RE.match(table_name):
                    raise ValueError(
                        f"{origin}: production table name {table_name!r} must already be lowercase"
                    )


def reject_draft_generation(typed: TypedDeclarations) -> None:
    drafts = typed.drafts()
    if not drafts:
        return
    names = ", ".join(f"{item.source_name}.{item.table_name}" for item in drafts)
    raise ValueError(
        f"draft delivery cannot generate: {names} "
        "(reason: delivery_contract_required -- supply a production delivery contract)"
    )


def _validate_binding_id(binding: RuntimeBinding) -> None:
    if not BINDING_ID_RE.match(binding.binding_id):
        raise ValueError(
            f"binding_id {binding.binding_id!r} must match [a-z][a-z0-9_-]{{0,62}}"
        )


def load_runtime_bindings(path: Path, environment: str) -> list[RuntimeBinding]:
    """Load one RuntimeBinding YAML file, or a directory of them. ``environment``
    is a mandatory matching assertion against each binding."""
    if not environment:
        raise ValueError("production Bronze generation needs --environment NAME")
    if not path.exists():
        raise ValueError(f"runtime binding not found: {path}")
    files = sorted(path.glob("*.yml")) if path.is_dir() else [path]
    if not files:
        raise ValueError(f"{path}: no runtime binding YAML files")
    bindings: list[RuntimeBinding] = []
    for file in files:
        data = yaml.safe_load(file.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{file}: expected a YAML mapping")
        try:
            binding = RuntimeBinding.model_validate(data)
        except ValidationError as exc:
            raise ValueError(f"{file}: {exc}") from exc
        _validate_binding_id(binding)
        if binding.environment != environment:
            raise ValueError(
                f"{file}: RuntimeBinding.environment {binding.environment!r} "
                f"does not match --environment {environment!r}"
            )
        bindings.append(binding)
    return bindings


def bind_production_sources(
    typed: TypedDeclarations, bindings: list[RuntimeBinding]
) -> dict[tuple[str, str], RuntimeBinding]:
    """Every production contract is bound to exactly one RuntimeBinding whose
    logical identity matches, and whose landing_ports contain the physical
    input for that contract's landing handle. The binding's execution plan
    digest must equal the resolved Bronze graph so emit, ODCS, ODPS and the
    dbt translator share one identity with the runtime binding."""
    plan_digest = bronze_plan_digest()
    by_identity: dict[tuple[str, str], RuntimeBinding] = {}
    for binding in bindings:
        ident = binding.logical_identity
        key = (ident.source, ident.table)
        if key in by_identity:
            raise ValueError(
                f"duplicate runtime binding for ({ident.source}, {ident.table})"
            )
        by_identity[key] = binding

    bound: dict[tuple[str, str], RuntimeBinding] = {}
    for key, table in typed.tables.items():
        if table.kind != "production" or table.contract is None:
            continue
        binding = by_identity.get(key)
        if binding is None:
            raise ValueError(
                f"{key[0]}.{key[1]}: physical inputs bind -- no RuntimeBinding "
                "matches this logical identity"
            )
        ident = table.contract.logical_identity
        if (
            binding.logical_identity.estate_namespace != ident.estate_namespace
            or binding.logical_identity.source != ident.source
            or binding.logical_identity.table != ident.table
        ):
            raise ValueError(
                f"{key[0]}.{key[1]}: RuntimeBinding logical identity does not match the contract"
            )
        if binding.contract_digest != table.contract_digest:
            raise ValueError(
                f"{key[0]}.{key[1]}: RuntimeBinding.contract_digest does not match the compiled contract"
            )
        if binding.execution_plan_digest != plan_digest:
            raise ValueError(
                f"{key[0]}.{key[1]}: RuntimeBinding.execution_plan_digest does not match the "
                f"resolved Bronze graph {plan_digest}"
            )
        handle = landing_handle(table.contract)
        if handle not in binding.landing_ports:
            raise ValueError(
                f"{key[0]}.{key[1]}: physical inputs bind -- landing handle "
                f"{handle!r} is missing from RuntimeBinding.landing_ports"
            )
        bound[key] = binding

    unused = set(by_identity) - set(bound)
    if unused:
        leftover = ", ".join(f"{source}.{table}" for source, table in sorted(unused))
        raise ValueError(f"RuntimeBinding(s) name unbound product(s): {leftover}")
    return bound


def _sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def visibility_join_sql(table: TypedTable, binding: RuntimeBinding) -> str:
    """Pre-rendered FROM-clause join so the Jinja template never names a
    Bronze contract fact. Staging becomes visible only through the published
    delivery projection."""
    contract = table.contract
    assert contract is not None
    epoch_col, kind_col, id_col = visibility_columns(contract)
    source_name = projection_source_name(contract)
    ident = identity_key(contract.logical_identity)
    target = binding.projection_target
    source_call = "{{ source('" + source_name + "', 'published_ledger') }}"
    return (
        f"\ninner join {source_call} as published\n"
        f"    on source.{epoch_col} = published.visibility_epoch\n"
        f"   and source.{kind_col} = published.visibility_kind\n"
        f"   and source.{id_col} = published.visibility_id\n"
        f"   and published.identity_key = {_sql_string(ident)}\n"
        f"   and published.projection_target = {_sql_string(target)}"
    )


def bronze_source_yaml(
    table: TypedTable, binding: RuntimeBinding, *, plan_digest: str
) -> str:
    """Pre-rendered YAML indented for a dbt source table. Built in Python so
    the Jinja template never carries a contract-fact token."""
    identity = graph_contract_identity(table, plan_digest=plan_digest)
    landing = binding.landing_ports[landing_handle(table.contract)]
    lines = [
        f"        identifier: {landing.relation_ref}",
        "        meta:",
        f"          dpf.identity: {json.dumps(identity, sort_keys=True)}",
        "        data_tests:",
        "          - dpf_projection_integrity:",
        f"              identity_key: {json.dumps(identity_key(table.contract.logical_identity))}",
        f"              projection_target: {json.dumps(binding.projection_target)}",
        "          - dpf_schedule_timeliness:",
        f"              identity_key: {json.dumps(identity_key(table.contract.logical_identity))}",
        f"              projection_target: {json.dumps(binding.projection_target)}",
    ]
    maximum_age = table.contract.delivery.maximum_age if table.contract is not None else None
    if maximum_age is not None:
        query = "{{ dpf_source_freshness_query() }}"
        lines.extend(
            [
                "        config:",
                "          freshness:",
                f"            warn_after: {{count: {maximum_age.warn_after_minutes}, period: minute}}",
                f"            error_after: {{count: {maximum_age.error_after_minutes}, period: minute}}",
                f"          loaded_at_query: {json.dumps(query)}",
            ]
        )
    return "\n".join(lines)


def projection_source_group(table: TypedTable, binding: RuntimeBinding) -> dict[str, Any]:
    contract = table.contract
    assert contract is not None
    relations = binding.projection_relations
    group: dict[str, Any] = {
        "name": projection_source_name(contract),
        "schema": relations.schema_ref,
        "tables": [
            {
                "name": name,
                "identifier": getattr(relations, name),
            }
            for name in PROJECTION_SOURCE_TABLES
        ],
    }
    if relations.database_ref is not None:
        group["database"] = relations.database_ref
    return group


def annotate_production_tables(
    declarations: list[dict[str, Any]],
    typed: TypedDeclarations,
    bound: dict[tuple[str, str], RuntimeBinding],
    *,
    plan_digest: str | None = None,
) -> list[dict[str, Any]]:
    """Attach pre-rendered dbt fragments to production tables. Seed and draft
    tables are left untouched so their generated bytes stay identical."""
    digest = plan_digest or bronze_plan_digest()
    for declaration in declarations:
        source_name = declaration["source"]["name"]
        for table_name, table in declaration.get("tables", {}).items():
            table.setdefault("visibility_join", "")
            table.setdefault("bronze_source_yaml", "")
            key = (source_name, table_name)
            typed_table = typed.tables.get(key)
            if typed_table is None or typed_table.kind != "production":
                continue
            binding = bound[key]
            landing = binding.landing_ports[landing_handle(typed_table.contract)]
            table["visibility_join"] = visibility_join_sql(typed_table, binding)
            table["bronze_source_yaml"] = bronze_source_yaml(
                typed_table, binding, plan_digest=digest
            )
            table["landing_database"] = landing.database_ref
            table["landing_schema"] = landing.schema_ref
    return declarations


def production_projection_groups(
    typed: TypedDeclarations, bound: dict[tuple[str, str], RuntimeBinding]
) -> list[dict[str, Any]]:
    groups = []
    for key in sorted(bound):
        groups.append(projection_source_group(typed.tables[key], bound[key]))
    return groups


def attach_source_physical_coords(source_groups: list[dict[str, Any]]) -> None:
    """Copy landing database/schema from the first annotated table onto the
    dbt source group so physical inputs bind in generated sources.yml."""
    for group in source_groups:
        database = None
        schema = None
        for table in group["tables"]:
            if table.get("landing_database"):
                database = table["landing_database"]
            if table.get("landing_schema"):
                schema = table["landing_schema"]
        if database:
            group["database"] = database
        if schema:
            group["schema"] = schema


def template_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        trim_blocks=False,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    return env


def _normalise_sql_newlines(text: str) -> str:
    lines = [line.rstrip() for line in text.strip().splitlines()]
    return "\n".join(lines) + "\n"


class DbtTranslator(Translator):
    """Observes the Bronze graph and emits dbt sources, staging joins and
    diagnostic tests for production products. Seed fixtures are out of scope:
    ``ergasterion.emit.generate_files`` remains the seed renderer."""

    def __init__(
        self,
        *,
        typed: TypedDeclarations,
        bound: dict[tuple[str, str], RuntimeBinding],
        declarations: list[dict[str, Any]] | None = None,
        plan_digest: str | None = None,
    ) -> None:
        self._typed = typed
        self._bound = bound
        self._declarations = declarations or []
        self._plan_digest = plan_digest or bronze_plan_digest()

    @property
    def target_name(self) -> str:
        return "dbt"

    def owned_occurrences(self) -> frozenset[str]:
        return frozenset()

    def observed_occurrences(self) -> frozenset[str]:
        return _OBSERVED if self._bound else frozenset()

    def execution_order(self) -> tuple[str, ...]:
        return ()

    def plan_digest(self) -> str | None:
        return self._plan_digest

    def validate_compatibility(self, plan: ExecutionPlan) -> list[str]:
        issues: list[str] = []
        expected = compute_plan_digest(plan)
        if expected != self._plan_digest:
            issues.append(
                f"translator was built against plan digest {self._plan_digest}, "
                f"plan digest is {expected}"
            )
        return issues

    def translate(self, plan: ExecutionPlan) -> TranslationResult:
        env = template_env()
        artefacts: dict[str, str] = {}
        identities: dict[str, dict[str, str]] = {}
        production_tables: list[dict[str, Any]] = []
        annotate_production_tables(
            self._declarations, self._typed, self._bound, plan_digest=self._plan_digest
        )
        for declaration in self._declarations:
            source_name = declaration["source"]["name"]
            for table_name, table in declaration.get("tables", {}).items():
                key = (source_name, table_name)
                if key not in self._bound:
                    continue
                production_tables.append(table)
                identities[f"{source_name}.{table_name}"] = graph_contract_identity(
                    self._typed.tables[key], plan_digest=self._plan_digest
                )
                artefacts[f"models/staging/{table['staging_model']}.sql"] = _normalise_sql_newlines(
                    env.get_template("staging.sql.j2").render(
                        generated_header=SQL_HEADER, table=table
                    )
                )
        source_groups_by_name: dict[str, dict[str, Any]] = {}
        for table in production_tables:
            source_name = table["landing"]["source_name"]
            group = source_groups_by_name.setdefault(source_name, {"name": source_name, "tables": []})
            group["tables"].append(table)
        attach_source_physical_coords(list(source_groups_by_name.values()))
        projection_groups = production_projection_groups(self._typed, self._bound)
        if production_tables:
            artefacts["models/staging/_bronze.yml"] = _normalise_sql_newlines(
                env.get_template("sources.yml.j2").render(
                    generated_header=YAML_HEADER,
                    seed_tables=[],
                    source_groups=list(source_groups_by_name.values()),
                    projection_source_groups=projection_groups,
                    staging_tables=production_tables,
                )
            )
        return TranslationResult(
            artefacts=artefacts,
            metadata={
                "target_name": self.target_name,
                "identities": identities,
                "execution_plan_digest": self._plan_digest,
            },
        )
