-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_portiq_portfolio_companies' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!PORTIQ_PORTFOLIO_COMPANIES'} -%}
{%- set hashed_columns = {'portfolio_company_hk': 'golden_portfolio_company_key',
 'fund_hk': 'golden_fund_key',
 'fund_portfolio_company_lhk': ['golden_fund_key', 'golden_portfolio_company_key'],
 'portfolio_company_hashdiff': {'is_hashdiff': True,
                                'columns': ['source_company_id',
                                            'source_fund_id',
                                            'company_name',
                                            'lei',
                                            'shared_external_id',
                                            'sector',
                                            'sub_sector',
                                            'country',
                                            'status',
                                            'first_seen_at',
                                            'portfolio_company_resolution_tier',
                                            'portfolio_company_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
