-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_chrono_valuations' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!CHRONO_VALUATIONS'} -%}
{%- set hashed_columns = {'fund_hk': 'golden_fund_key',
 'portfolio_company_hk': 'golden_portfolio_company_key',
 'fund_portfolio_company_lhk': ['golden_fund_key', 'golden_portfolio_company_key'],
 'fund_valuation_hashdiff': {'is_hashdiff': True,
                             'columns': ['valuation_id',
                                         'source_fund_id',
                                         'source_company_id',
                                         'valuation_date',
                                         'value_usd',
                                         'method',
                                         'valuation_level',
                                         'confidence_score',
                                         'fund_resolution_tier',
                                         'fund_resolution_confidence',
                                         'portfolio_company_resolution_tier',
                                         'portfolio_company_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
