-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_relatio_customers' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!RELATIO_CUSTOMERS'} -%}
{%- set hashed_columns = {'customer_hk': 'golden_customer_key',
 'customer_hashdiff': {'is_hashdiff': True,
                       'columns': ['source_record_id',
                                   'source_customer_id',
                                   'loyalty_id',
                                   'email',
                                   'full_name',
                                   'phone',
                                   'address_line',
                                   'city',
                                   'postal_code',
                                   'country',
                                   'marketing_consent',
                                   'preferred_channel',
                                   'buyer_segment',
                                   'customer_status',
                                   'as_of_date',
                                   'customer_resolution_tier',
                                   'customer_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
