-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_vantora_gps' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!VANTORA_GPS'} -%}
{%- set hashed_columns = {'gp_hk': 'golden_gp_key',
 'gp_hashdiff': {'is_hashdiff': True,
                 'columns': ['source_gp_id',
                             'source_fund_id',
                             'gp_name',
                             'lei',
                             'shared_external_id',
                             'domicile',
                             'relationship_start_date',
                             'gp_resolution_tier',
                             'gp_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
