-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_vantora_funds' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!VANTORA_FUNDS'} -%}
{%- set hashed_columns = {'fund_hk': 'golden_fund_key',
 'gp_hk': 'golden_gp_key',
 'fund_gp_lhk': ['golden_fund_key', 'golden_gp_key'],
 'fund_hashdiff': {'is_hashdiff': True,
                   'columns': ['source_record_id',
                               'source_fund_id',
                               'source_gp_id',
                               'fund_name',
                               'fund_family_name',
                               'vehicle_type',
                               'gp_name',
                               'lei',
                               'shared_external_id',
                               'asset_class',
                               'strategy',
                               'vintage_year',
                               'committed_capital_usd',
                               'currency',
                               'domicile',
                               'fund_status',
                               'as_of_date',
                               'fund_resolution_tier',
                               'fund_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
