-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_origo_deals' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!ORIGO_DEALS'} -%}
{%- set hashed_columns = {'deal_hk': 'golden_deal_key',
 'deal_hashdiff': {'is_hashdiff': True,
                   'columns': ['source_record_id',
                               'source_deal_id',
                               'external_deal_id',
                               'deal_name',
                               'target_entity_id',
                               'strategy',
                               'originating_team',
                               'source_channel',
                               'sourced_date',
                               'structure',
                               'converted_record_type',
                               'converted_record_id',
                               'deal_resolution_tier',
                               'deal_resolution_confidence']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
