-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
{%- set source_model = 'br_dv_vantora_legal_vehicles' -%}
{%- set derived_columns = {'load_datetime': 'current_timestamp', 'record_source': '!VANTORA_LEGAL_VEHICLES'} -%}
{%- set hashed_columns = {'legal_vehicle_hk': 'golden_legal_vehicle_key',
 'fund_hk': 'golden_fund_key',
 'investment_vehicle_lhk': ['golden_fund_key', 'golden_legal_vehicle_key'],
 'legal_vehicle_hashdiff': {'is_hashdiff': True,
                            'columns': ['vehicle_natural_id',
                                        'source_fund_id',
                                        'parent_vehicle_id',
                                        'vehicle_name',
                                        'vehicle_type',
                                        'jurisdiction',
                                        'incorporation_date',
                                        'lei']}} -%}

{{ automate_dv.stage(
    include_source_columns=true,
    source_model=source_model,
    derived_columns=derived_columns,
    hashed_columns=hashed_columns
) }}
