-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with candidates as (
    select
        source_system as source_system,
        source_customer_id as source_id,
        source_record_id as source_record_id,
        full_name as customer_name,
        {{ normalise_name('full_name') }} as normalised_name,
        email as email,
        nullif(lower(trim(cast(email as string))), '') as normalised_email,
        loyalty_id as loyalty_id,
        city as city
    from {{ ref('stg_relatio_customers') }} as source


    union all


    select
        source_system as source_system,
        source_customer_id as source_id,
        source_record_id as source_record_id,
        full_name as customer_name,
        {{ normalise_name('full_name') }} as normalised_name,
        email as email,
        nullif(lower(trim(cast(email as string))), '') as normalised_email,
        loyalty_id as loyalty_id,
        city as city
    from {{ ref('stg_cartivo_customers') }} as source


    union all


    select
        source_system as source_system,
        source_customer_id as source_id,
        source_record_id as source_record_id,
        full_name as customer_name,
        {{ normalise_name('full_name') }} as normalised_name,
        email as email,
        nullif(lower(trim(cast(email as string))), '') as normalised_email,
        loyalty_id as loyalty_id,
        city as city
    from {{ ref('stg_mercaro_customers') }} as source

),

keyed as (
    select
        *,
        case
            when loyalty_id is not null then concat('loyalty:', upper(loyalty_id))
            when normalised_email is not null then concat('email:', normalised_email)
        end as deterministic_match_key,
        case
            when loyalty_id is not null then 'loyalty_id'
            when normalised_email is not null then 'normalised_email'
        end as exact_key_type
    from candidates
),

scored as (
    select
        *,
        count(*) over (partition by deterministic_match_key) as match_row_count,
        count(distinct source_system) over (partition by deterministic_match_key) as match_source_count
    from keyed
)

select
    source_system as source_system,
    source_id as source_id,
    source_record_id as source_record_id,
    customer_name as customer_name,
    normalised_name as normalised_name,
    deterministic_match_key as deterministic_match_key,
    exact_key_type as exact_key_type,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then {{ stable_golden_key('customer', 'deterministic_match_key') }}
    end as golden_customer_key,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 'tier_1_deterministic_exact_id'
    end as resolution_tier,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
             and exact_key_type = 'normalised_name'
            then 0.95
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 1.00
        else 0.00
    end as confidence,
    not (
        deterministic_match_key is not null
        and (exact_key_type != 'normalised_name' or match_row_count > 1)
    ) as pending_probabilistic,
    email,
    normalised_email,
    loyalty_id,
    city,
    match_row_count,
    match_source_count
from scored
