-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with candidates as (
    select
        source_system as source_system,
        source_deal_id as source_id,
        source_record_id as source_record_id,
        deal_name as deal_name,
        {{ normalise_name('deal_name') }} as normalised_name,
        external_deal_id as external_deal_id,
        strategy as strategy,
        sourced_date as sourced_date
    from {{ ref('stg_origo_deals') }} as source

),

keyed as (
    select
        *,
        case
            when external_deal_id is not null then concat('deal_ext:', upper(external_deal_id))
            when normalised_name is not null then concat('name:', normalised_name)
        end as deterministic_match_key,
        case
            when external_deal_id is not null then 'external_deal_id'
            when normalised_name is not null then 'normalised_name'
        end as exact_key_type
    from candidates
),

scored as (
    select
        *,
        count(*) over (partition by deterministic_match_key) as match_row_count,
        count(distinct source_system) over (partition by deterministic_match_key) as match_source_count
    from keyed
)

select
    source_system as source_system,
    source_id as source_id,
    source_record_id as source_record_id,
    deal_name as deal_name,
    normalised_name as normalised_name,
    deterministic_match_key as deterministic_match_key,
    exact_key_type as exact_key_type,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then {{ stable_golden_key('deal', 'deterministic_match_key') }}
    end as golden_deal_key,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 'tier_1_deterministic_exact_id'
    end as resolution_tier,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
             and exact_key_type = 'normalised_name'
            then 0.95
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 1.00
        else 0.00
    end as confidence,
    not (
        deterministic_match_key is not null
        and (exact_key_type != 'normalised_name' or match_row_count > 1)
    ) as pending_probabilistic,
    external_deal_id,
    strategy,
    sourced_date,
    match_row_count,
    match_source_count
from scored
