-- Generated by ergasterion/emit.py from declarations/*.yml. Do not edit by hand.
with candidates as (
    select
        source_system as source_system,
        source_company_id as source_id,
        source_fund_id as source_fund_id,
        company_name as company_name,
        {{ normalise_name('company_name') }} as normalised_name,
        lei as lei,
        shared_external_id as shared_external_id,
        sector as sector,
        country as country
    from {{ ref('stg_vantora_portfolio_companies') }} as source


    union all


    select
        source_system as source_system,
        source_company_id as source_id,
        source_fund_id as source_fund_id,
        company_name as company_name,
        {{ normalise_name('company_name') }} as normalised_name,
        lei as lei,
        shared_external_id as shared_external_id,
        sector as sector,
        country as country
    from {{ ref('stg_meridex_portfolio_companies') }} as source


    union all


    select
        source_system as source_system,
        source_company_id as source_id,
        source_fund_id as source_fund_id,
        company_name as company_name,
        {{ normalise_name('company_name') }} as normalised_name,
        lei as lei,
        shared_external_id as shared_external_id,
        sector as sector,
        country as country
    from {{ ref('stg_portiq_portfolio_companies') }} as source


    union all


    select
        source_system as source_system,
        source_company_id as source_id,
        source_fund_id as source_fund_id,
        company_name as company_name,
        {{ normalise_name('company_name') }} as normalised_name,
        lei as lei,
        shared_external_id as shared_external_id,
        sector as sector,
        country as country
    from {{ ref('stg_chrono_portfolio_companies') }} as source

),

keyed as (
    select
        *,
        case
            when lei is not null then concat('lei:', upper(lei))
            when shared_external_id is not null then concat('external:', upper(shared_external_id))
            when normalised_name is not null then concat('name:', normalised_name)
        end as deterministic_match_key,
        case
            when lei is not null then 'lei'
            when shared_external_id is not null then 'shared_external_id'
            when normalised_name is not null then 'normalised_name'
        end as exact_key_type
    from candidates
),

scored as (
    select
        *,
        count(*) over (partition by deterministic_match_key) as match_row_count,
        count(distinct source_system) over (partition by deterministic_match_key) as match_source_count
    from keyed
)

select
    source_system as source_system,
    source_id as source_id,
    source_fund_id as source_fund_id,
    company_name as company_name,
    normalised_name as normalised_name,
    deterministic_match_key as deterministic_match_key,
    exact_key_type as exact_key_type,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then {{ stable_golden_key('portfolio_company', 'deterministic_match_key') }}
    end as golden_portfolio_company_key,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 'tier_1_deterministic_exact_id'
    end as resolution_tier,
    case
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
             and exact_key_type = 'normalised_name'
            then 0.95
        when deterministic_match_key is not null
             and (exact_key_type != 'normalised_name' or match_row_count > 1)
            then 1.00
        else 0.00
    end as confidence,
    not (
        deterministic_match_key is not null
        and (exact_key_type != 'normalised_name' or match_row_count > 1)
    ) as pending_probabilistic,
    lei,
    shared_external_id,
    sector,
    country,
    match_row_count,
    match_source_count
from scored
