-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
fund_identity_source as (
    select
        external_ids,
        lei,
        fund_name
    from {{ ref("investment__fund_canonical__base") }}
)

select
    cast(external_ids as {{ dpf_type('string') }}) as external_ids,
    cast(lei as {{ dpf_type('string') }}) as lei,
    cast(fund_name as {{ dpf_type('string') }}) as fund_name
from fund_identity_source
