-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        deal_hk,
        deal_business_key,
        deal_name,
        deal_strategy,
        deal_structure,
        deal_channel,
        deal_originating_team,
        deal_target_company_external_id,
        deal_converted_record_type,
        deal_converted_fund_external_id,
        deal_external_identity,
        load_datetime,
        record_source
    from {{ ref("investment__deal_canonical__checked") }}
),
step_02_schema_transform as (
    select
        cast(deal_business_key as {{ dpf_type('string') }}) as deal_id,
        cast(deal_name as {{ dpf_type('string') }}) as deal_name,
        cast(deal_target_company_external_id as {{ dpf_type('string') }}) as target_entity_id,
        cast(deal_strategy as {{ dpf_type('string') }}) as strategy,
        cast(deal_originating_team as {{ dpf_type('string') }}) as originating_team,
        cast(deal_channel as {{ dpf_type('string') }}) as source_channel,
        cast(deal_structure as {{ dpf_type('string') }}) as structure,
        cast(deal_converted_record_type as {{ dpf_type('string') }}) as converted_record_type,
        cast(deal_converted_fund_external_id as {{ dpf_type('string') }}) as converted_record_id
    from checked_input
)

select
    deal_id,
    deal_name,
    target_entity_id,
    strategy,
    originating_team,
    source_channel,
    structure,
    converted_record_type,
    converted_record_id
from step_02_schema_transform
