-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
legal_vehicle_source as (
    select
        vehicle_id,
        lei,
        vehicle_name,
        vehicle_type,
        jurisdiction,
        incorporation_date,
        investment_id
    from {{ ref("investment__legal_vehicle_canonical__base") }}
)

select
    cast(vehicle_id as {{ dpf_type('string') }}) as vehicle_id,
    cast(lei as {{ dpf_type('string') }}) as lei,
    cast(vehicle_name as {{ dpf_type('string') }}) as vehicle_name,
    cast(vehicle_type as {{ dpf_type('string') }}) as vehicle_type,
    cast(jurisdiction as {{ dpf_type('string') }}) as jurisdiction,
    cast(incorporation_date as {{ dpf_type('date') }}) as incorporation_date,
    cast(investment_id as {{ dpf_type('string') }}) as investment_id
from legal_vehicle_source
