-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        portfolio_company_hk,
        company_business_key,
        company_name,
        company_sector,
        company_sub_sector,
        company_country,
        company_status,
        company_lei,
        company_external_id,
        load_datetime,
        record_source
    from {{ ref("investment__portfolio_company_canonical__checked") }}
),
step_02_schema_transform as (
    select
        cast(company_business_key as {{ dpf_type('string') }}) as external_ids,
        cast(company_lei as {{ dpf_type('string') }}) as lei,
        cast(company_name as {{ dpf_type('string') }}) as company_name,
        cast(company_sector as {{ dpf_type('string') }}) as sector,
        cast(company_sub_sector as {{ dpf_type('string') }}) as sub_sector,
        cast(company_country as {{ dpf_type('string') }}) as country,
        cast(company_status as {{ dpf_type('string') }}) as status
    from checked_input
)

select
    external_ids,
    lei,
    company_name,
    sector,
    sub_sector,
    country,
    status
from step_02_schema_transform
