-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        gp_hk,
        gp_business_key,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        load_datetime,
        record_source
    from {{ ref("investment__gp_vault__golden_gp") }}
),
step_00_batch_transfer as (
    select
        gp_hk,
        gp_business_key,
        gp_name,
        gp_domicile,
        gp_relationship_start_on,
        gp_lei,
        load_datetime,
        record_source
    from source_00
)

select
    gp_hk,
    gp_business_key,
    gp_name,
    gp_domicile,
    gp_relationship_start_on,
    gp_lei,
    load_datetime,
    record_source,
    coalesce(gp_business_key is null, true) as violation_00
from step_00_batch_transfer
