-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
quarantined as (
    select
        legal_vehicle_hk,
        vehicle_business_key,
        vehicle_name,
        vehicle_type,
        vehicle_jurisdiction,
        vehicle_incorporated_on,
        vehicle_fund_source_id,
        vehicle_parent_source_id,
        vehicle_lei,
        vehicle_fund_business_key,
        load_datetime,
        record_source,
        violation_00
    from {{ ref("investment__legal_vehicle_canonical__checked") }}
),
violations as (
    select
        'vehicle_business_key_not_null' as rule_name,
        legal_vehicle_hk,
        vehicle_business_key,
        vehicle_name,
        vehicle_type,
        vehicle_jurisdiction,
        vehicle_incorporated_on,
        vehicle_fund_source_id,
        vehicle_parent_source_id,
        vehicle_lei,
        vehicle_fund_business_key,
        load_datetime,
        record_source
    from quarantined
    where violation_00
)

select
    rule_name,
    legal_vehicle_hk,
    vehicle_business_key,
    vehicle_name,
    vehicle_type,
    vehicle_jurisdiction,
    vehicle_incorporated_on,
    vehicle_fund_source_id,
    vehicle_parent_source_id,
    vehicle_lei,
    vehicle_fund_business_key,
    load_datetime,
    record_source
from violations
