-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='table') }}

with
checked_input as (
    select
        fund_hk,
        fund_business_key,
        fund_name,
        fund_asset_class,
        fund_strategy,
        fund_gp_business_key,
        fund_vintage_year,
        fund_committed_capital_usd,
        fund_status,
        fund_external_identity,
        fund_lei,
        fund_external_id,
        fund_domicile,
        fund_currency,
        load_datetime,
        record_source
    from {{ ref("investment__fund_canonical__checked") }}
),
step_02_schema_transform as (
    select
        fund_external_id,
        cast(fund_business_key as {{ dpf_type('string') }}) as external_ids,
        cast(fund_lei as {{ dpf_type('string') }}) as lei,
        cast(fund_name as {{ dpf_type('string') }}) as fund_name,
        cast(fund_gp_business_key as {{ dpf_type('string') }}) as gp_id,
        cast(fund_asset_class as {{ dpf_type('string') }}) as asset_class,
        cast(fund_strategy as {{ dpf_type('string') }}) as strategy,
        cast(fund_vintage_year as {{ dpf_type('int') }}) as vintage_year,
        cast(fund_committed_capital_usd as {{ dpf_decimal_type(18, 2) }}) as committed_capital_usd,
        cast(fund_currency as {{ dpf_type('string') }}) as currency,
        cast(fund_domicile as {{ dpf_type('string') }}) as domicile,
        cast(fund_status as {{ dpf_type('string') }}) as fund_status
    from checked_input
)

select
    fund_external_id,
    external_ids,
    lei,
    fund_name,
    gp_id,
    asset_class,
    strategy,
    vintage_year,
    committed_capital_usd,
    currency,
    domicile,
    fund_status
from step_02_schema_transform
