-- Generated by Ergasterion from a product declaration. Do not edit by hand.
{{ config(materialized='view') }}

with
source_00 as (
    select
        legal_vehicle_hk,
        vehicle_business_key,
        vehicle_name,
        vehicle_type,
        vehicle_jurisdiction,
        vehicle_incorporated_on,
        vehicle_fund_source_id,
        vehicle_parent_source_id,
        vehicle_lei,
        vehicle_fund_business_key,
        load_datetime,
        record_source
    from {{ ref("investment__legal_vehicle_vault__golden_legal_vehicle") }}
),
step_00_batch_transfer as (
    select
        legal_vehicle_hk,
        vehicle_business_key,
        vehicle_name,
        vehicle_type,
        vehicle_jurisdiction,
        vehicle_incorporated_on,
        vehicle_fund_source_id,
        vehicle_parent_source_id,
        vehicle_lei,
        vehicle_fund_business_key,
        load_datetime,
        record_source
    from source_00
)

select
    legal_vehicle_hk,
    vehicle_business_key,
    vehicle_name,
    vehicle_type,
    vehicle_jurisdiction,
    vehicle_incorporated_on,
    vehicle_fund_source_id,
    vehicle_parent_source_id,
    vehicle_lei,
    vehicle_fund_business_key,
    load_datetime,
    record_source,
    coalesce(vehicle_business_key is null, true) as violation_00
from step_00_batch_transfer
